#!/bin/bash
NAME="acl"
VERS="2.3.2"
LINK="https://download.savannah.gnu.org/releases/acl/acl-$VERS.tar.xz"
UPST="https://git.savannah.nongnu.org/git/acl.git"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash
32cm --libexecdir=/usr/lib32

}

rdir() {

echo not implemented

}
