#!/bin/bash
NAME="acl"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://download.savannah.gnu.org/releases/acl/acl-$VERS.tar.xz"
UPST="http://download.savannah.gnu.org/releases/acl/?C=M&O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
32cm --libexecdir=/usr/lib32

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
