#!/bin/bash
NAME="acl"
VERS="${!NAME}_version"
LINK="https://download.savannah.gnu.org/releases/acl/acl-$VERS.tar.xz"
UPST="https://archlinux.org/packages/core/x86_64/acl/"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
32cm --libexecdir=/usr/lib32

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
