#!/bin/bash
NAME="alacritty"
VERS="0.15.0-rc1"
LINK="https://github.com/alacritty/alacritty/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/alacritty/alacritty.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS="rust ncurses libxcb freetype2 fontconfig libxi libxcursor libxkbcommon libxrandr desktop-file-utils"
NEWS="The default build instructions disable Wayland support."


idir() {

cargo build --release --no-default-features --features=x11

install -v -D -m755 "target/release/alacritty" "/usr/bin/alacritty"
install -v -D -m644 "extra/logo/alacritty-term.svg" "/usr/share/pixmaps/Alacritty.svg"
desktop-file-install -m 644 --dir "/usr/share/applications/" "extra/linux/Alacritty.desktop"

update-desktop-database

}

rdir() {

echo not implemented

}
