#!/bin/bash
NAME="alacritty"
VERS="0.14.0"
LINK="https://github.com/alacritty/alacritty/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/alacritty/alacritty/tags"
DEPS="rust ncurses libxcb freetype2 fontconfig libxi libxcursor libxkbcommon libxrandr desktop-file-utils"
NEWS="The default build instructions disable Wayland support."


IDIR=$(cat << '~fin.'
opts "x11" "wayland x11"

FEATURES=$(echo "$OPTS" | tr ' ' ',')
cargo build --release --no-default-features --features="$FEATURES"

install -v -D -m755 "target/release/alacritty" "/usr/bin/alacritty"
install -v -D -m644 "extra/logo/alacritty-term.svg" "/usr/share/pixmaps/Alacritty.svg"
desktop-file-install -m 644 --dir "/usr/share/applications/" "extra/linux/Alacritty.desktop"

update-desktop-database

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
