#!/bin/bash
NAME="alsa-lib"
VERS=1.2.12
LINK="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERS.tar.bz2"
DEPS=""


IDIR=$(cat <<EOF

cm
32cm

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
