#!/bin/bash
NAME="alsa-plugins"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.alsa-project.org/files/pub/plugins/alsa-plugins-$VERS.tar.bz2"
DEPS="alsa-lib"


IDIR=$(cat << '~fin.'

cm   --sysconfdir=/etc --disable-libav
32cm --sysconfdir=/etc --disable-libav

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
