#!/bin/bash
NAME="alsa-lib"
VERS="1.2.13"
LINK="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERS.tar.bz2"
UPST="https://github.com/alsa-project/alsa-lib/tags"
DEPS=""


idir() {

cm
32cm

}

rdir() {

echo not implemented

}


