#!/bin/bash
NAME="alsa-plugins"
VERS="1.2.12"
LINK="https://www.alsa-project.org/files/pub/plugins/alsa-plugins-$VERS.tar.bz2"
UPST="https://github.com/alsa-project/alsa-plugins.git"
DEPS="alsa-lib"


idir() {

cm   --sysconfdir=/etc --disable-libav
32cm --sysconfdir=/etc --disable-libav

}

rdir() {

echo not implemented

}
