#!/bin/bash
NAME="alsa-utils"
VERS="1.2.13"
LINK="https://www.alsa-project.org/files/pub/utils/alsa-utils-$VERS.tar.bz2"
UPST="https://github.com/alsa-project/alsa-utils/tags"
DEPS="alsa-lib"


idir() {

cm --disable-alsaconf \
   --disable-bat      \
   --disable-xmlto    \
   --with-curses=ncursesw

alsactl init
alsactl -L store

cat > /etc/asound.conf << "EOF"
# Begin /etc/asound.conf

defaults.pcm.card 1
defaults.ctl.card 1

# End /etc/asound.conf
EOF

}

rdir() {

echo not implemented

}
