#!/bin/bash
NAME="alsa-lib"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERS.tar.bz2"
UPST="https://archlinux.org/packages/extra/x86_64/alsa-lib"
DEPS=""


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
