#!/bin/bash
NAME="alsa_utils"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.alsa-project.org/files/pub/utils/alsa-utils-$VERS.tar.bz2"
DEPS="alsa_lib"


IDIR=$(cat << '~fin.'

cm --disable-alsaconf \
   --disable-bat      \
   --disable-xmlto    \
   --with-curses=ncursesw

alsactl init
alsactl -L store

cat > /etc/asound.conf << "EOF"
# Begin /etc/asound.conf

defaults.pcm.card 1
defaults.ctl.card 1

# End /etc/asound.conf
EOF

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
