#!/bin/bash
NAME="at-spi2-core"
VERS="2.54.0"
LINK="https://download.gnome.org/sources/at-spi2-core/${VERS%.*}/at-spi2-core-$VERS.tar.xz"
UPST="https://github.com/GNOME/at-spi2-core.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n3 | head -n1 | cut -d'_' -f4- | sed 's/_/./g' | cut -d'^' -f1" # fuck at-spi2-core's tagging system
DEPS="bash dbus2 glib libx11 libxi libxtst xprop gsettings-desktop-schemas"


idir() {

mn -D systemd_user_dir=/tmp -D docs=false
rm -vf /tmp/at-spi-dbus-bus.service

}

rdir() {

rm -rvf /lib/libatk-1.0.so*         \
        /lib/libatk-bridge-2.0.so*  \
        /lib/libatspi.so*           \
        /usr/include/atk-1.0        \
        /usr/include/at-spi-2.0     \
        /usr/include/at-spi2-atk    \
        /usr/share/defaults/at-spi2 \
        /usr/lib/gnome-settings-daemon-3.0  \
        /usr/lib/gtk-2.0/modules/libatk-bridge.so

}
