#!/bin/bash
NAME="at_spi2_core"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://download.gnome.org/sources/at-spi2-core/${VERS%.*}/at-spi2-core-$VERS.tar.xz"
DEPS="dbus2 glib xorg_libraries gsettings_desktop_schemas"


IDIR=$(cat << '~fin.'

mn -D systemd_user_dir=/tmp -D docs=false
rm -vf /tmp/at-spi-dbus-bus.service

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /lib/libatk-1.0.so*         \
        /lib/libatk-bridge-2.0.so*  \
        /lib/libatspi.so*           \
        /usr/include/atk-1.0        \
        /usr/include/at-spi-2.0     \
        /usr/include/at-spi2-atk    \
        /usr/share/defaults/at-spi2 \
        /usr/lib/gnome-settings-daemon-3.0  \
        /usr/lib/gtk-2.0/modules/libatk-bridge.so

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
