#!/bin/bash
NAME="automake"
VERS="${!NAME}_version"
LINK="https://ftp.gnu.org/gnu/automake/automake-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
