#!/bin/bash
NAME="automake"
VERS="1.17"
LINK="https://ftp.gnu.org/gnu/automake/automake-$VERS.tar.xz"
UPST="https://git.savannah.gnu.org/git/automake.git"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash

}

rdir() {

echo not implemented

}
