#!/bin/bash
NAME="bzip2"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.sourceware.org/pub/bzip2/bzip2-$VERS.tar.gz"
UPST="https://www.sourceware.org/pub/bzip2/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(8) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

make -f Makefile-libbz2_so
make clean

make
make PREFIX=/usr install
cp -av libbz2.so.* /usr/lib
ln -sv libbz2.so.1.0.8 /usr/lib/libbz2.so

cp -v bzip2-shared /usr/bin/bzip2
for i in /usr/bin/{bzcat,bunzip2}; do
  ln -sfv bzip2 $i
done

rm -fv /usr/lib/libbz2.a

make clean
sed -e "s/^CC=.*/CC=gcc -m32/" -i Makefile{,-libbz2_so}
make -f Makefile-libbz2_so
make libbz2.a

install -Dm755 libbz2.so.1.0.8 /usr/lib32/libbz2.so.1.0.8
ln -sf libbz2.so.1.0.8 /usr/lib32/libbz2.so
ln -sf libbz2.so.1.0.8 /usr/lib32/libbz2.so.1
ln -sf libbz2.so.1.0.8 /usr/lib32/libbz2.so.1.0
install -Dm644 libbz2.a /usr/lib32/libbz2.a

~fin.
)

RDIR=$(cat << '~fin.'

pushd /usr/bin
rm -vf \
    bunzip2         \
    bzcat           \
    bzcmp           \
    bzdiff          \
    bzegrep         \
    bzfgrep         \
    bzgrep          \
    bzip2           \
    bzip2recover    \
    bzless          \
    bzmore          \
    /usr/lib{,32}/libbz2.so*
popd

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
