#!/bin/bash
NAME="cargo-c"
VERS="0.10.9"
LINK="https://github.com/lu-zero/cargo-c/archive/v$VERS/cargo-c-$VERS.tar.gz"
UPST="https://github.com/lu-zero/cargo-c.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS="rust"


idir() {

curl -LO https://github.com/lu-zero/cargo-c/releases/download/v$VERS/Cargo.lock
[ ! -e /usr/include/libssh2.h ] || export LIBSSH2_SYS_USE_PKG_CONFIG=1    &&
[ ! -e /usr/include/sqlite3.h ] || export LIBSQLITE3_SYS_USE_PKG_CONFIG=1 &&

cargo build --release

install -vm755 target/release/cargo-{capi,cbuild,cinstall,ctest} /usr/bin/

}

rdir() {

rm -vf \
    /usr/bin/cargo-c{api,test,build,install}

}
