#!/bin/bash
NAME="cbindgen"
VERS="0.28.0"
LINK="https://github.com/mozilla/cbindgen/archive/v$VERS/cbindgen-$VERS.tar.gz"
UPST="https://github.com/mozilla/cbindgen.git"
DEPS="rust"


idir() {

cargo build --release
install -Dm755 target/release/cbindgen /usr/bin/

}

rdir() {

rm -vf /usr/bin/cbindgen

}
