#!/bin/bash
NAME="cbindgen"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/mozilla/cbindgen/archive/v$VERS/cbindgen-$VERS.tar.gz"
DEPS="rust"


IDIR=$(cat << '~fin.'

cargo build --release
install -Dm755 target/release/cbindgen /usr/bin/

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/cbindgen

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
