#!/bin/bash
NAME="check"
VERS=0.15.2
LINK="https://github.com/libcheck/check/releases/download/$VERS/check-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

export docdir=/tmp/rid/trash
cm
32cm
unset docdir

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
