#!/bin/bash
NAME="check"
VERS=0.15.2
LINK="https://github.com/libcheck/check/releases/download/$VERS/check-$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<EOF

export docdir=/tmp/rid/trash
cm
32cm
unset docdir

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
