#!/bin/bash
NAME="check"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/libcheck/check/releases/download/$VERS/check-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

export docdir=/tmp/rid/trash
cm
32cm
unset docdir

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/checkmk    \
        /usr/lib{,32}/libcheck.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
