#!/bin/bash
NAME="chrony"
VERS="4.6.1"
LINK="https://chrony-project.org/releases/chrony-$VERS.tar.gz"
UPST="https://gitlab.com/chrony/chrony.git"
SELE="div.sect1:nth-child(1) > div:nth-child(2) > div:nth-child(1) > p:nth-child(1) > a:nth-child(1)"
DEPS=""


idir() {

RIDBUILD=false        \
cm                    \
  --disable-readline  \
  --without-editline  \
  --disable-sechash   \
  --without-nettle    \
  --without-gnutls    \
  --without-nss       \
  --without-tomcrypt  \
  --disable-nts       \
  --disable-cmdmon    \
  --disable-refclock  \
  --disable-phc       \
  --disable-pps       \
  --disable-ipv6      \
  --disable-rtc       \
  --disable-privdrop  \
  --without-libcap    \
  --disable-asyncdns  \
  --disable-timestamping

}

rdir() {

echo not implemented

}
