#!/bin/bash
NAME="coreutils"
VERS="9.6"
LINK="https://ftp.gnu.org/gnu/coreutils/coreutils-$VERS.tar.xz"
UPST="git://git.savannah.gnu.org/coreutils.git"
DEPS=""


idir() {

FORCE_UNSAFE_CONFIGURE=1 cm --enable-no-install-program=kill,uptime

mv -vf /usr/bin/chroot /usr/sbin
mv -vf /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8

}

rdir() {

echo not implemented

}
