#!/bin/bash
NAME="coreutils"
VERS="9.5"
LINK="https://ftp.gnu.org/gnu/coreutils/coreutils-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/coreutils/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

[ -e "$RIDSOURCES"/coreutils-$VERS-i18n-2.patch ] || raw https://www.linuxfromscratch.org/patches/lfs/development/coreutils-$VERS-i18n-2.patch

patch -Np1 -i "$RIDSOURCES"/coreutils-$VERS-i18n-2.patch

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 cm --enable-no-install-program=kill,uptime

mv -vf /usr/bin/chroot /usr/sbin
mv -vf /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
