#!/bin/bash
NAME="coreutils"
VERS="9.5"
LINK="https://ftp.gnu.org/gnu/coreutils/coreutils-$VERS.tar.xz"
DOWN="https://www.linuxfromscratch.org/patches/lfs/development/coreutils-$VERS-i18n-2.patch"
UPST="https://ftp.gnu.org/gnu/coreutils/?C=M;O=D"
DEPS=""


idir() {

patch -Np1 -i "$RIDSOURCES"/coreutils-$VERS-i18n-2.patch

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 cm --enable-no-install-program=kill,uptime

mv -vf /usr/bin/chroot /usr/sbin
mv -vf /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8

}

rdir() {

echo not implemented

}
