#!/bin/bash
NAME="cuda"
VERS="12.6.3"
NV=$(gv nvidia)
DOWN="https://developer.download.nvidia.com/compute/cuda/$VERS/local_installers/cuda_${VERS}_${NV}_linux.run"
UPST="https://developer.nvidia.com/cuda-toolkit-archive"
SELE="div.field:nth-child(1) > div:nth-child(1) > div:nth-child(1) > p:nth-child(3) > a:nth-child(3)"
DEPS="nvidia"


idir() {

chmod +x "$RIDSOURCES"/cuda_${VERS}_${NV}_linux.run
cp -vf "$RIDSOURCES"/cuda_${VERS}_${NV}_linux.run .

export CUDA_HOME="/opt/cuda"

echo "Running cuda installer..."
./cuda_${VERS}_${NV}_linux.run  \
  --silent                      \
  --toolkit                     \
  --toolkitpath="$CUDA_HOME"    \
  --no-man-page

pathappend "$CUDA_HOME/bin"

echo "Adding cuda libraries to ld.so.conf.d/cuda.conf"
# useful for ffmpeg which links to cuda's libnppig.so.12
echo "$CUDA_HOME/lib64" > /etc/ld.so.conf.d/cuda.conf

echo "Writing to /etc/env"
if ! grep -q "# cuda end" /etc/env ; then
    cat << EOF >> /etc/env

    # cuda
    export CUDA_HOME=$CUDA_HOME
    pathappend \$CUDA_HOME/bin
    # cuda end
EOF
fi
echo "Done"

}

rdir() {

rm -rvf /opt/cuda
sed -i '/    # cuda/,/    # cuda end/' /etc/env

}
