#!/bin/bash
NAME="curl"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://curl.se/download/curl-$VERS.tar.xz"
DEPS="libpsl"


IDIR=$(cat << '~fin.'

cm --with-openssl                \
   --with-ca-path=/etc/ssl/certs \
   --without-brotli

32cm --with-openssl                \
     --with-ca-path=/etc/ssl/certs \
     --without-brotli

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
