#!/bin/bash
NAME="cython"
VERS="3.1.0a1"
LINK="https://github.com/cython/cython/releases/download/$VERS/cython-$VERS.tar.gz"
UPST="https://github.com/cython/cython.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS=""


idir() {

pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
pip3 install --no-index --find-links=dist --no-cache-dir --no-user Cython

}

rdir() {

echo not implemented

}
