#!/bin/bash
NAME="dbus"
VERS=1.14.10
blfsbsver="20240913"
LINK="https://dbus.freedesktop.org/releases/dbus/dbus-$VERS.tar.xz"
DEPS=""  # xorg-libraries for dbus-launch


IDIR=$(cat <<EOF

cm                                  \
    --sysconfdir=/etc               \
    --localstatedir=/var            \
    --runstatedir=/run              \
    --disable-doxygen-docs          \
    --disable-xml-docs              \
    --with-systemduserunitdir=no    \
    --with-systemdsystemunitdir=no  \
    --docdir=/tmp/rid/trash         \
    --with-system-socket=/run/dbus/system_bus_socket

chown -v root:messagebus /usr/libexec/dbus-daemon-launch-helper &&
chmod -v      4750       /usr/libexec/dbus-daemon-launch-helper

dbus-uuidgen --ensure
ln -sfv /var/lib/dbus/machine-id /etc

raw https://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-$blfsbsver.tar.xz
pushd /tmp/rid/building
tar xvf /etc/rid/sources/blfs-bootscripts-$blfsbsver.tar.xz
cd blfs-bootscripts-$blfsbsver
make install-dbus
popd

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
