#!/bin/bash
NAME="dbus1"
VERS="1.14.10" # odd minor versions represent development branches; although 1.15 is the latest, it's not stable; i may use 1.15 here
LINK="https://dbus.freedesktop.org/releases/dbus/dbus-$VERS.tar.xz"
UPST="https://dbus.freedesktop.org/releases/dbus/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""

# dbus pass 1

idir() {

cm \
    --sysconfdir=/etc               \
    --localstatedir=/var            \
    --runstatedir=/run              \
    --disable-doxygen-docs          \
    --disable-xml-docs              \
    --with-systemduserunitdir=no    \
    --with-systemdsystemunitdir=no  \
    --docdir=/tmp/rid/trash         \
    --with-system-socket=/run/dbus/system_bus_socket

chown -v root:messagebus /usr/libexec/dbus-daemon-launch-helper &&
chmod -v      4750       /usr/libexec/dbus-daemon-launch-helper

dbus-uuidgen --ensure
ln -sfv /var/lib/dbus/machine-id /etc

CC="gcc -m32" CXX="g++ -m32"                     \
PKG_CONFIG_PATH="/usr/lib32/pkgconfig"           \
./configure --prefix=/usr                        \
            --libdir=/usr/lib32                  \
            --host=i686-pc-linux-gnu             \
            --sysconfdir=/etc                    \
            --localstatedir=/var                 \
            --runstatedir=/run                   \
            --disable-doxygen-docs               \
            --disable-xml-docs                   \
            --disable-static                     \
            --with-systemduserunitdir=no         \
            --with-systemdsystemunitdir=no       \
            --with-system-socket=/run/dbus/system_bus_socket &&

make  || die "Make failed"
make DESTDIR=$PWD/DESTDIR install     &&
cp -vR DESTDIR/usr/lib32/* /usr/lib32 &&
rm -rf DESTDIR                        &&
ldconfig  || die "Install failed"

}

rdir() {

echo not implemented

}


