#!/bin/bash
NAME="dbus2"
VERS="1.14.10"
DOWN="https://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20240913.tar.xz"
UPST="https://dbus.freedesktop.org/releases/dbus/?C=M;O=D"
DEPS="dbus1 @xorg-libs"


idir() {
tar xvf "$RIDSOURCES"/dbus1-$VERS.tar &&
cd dbus-$VERS                         ||
die "Failed to extract tarball"

cm \
    --sysconfdir=/etc               \
    --localstatedir=/var            \
    --runstatedir=/run              \
    --disable-doxygen-docs          \
    --disable-xml-docs              \
    --with-systemduserunitdir=no    \
    --with-systemdsystemunitdir=no  \
    --docdir=/tmp/rid/trash         \
    --with-system-socket=/run/dbus/system_bus_socket

chown -v root:messagebus /usr/libexec/dbus-daemon-launch-helper
chmod -v      4750       /usr/libexec/dbus-daemon-launch-helper

tar xf "$RIDSOURCES"/blfs-bootscripts-20240913.tar.xz

cd blfs-bootscripts-20240913
make install-dbus

}

rdir() {

echo not implemented

}
