#!/bin/bash
NAME="dejagnu"
VERS="1.6.3"
LINK="https://ftp.gnu.org/gnu/dejagnu/dejagnu-$VERS.tar.gz"
UPST="https://git.savannah.gnu.org/git/dejagnu.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n4 | head -n1 | cut -d- -f2"
DEPS=""


idir() {

mkdir -v build
cd       build

../configure --prefix=/usr
makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi

make install
install -v -dm755  /usr/share/doc/dejagnu-$VERS
install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-$VERS

}

rdir() {

rm -vf /usr/bin/{dejagnu,runtest}

}
