#!/bin/bash
NAME="desktop-file-utils"
VERS="0.28"
LINK="https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-$VERS.tar.xz"
UPST="https://freedesktop.org/software/desktop-file-utils/releases/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="glib"


IDIR=$(cat << '~fin.'

mn

install -vdm755 /usr/share/applications &&
update-desktop-database /usr/share/applications

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/desktop-file-{edit,install,validate} \
       /usr/bin/update-desktop-database

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
