#!/bin/bash
NAME="dhcpcd"
VERS="10.1.0"
LINK="https://github.com/NetworkConfiguration/dhcpcd/releases/download/v$VERS/dhcpcd-$VERS.tar.xz"
DOWN="https://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20240913.tar.xz"
UPST="https://github.com/NetworkConfiguration/dhcpcd.git"
DEPS=""


idir() {

export RIDBUILD=false
cm  --sysconfdir=/etc            \
    --libexecdir=/usr/lib/dhcpcd \
    --dbdir=/var/lib/dhcpcd      \
    --runstatedir=/run           \
    --disable-privsep
unset RIDBUILD

tar xvf "$RIDSOURCES"/blfs-bootscripts-20240913.tar*
cd blfs-bootscripts-20240913
make install-service-dhcpcd

}

rdir() {

echo not implemented

}
