#!/bin/bash
NAME="dhcpcd"
VERS=10.1.0
LINK="https://github.com/NetworkConfiguration/dhcpcd/releases/download/v$VERS/dhcpcd-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

export RIDBUILD=false
cm  --sysconfdir=/etc            \
    --libexecdir=/usr/lib/dhcpcd \
    --dbdir=/var/lib/dhcpcd      \
    --runstatedir=/run           \
    --disable-privsep
unset RIDBUILD

[ -e /etc/rid/sources/blfs-bootscripts-20240913.tar* ] || raw https://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20240913.tar.xz

tar xvf /etc/rid/sources/blfs-bootscripts-20240913.tar*
cd blfs-bootscripts-20240913
make install-service-dhcpcd

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
