#!/bin/bash
NAME="diffutils"
VERS="3.10"
LINK="https://ftp.gnu.org/gnu/diffutils/diffutils-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/diffutils/?C=M;O=D"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf  /usr/bin/cmp        \
        /usr/bin/diff{,3}   \
        /usr/bin/sdiff
        

    }
