#!/bin/bash
NAME="dosfstools"
VERS="4.2"
LINK="https://github.com/dosfstools/dosfstools/releases/download/v$VERS/dosfstools-$VERS.tar.gz"
UPST="https://github.com/dosfstools/dosfstools/tags"
DEPS=""


idir() {

cm \
    --enable-compat-symlinks \
    --mandir=/usr/share/man  \
    --docdir=/tmp/rid/trash

}

rdir() {

rm -vf  /bin/fatlabel   \
        /bin/fsck.fat   \
        /bin/mkfs.fat
        
    }
