#!/bin/bash
NAME="duktape"
VERS="2.7.0"
LINK="https://duktape.org/duktape-$VERS.tar.xz"
UPST="https://github.com/svaarala/duktape.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS=""


idir() {

sed -i 's/-Os/-O2/' Makefile.sharedlibrary
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr install

}

rdir() {

rm -vf /usr/lib/libduktape{,d}.so*

}
