#!/bin/bash
NAME="duktape"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://duktape.org/duktape-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i 's/-Os/-O2/' Makefile.sharedlibrary
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libduktape{,d}.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
