#!/bin/bash
NAME="duktape"
VERS="2.7.0"
LINK="https://duktape.org/duktape-$VERS.tar.xz"
UPST="https://duktape.org/download"
SELE=".latest > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i 's/-Os/-O2/' Makefile.sharedlibrary
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libduktape{,d}.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
