#!/bin/bash

NAME="e2fsprogs"
VERS=1.47.1
LINK="https://github.com/tytso/e2fsprogs/archive/refs/tags/v$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc    \
   --enable-elf-shlibs  \
   --disable-libblkid   \
   --disable-libuuid    \
   --disable-uuidd      \
   --disable-fsck       \
   --disable-fuse2fs

rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
gunzip -v /usr/share/info/libext2fs.info.gz
install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
