#!/bin/bash

NAME="e2fsprogs"
VERS=1.47.1
LINK="https://downloads.sourceforge.net/project/$NAME/$NAME/v$VERS/$NAME-$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<EOF

cm --sysconfdir=/etc    \
   --enable-elf-shlibs  \
   --disable-libblkid   \
   --disable-libuuid    \
   --disable-uuidd      \
   --disable-fsck

rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
gunzip -v /usr/share/info/libext2fs.info.gz
install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
