#!/bin/bash
NAME="efibootmgr"
VERS="18"
LINK="https://github.com/rhboot/efibootmgr/archive/$VERS/efibootmgr-$VERS.tar.gz"
UPST="https://github.com/rhboot/efibootmgr/tags"
DEPS="efivar popt"


idir() {

make EFIDIR=LFS EFI_LOADER=tox64.efi
make install EFIDIR=LFS

}

rdir() {

echo not implemented

}
