#!/bin/bash
NAME="efibootmgr"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/rhboot/efibootmgr/archive/$VERS/efibootmgr-$VERS.tar.gz"
DEPS="efivar popt"


IDIR=$(cat << '~fin.'

make EFIDIR=LFS EFI_LOADER=tox64.efi
make install EFIDIR=LFS

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
