#!/bin/bash
NAME="efivar"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/rhboot/efivar/archive/$VERS/efivar-$VERS.tar.gz"
DEPS="" # doc dep on mandoc


IDIR=$(cat << '~fin.'

make ENABLE_DOCS=0
make install ENABLE_DOCS=0 LIBDIR=/usr/lib

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
