#!/bin/bash
NAME="efivar"
VERS="39"
LINK="https://github.com/rhboot/efivar/archive/$VERS/efivar-$VERS.tar.gz"
UPST="https://github.com/rhboot/efivar.git"
DEPS="" # doc dep on mandoc


idir() {

make ENABLE_DOCS=0
make install ENABLE_DOCS=0 LIBDIR=/usr/lib

}

rdir() {

echo not implemented

}
