#!/bin/bash
NAME="elogind"
VERS=255.5
LINK="https://github.com/elogind/elogind/archive/v$VERS/elogind-$VERS.tar.gz"
DEPS="dbus1 linux-pam"


IDIR=$(cat <<'~fin.'

mn \
    -D docdir=/tmp/rid/trash        \
    -D cgroup-controller=elogind    \
    -D dev-kvm-mode=0660            \
    -D dbuspolicydir=/etc/dbus-1/system.d    

ln -sfv  libelogind.pc /usr/lib/pkgconfig/libsystemd.pc
ln -sfvn elogind /usr/include/systemd

32mn \
    -D cgroup-controller=elogind    \
    -D dev-kvm-mode=0660            \
    -D dbuspolicydir=/etc/dbus-1/system.d

ln -sfv  libelogind.pc /usr/lib32/pkgconfig/libsystemd.pc

sed -e '/\[Login\]/a KillUserProcesses=no' \
    -i /etc/elogind/logind.conf

cat >> /etc/pam.d/system-session << "EOF" &&
# Begin elogind addition

session  required    pam_loginuid.so
session  optional    pam_elogind.so

# End elogind addition
EOF
cat > /etc/pam.d/elogind-user << "EOF"
# Begin /etc/pam.d/elogind-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_unix.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_elogind.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/elogind-user
EOF

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
