#!/bin/bash
NAME="expat"
VERS="2.6.4"
LINK="https://prdownloads.sourceforge.net/expat/expat-$VERS.tar.xz"
UPST="https://sourceforge.net/projects/expat/files"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash
32cm

}

rdir() {

echo not implemented

}
