#!/bin/bash
NAME="expat"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://prdownloads.sourceforge.net/expat/expat-$VERS.tar.xz"
UPST="https://libexpat.github.io"
SELE="#page-content > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
