#!/bin/bash
NAME="expect"
VERS="5.45.4"
LINK="https://prdownloads.sourceforge.net/expect/expect$VERS.tar.gz"
UPST="https://sourceforge.net/projects/expect/files"
VCMD="curl -s https://sourceforge.net/projects/expect/files/Expect/ | rg 'tr title=' | head -n1 | cut -d'\"' -f2"
DEPS=""


idir() {

patch -Np1 -i "$RIDSOURCES"/expect-5.45.4-gcc14-1.patch

cm  \
    --with-tcl=/usr/lib     \
    --enable-shared         \
    --disable-rpath         \
    --mandir=/usr/share/man \
    --with-tclinclude=/usr/include

ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib

}

rdir() {

rm -vf  /usr/bin/expect  \
        /usr/lib/libexpect$VERS.so

    }
