#!/bin/bash
NAME="eza"
VERS="0.20.16"
LINK="https://github.com/eza-community/eza/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/eza-community/eza.git"
DEPS="rust"


idir() {

cargo build --release
install -v -Dm755 "target/release/eza" "/usr/bin/eza"

}

rdir() {

echo not implemented

}
