#!/bin/bash
NAME="eza"
VERS="0.20.8"
LINK="https://github.com/eza-community/eza/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/eza-community/eza/tags"
DEPS="rust"


IDIR=$(cat << '~fin.'

cargo build --release
install -v -Dm755 "target/release/eza" "/usr/bin/eza"

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
