#!/bin/bash
NAME="fdk-aac"
VERS="2.0.3"
LINK="https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-$VERS.tar.gz"
UPST="https://sourceforge.net/projects/opencore-amr/files"
DEPS=""


idir() {

cm

}

rdir() {

rm -rvf /usr/include/fdk-aac /usr/lib/libfdk-aac.*

}


