#!/bin/bash
NAME="fdk-aac"
VERS="${!NAME}_version"
LINK="https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/fdk-aac /usr/lib/libfdk-aac.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
