#!/bin/bash
NAME="feh"
VERS="3.10.3"
LINK="https://github.com/derf/feh/archive/refs/heads/master.tar.gz" # not sure why, but finalrewind's link doesn't work with rid; so im using github's
UPST="https://github.com/derf/feh.git"
DEPS="libpng imlib2 curl"


idir() {

sed -i "s:doc/feh:&-$VERS:" config.mk &&
make PREFIX=/usr         || die "Make failed"
make PREFIX=/usr install || die "Make install failed"

}

rdir() {

rm -rvf /usr/share/doc/feh-$VERS
rm -rvf /usr/share/feh
rm -vf /usr/bin/feh

}
