#!/bin/bash
NAME="ffmpeg"
VERS="7.1"
LINK="https://ffmpeg.org/releases/ffmpeg-$VERS.tar.xz"
DOWN="https://www.linuxfromscratch.org/patches/blfs/svn/ffmpeg-$VERS-chromium_method-1.patch"
UPST="https://ffmpeg.org//releases/?C=M;O=D"
SELE="body > pre:nth-child(2) > a:nth-child(14)"

cuda_deps="nv-codec-headers gcc13 cuda"
DEPS="libaom libass fdk-aac freetype2 lame libvorbis libvpx opus x264 x265 yasm alsa-lib libva sdl2 pulseaudio ${cuda_deps}"


IDIR=$(cat << '~fin.'

patch -Np1 -i "$RIDSOURCES"/ffmpeg-$VERS-chromium_method-1.patch

pathprepend /opt/gcc13/bin
cuda_config="--enable-cuda-nvcc       \
  --enable-nvenc                      \
  --enable-libnpp                     \
  --extra-cflags=-I/opt/cuda/include  \
  --extra-ldflags=-L/opt/cuda/lib64"

cm --enable-gpl                       \
   --enable-lto                       \
   --enable-version3                  \
   --enable-nonfree                   \
   --disable-static                   \
   --disable-rpath                    \
   --enable-shared                    \
   --disable-debug                    \
   --enable-libaom                    \
   --enable-libpulse                  \
   --enable-libass                    \
   --enable-libfdk-aac                \
   --enable-libfreetype               \
   --enable-libmp3lame                \
   --enable-libopus                   \
   --enable-libvorbis                 \
   --enable-libvpx                    \
   --enable-libx264                   \
   --enable-libx265                   \
   --enable-openssl                   \
   --disable-doc                      \
   --disable-large-tests              \
   --ignore-tests=enhanced-flv-av1    \
   ${cuda_config}

gcc tools/qt-faststart.c -o tools/qt-faststart
install -v -m755    tools/qt-faststart /usr/bin

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
