#!/bin/bash
NAME="ffmpeg"
VERS=7.1
LINK="https://ffmpeg.org/releases/ffmpeg-$VERS.tar.xz"
DEPS="libaom libass fdk-aac freetype2 lame libvorbis libvpx opus x264 x265 yasm alsa-lib libva sdl2 pulseaudio"


IDIR=$(cat << '~fin.'

raw https://www.linuxfromscratch.org/patches/blfs/svn/ffmpeg-$VERS-chromium_method-1.patch
patch -Np1 -i /etc/rid/sources/ffmpeg-$VERS-chromium_method-1.patch


cm --enable-gpl                       \
   --enable-version3                  \
   --enable-nonfree                   \
   --disable-static                   \
   --enable-shared                    \
   --disable-debug                    \
   --enable-libaom                    \
   --enable-libpulse                  \
   --enable-libass                    \
   --enable-libfdk-aac                \
   --enable-libfreetype               \
   --enable-libmp3lame                \
   --enable-libopus                   \
   --enable-libvorbis                 \
   --enable-libvpx                    \
   --enable-libx264                   \
   --enable-libx265                   \
   --enable-openssl                   \
   --disable-doc                      \
   --disable-large-tests              \
   --ignore-tests=enhanced-flv-av1

gcc tools/qt-faststart.c -o tools/qt-faststart
install -v -m755    tools/qt-faststart /usr/bin &&

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
