#!/bin/bash
NAME="fftw"
VERS="3.3.10"
LINK="http://fftw.org/fftw-$VERS.tar.gz"
UPST="http://fftw.org/download.html"
SELE="body > h2:nth-child(10)"
DEPS=""


idir() {

cm  \
  --enable-shared   \
  --enable-threads

}

rdir() {

echo "not implemented"

}
