#!/bin/bash
NAME="file"
VERS="5.45"
LINK="https://astron.com/pub/file/file-$VERS.tar.gz"
UPST="https://astron.com/pub/file/?C=M;O=D"
SELE="body > pre:nth-child(2) > a:nth-child(7)"
DEPS=""


idir() {

cm
32cm

}

rdir() {

rm -vf /usr/bin/file    \
    /usr/lib{,32}/libmagic.so*

}


