#!/bin/bash
NAME="file"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://astron.com/pub/file/file-$VERS.tar.gz"
UPST="https://astron.com/pub/file/?C=M;O=D"
SELE="body > pre:nth-child(2) > a:nth-child(7)"
DEPS=""


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/file    \
    /usr/lib{,32}/libmagic.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
