#!/bin/bash
NAME="findutils"
VERS="4.10.0"
LINK="https://ftp.gnu.org/gnu/findutils/findutils-$VERS.tar.xz"
UPST="https://git.savannah.gnu.org/git/findutils.git"
VCMD="git ls-remote --tags 'https://git.savannah.gnu.org/git/findutils.git' | sed 's:.*/::' | sort -V | tail -n1"
DEPS=""


idir() {

cm --localstatedir=/var/lib/locate

}

rdir() {

rm -vf  /usr/bin/find   \
        /usr/bin/locate \
        /usr/bin/xargs  \
        /usr/bin/updatedb

rm -rvf /var/lib/locate

}
