#!/bin/bash
NAME="findutils"
VERS="4.10.0"
LINK="https://ftp.gnu.org/gnu/findutils/findutils-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/findutils/?C=M;O=D"
DEPS=""


idir() {

cm --localstatedir=/var/lib/locate

}

rdir() {

rm -vf  /usr/bin/find   \
        /usr/bin/locate \
        /usr/bin/xargs  \
        /usr/bin/updatedb

rm -rvf /var/lib/locate

}
