#!/bin/bash
NAME="flac"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://downloads.xiph.org/releases/flac/flac-$VERS.tar.xz"
UPST="https://github.com/xiph/flac/releases/latest"
DEPS=""


IDIR=$(cat << '~fin.'

cm   --disable-thorough-tests \
     --docdir=/tmp/rid/trash

32cm --disable-thorough-tests

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/bin/{meta,}flac   \
        /usr/include/FLAC{,++} \
        /usr/lib{,32}/libFLAC* \
        /usr/share/doc/flac-$VERS

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
