#!/bin/bash
NAME="flac"
VERS="1.4.3"
LINK="https://downloads.xiph.org/releases/flac/flac-$VERS.tar.xz"
UPST="https://github.com/xiph/flac/releases/latest"
DEPS=""


idir() {

cm   --disable-thorough-tests \
     --docdir=/tmp/rid/trash

32cm --disable-thorough-tests

}

rdir() {

rm -rvf /usr/bin/{meta,}flac   \
        /usr/include/FLAC{,++} \
        /usr/lib{,32}/libFLAC* \
        /usr/share/doc/flac-$VERS

    }


