#!/bin/bash
NAME="flit-core"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://pypi.org/packages/source/f/flit-core/flit_core-$VERS.tar.gz"
DEPS="python"


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --find-links dist flit_core

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/python3.13/site-packages/flit_core*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
