#!/bin/bash
NAME="floorp"
VERS="11.23.0"
LINK="https://github.com/Floorp-Projects/Floorp/releases/download/v$VERS/floorp-$VERS.linux-x86_64.tar.bz2"
UPST="https://github.com/Floorp-Projects/Floorp.git"
DEPS="gtk3"  # floorp has a bunch of dependencies that i dont feel like finding rn


idir() {

rm -rf /usr/src/floorp-$VERS

cd ..
cp -rv floorp-$VERS /usr/src/
[ -L /usr/src/floorp ] && rm -vf /usr/src/floorp
ln -sfv floorp-$VERS /usr/src/floorp

cat << 'EOF' > /usr/bin/floorp.sh
#!/bin/bash

DEF="--force-device-scale-factor=1"

exec /usr/src/floorp/floorp "$DEF" "$@"
EOF

chmod +x /usr/bin/floorp.sh

}

rdir() {

echo not implemented

}
