#!/bin/bash
NAME="floorp"
VERS="${!NAME}_version"
LINK="https://github.com/Floorp-Projects/Floorp/releases/download/v$VERS/floorp-$VERS.linux-x86_64.tar.bz2"
DEPS="gtk+"  # floorp has a bunch of dependencies that i dont feel like finding rn


IDIR=$(cat << '~fin.'

rm -rf /usr/src/floorp-$VERS

cd ..
cp -rv floorp-$VERS /usr/src/
[ -L /usr/src/floorp ] && rm -vf /usr/src/floorp
ln -sfv /usr/src/floorp-$VERS /usr/src/floorp

cat << 'EOF' > /usr/bin/floorp.sh
#!/bin/bash

DEF="--force-device-scale-factor=1"

exec /usr/src/floorp/floorp "$DEF" "$@"
EOF

chmod +x /usr/bin/floorp.sh

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
