#!/bin/bash
NAME="fontconfig"
VERS="2.15.0"
LINK="https://www.freedesktop.org/software/fontconfig/release/fontconfig-$VERS.tar.xz"
UPST="https://www.freedesktop.org/software/fontconfig/release/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="freetype2"


idir() {

cm  --sysconfdir=/etc    \
    --localstatedir=/var \
    --disable-docs       \
    --docdir=/tmp/rid/trash

32cm    --sysconfdir=/etc    \
        --localstatedir=/var \
        --disable-docs

    }

    rdir() {

pushd /usr/bin
rm -vf \
    fc-cache    \
    fc-cat      \
    fc-conflist \
    fc-list     \
    fc-match    \
    fc-pattern  \
    fc-query    \
    fc-scan     \
    fc-validate
popd
rm -vf /usr/lib{,32}/libfontconfig.*
rm -rvf \
    /etc/fonts              \
    /usr/include/fontconfig \
    /usr/share/fontconfig   \
    /var/cache/fontconfig   \
    /usr/share/xml/fontconfig 

}


