#!/bin/bash
NAME="fontconfig"
VERS="2.16.0"
LINK="https://www.freedesktop.org/software/fontconfig/release/fontconfig-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B 1 'ah-20021030' | head -n1"
DEPS="freetype2"


idir() {

cm  --sysconfdir=/etc    \
    --localstatedir=/var \
    --disable-docs       \
    --docdir=/tmp/rid/trash

32cm    --sysconfdir=/etc    \
        --localstatedir=/var \
        --disable-docs

    }

    rdir() {

pushd /usr/bin
rm -vf \
    fc-cache    \
    fc-cat      \
    fc-conflist \
    fc-list     \
    fc-match    \
    fc-pattern  \
    fc-query    \
    fc-scan     \
    fc-validate
popd
rm -vf /usr/lib{,32}/libfontconfig.*
rm -rvf \
    /etc/fonts              \
    /usr/include/fontconfig \
    /usr/share/fontconfig   \
    /var/cache/fontconfig   \
    /usr/share/xml/fontconfig 

}
