#!/bin/bash
NAME="font-util"
VERS="1.4.1"
LINK="https://www.x.org/pub/individual/font/$NAME-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/font/util/-/tags"
DEPS="util-macros glibc"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
