#!/bin/bash
NAME="freetype2"
VERS="2.13.3"
UPST="https://sourceforge.net/projects/freetype/files"
DEPS="freetype1 harfbuzz"

idir() {

tar xvf "$RIDSOURCES"/freetype1-$VERS.tar &&
cd  freetype-$VERS                        ||
die "Failed to extract tarball"

cm   --enable-freetype-config
32cm --enable-freetype-config --with-brotli=no

}

rdir() {

rm -rvf 
    /usr/bin/freetype-config    \
    /usr/lib{,32}/libfreetype.* \
    /usr/include/freetype2

}
