#!/bin/bash
NAME="freetype1"
VERS="2.13.3"
LINK="https://downloads.sourceforge.net/project/freetype/freetype2/$VERS/freetype-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/freetype/freetype.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B 1 VER-2-BETA2 | head -n1 | cut -d- -f2- | sed 's/-/./g'"
DEPS="libpng which"

idir() {

sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h  &&

cm   --enable-freetype-config --with-harfbuzz=no
32cm --enable-freetype-config --with-harfbuzz=no --with-brotli=no

}

rdir() {

echo not implemented

}
