#!/bin/bash
NAME="freetype1"
VERS=2.13.3
LINK="https://downloads.sourceforge.net/project/freetype/freetype2/$VERS/freetype-$VERS.tar.xz"
DEPS="libpng which"

IDIR=$(cat <<EOF

sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h  &&

cm   --enable-freetype-config --with-harfbuzz=no
32cm --enable-freetype-config --with-harfbuzz=no --with-brotli=no

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
