#!/bin/bash
NAME="freetype1"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://downloads.sourceforge.net/project/freetype/freetype2/$VERS/freetype-$VERS.tar.xz"
UPST="https://sourceforge.net/projects/freetype/files"
DEPS="libpng which"

IDIR=$(cat << '~fin.'

sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h  &&

cm   --enable-freetype-config --with-harfbuzz=no
32cm --enable-freetype-config --with-harfbuzz=no --with-brotli=no

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
