#!/bin/bash
NAME="fribidi"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/fribidi/fribidi/releases/download/v$VERS/fribidi-$VERS.tar.xz"
UPST="https://github.com/fribidi/fribidi/tags"
DEPS=""


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf \
    /usr/lib/libfribidi.so* \
    /usr/include/fribidi    \
    /usr/bin/fribidi

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
