#!/bin/bash
NAME="fribidi"
VERS="1.0.16"
LINK="https://github.com/fribidi/fribidi/releases/download/v$VERS/fribidi-$VERS.tar.xz"
UPST="https://github.com/fribidi/fribidi/tags"
DEPS=""


idir() {

mn

}

rdir() {

rm -rvf \
    /usr/lib/libfribidi.so* \
    /usr/include/fribidi    \
    /usr/bin/fribidi

}


