#!/bin/bash
NAME="gdbm"
VERS="1.24"
LINK="https://ftp.gnu.org/gnu/gdbm/gdbm-$VERS.tar.gz"
UPST="https://git.savannah.gnu.org/git/gdbm.git"
DEPS=""


idir() {

cm --enable-libgdbm-compat
32cm --enable-libgdbm-compat

}

rdir() {

echo not implemented

}
