#!/bin/bash
NAME="gdbm"
VERS="1.24"
LINK="https://ftp.gnu.org/gnu/gdbm/gdbm-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/gdbm/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

cm --enable-libgdbm-compat
32cm --enable-libgdbm-compat

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
