#!/bin/bash
NAME="gdk-pixbuf"
VERS="2.42.12"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/gdk-pixbuf/$ver/gdk-pixbuf-$VERS.tar.xz"
UPST="https://github.com/GNOME/gdk-pixbuf.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B 1 2.90.0 | head -n1" # why does 2.90.x exist :sob:
DEPS="glib libjpeg-turbo libpng shared-mime-info"


idir() {

mn \
    -D others=enabled   \
    -D man=false        \
    --wrap-mode=nofallback

gdk-pixbuf-query-loaders --update-cache

}

rdir() {

rm -rvf \
    /usr/bin/gdk-pixbuf-*                   \
    /usr/lib/libgdk_pixbuf-2.0.so*          \
    /usr/include/gdk-pixbuf-2.0             \
    /usr/lib/gdk-pixbuf-2.0                 \
    /usr/libexec/installed-tests/gdk-pixbuf \
    /usr/share/installed-tests/gdk-pixbuf   \
    /usr/share/thumbnailers/gdk-pixbuf-thumbnailer.thumbnailer

}
