#!/bin/bash
NAME="gettext"
VERS="${!NAME}_version"
LINK="https://ftp.gnu.org/gnu/gettext/gettext-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
chmod -v 0755 /usr/lib/preloadable_libintl.so

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
