#!/bin/bash
NAME="gettext"
VERS="0.22.5"
LINK="https://ftp.gnu.org/gnu/gettext/gettext-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/gettext/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
chmod -v 0755 /usr/lib/preloadable_libintl.so

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
