#!/bin/bash
NAME="giflib"
VERS="5.2.2"
LINK="https://downloads.sourceforge.net/project/giflib/giflib-$VERS.tar.gz"
DOWN="https://www.linuxfromscratch.org/patches/blfs/svn/giflib-$VERS-upstream_fixes-1.patch"
UPST="https://git.code.sf.net/p/giflib/code.git"
VCMD="git ls-remote --tags 'https://git.code.sf.net/p/giflib/code.git' | sed 's:.*/::' | sort -V | grep -B 1 giflib-4_1_4 | head -n1"
DEPS="xmlto"


idir() {

patch -Np1 -i "$RIDSOURCES"/giflib-$VERS-upstream_fixes-1.patch
cp pic/gifgrid.gif doc/giflib-logo.gif
make
make PREFIX=/usr install

rm -fv /usr/lib/libgif.a

find doc \( -name Makefile\* -o -name \*.1 \
         -o -name \*.xml \) -exec rm -v {} \; &&

install -v -dm755 /usr/share/doc/giflib-$VERS &&
cp -v -R doc/* /usr/share/doc/giflib-$VERS

}

rdir() {

rm -rvf /bin/gif{2rgb,build,clrmp,fix,text,tool}    \
        /lib/libgif.so*                             \
        /usr/share/doc/giflib-$VERS
        
    }
