#!/bin/bash
NAME="git"
VERS="2.47.0"
LINK="https://www.kernel.org/pub/software/scm/git/git-$VERS.tar.xz"
UPST="https://github.com/git/git/tags"
DEPS="curl perl"


IDIR=$(cat << '~fin.'

./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3 &&
make  || die "Make failed"

PV=$(gv perl)
make perllibdir=/usr/lib/perl${PV%.*.*}/${PV%.*}/site_perl install || die "Make install failed"

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf ~/.gitconfig                                          \
         /etc/gitconfig                                       \
         /usr/bin/git{,k}                                     \
         /usr/bin/git-{shell,receive-pack,cvsserver}          \
         /usr/bin/git-upload-{archive,pack}                   \
         /usr/bin/scalar             

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
