#!/bin/bash
NAME="git"
VERS="2.48.1"
LINK="https://www.kernel.org/pub/software/scm/git/git-$VERS.tar.xz"
UPST="https://github.com/git/git.git"
DOWN="https://www.kernel.org/pub/software/scm/git/git-manpages-$VERS.tar.xz"
DEPS="curl perl"


idir() {

./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3 &&
make  || die "Make failed"

PV=$(gv perl)
make perllibdir=/usr/lib/perl${PV%.*.*}/${PV%.*}/site_perl install || die "Make install failed"

tar -xvf "$RIDSOURCES"/git-manpages-$VERS.tar.xz \
    -C /usr/share/man --no-same-owner --no-overwrite-dir

}

rdir() {

rm -rvf ~/.gitconfig                                          \
         /etc/gitconfig                                       \
         /usr/bin/git{,k}                                     \
         /usr/bin/git-{shell,receive-pack,cvsserver}          \
         /usr/bin/git-upload-{archive,pack}                   \
         /usr/bin/scalar             

     }
