#!/bin/bash
NAME="glad"
VERS="2.0.8"
LINK="https://github.com/Dav1dde/glad/archive/v$VERS/glad-$VERS.tar.gz"
UPST="https://github.com/Dav1dde/glad/tags"
DEPS=""


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
pip3 install --no-index --find-links=dist --no-cache-dir --no-user glad2

~fin.
)

RDIR=$(cat << '~fin.'

PV=$(gv python)
PV=${PV%.*}

rm -rvf /usr/lib/python$PV/site-packages/glad{,2-$VERS.dist-info}
rm -vf /usr/bin/glad

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
