#!/bin/bash
NAME="glib-no-gobject"
VERS=2.82.1
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/glib/$ver/glib-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi

mn \
    -D introspection=disabled \
    -D glib_debug=disabled    \
    -D man-pages=disabled     \
    -D sysprof=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
