#!/bin/bash
NAME="glib"
VERS=2.82.2
ver="${VERS%.*}"
gobjver=1.82.0
gobjv="${gobjver%.*}"
LINK="https://download.gnome.org/sources/glib/$ver/glib-$VERS.tar.xz"
DEPS="libxslt pcre2 glib-no-gobject"


IDIR=$(cat << '~fin.'

raw https://download.gnome.org/sources/gobject-introspection/$gobjv/gobject-introspection-$gobjver.tar.xz

if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi

mn \
    -D introspection=disabled \
    -D glib_debug=disabled    \
    -D man-pages=enabled      \
    -D sysprof=disabled

rm -rf ridbuild

tar xf /etc/rid/sources/gobject-introspection-$gobjver.tar.xz &&
meson setup gobject-introspection-$gobjver gi-build \
            --prefix=/usr --buildtype=release --strip &&
ninja -C gi-build
ninja -C gi-build install

mn \
    -D introspection=enabled  \
    -D glib_debug=disabled    \
    -D man-pages=enabled      \
    -D sysprof=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
