#!/bin/bash
NAME="glib"
VERS="2.82.2"
ver="${VERS%.*}"
gobjver=1.82.0
gobjv="${gobjver%.*}"
LINK="https://download.gnome.org/sources/glib/$ver/glib-$VERS.tar.xz"
DOWN="https://download.gnome.org/sources/gobject-introspection/$gobjv/gobject-introspection-$gobjver.tar.xz"
UPST="https://repology.org/project/glib/information"
DEPS="meson-toolchain-files pcre2"


idir() {

if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi

mkdir build && cd build
meson setup ..                  \
      --prefix=/usr             \
      --buildtype=release       \
      --strip                   \
      -D introspection=disabled \
      -D glib_debug=disabled    \
      -D man-pages=disabled     \
      -D tests=false            \
      -D sysprof=disabled   || die "Meson setup failed"

ninja                       || die "Ninja failed"
ninja install               || die "Ninja install failed"

tar xf "$RIDSOURCES"/gobject-introspection-$gobjver.tar.xz

meson setup gobject-introspection-$gobjver gi-build \
            --prefix=/usr --buildtype=release --strip &&
ninja -C gi-build
ninja -C gi-build install

meson configure -D introspection=enabled &&
ninja
ninja install

rm -rf *

meson setup ..                              \
    --cross-file lib32                      \
    --prefix=/usr                           \
    --libdir=/usr/lib32                     \
    --buildtype=release                     \
    -D introspection=disabled               \
    -D glib_debug=disabled                  \
    -D man-pages=disabled                   \
    -D tests=false                          \
    -D sysprof=disabled                     ||
die "32-bit meson setup failed"

ninja                                       ||
die "32-bit ninja failed"

DESTDIR=/tmp/rid/dest ninja install         ||
die "32-bit ninja install failed"
cp -vr /tmp/rid/dest/usr/lib32/* /usr/lib32 ||
die "Failed to copy 32-bit libraries"
rm -rf /tmp/rid/dest
ldconfig                                    ||
die "Failed to update library cache"

}

rdir() {

echo not implemented

}


