#!/bin/bash
NAME="glib-no-gobject"
VERS=2.82.1
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/glib/$ver/glib-$VERS.tar.xz"
DEPS=""


IDIR=$(cat <<EOF

if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi

mn \
    -D introspection=disabled \
    -D glib_debug=disabled    \
    -D man-pages=disabled     \
    -D sysprof=disabled

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
