#!/bin/bash
NAME="glslang"
VERS="15.0.0"
LINK="https://github.com/KhronosGroup/glslang/archive/$VERS/glslang-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/glslang/releases/latest"
DEPS="cmake spirv_tools"


IDIR=$(cat << '~fin.'
CN \
  -D ALLOW_EXTERNAL_SPIRV_TOOLS=ON \
  -D GLSLANG_TESTS=OFF

32CN \
  -D ALLOW_EXTERNAL_SPIRV_TOOLS=ON \
  -D GLSLANG_TESTS=OFF

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
