#!/bin/bash
NAME="gnutls"
VERS="3.8.8"
LINK="https://www.gnupg.org/ftp/gcrypt/gnutls/v${VERS:0:3}/gnutls-$VERS.tar.xz"
UPST="https://repology.org/project/gnutls/information"
DEPS="nettle make-ca libunistring libtasn1 p11-kit"


idir() {

cm --docdir=/tmp/rid/trash \
   --with-default-trust-store-pkcs11="pkcs11:"

}

rdir() {

echo not implemented

}


