#!/bin/bash
NAME="gnutls"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.gnupg.org/ftp/gcrypt/gnutls/v${VERS:0:3}/gnutls-$VERS.tar.xz"
UPST="https://repology.org/project/gnutls/information"
DEPS="nettle make_ca libunistring libtasn1 p11_kit"


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash \
   --with-default-trust-store-pkcs11="pkcs11:"

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
