#!/bin/bash
NAME="gperf"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/gperf/gperf-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/gperf

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
