#!/bin/bash
NAME="gperf"
VERS="3.1"
LINK="https://ftp.gnu.org/gnu/gperf/gperf-$VERS.tar.gz"
UPST="https://git.savannah.gnu.org/git/gperf.git"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash

}

rdir() {

rm -vf /usr/bin/gperf

}
