#!/bin/bash
NAME="grep"
VERS="3.11"
LINK="https://ftp.gnu.org/gnu/grep/grep-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/grep/?C=M;O=D"
DEPS=""


idir() {

sed -i "s/echo/#echo/" src/egrep.sh
cm

}

rdir() {

echo not implemented

}
