#!/bin/bash
NAME="grep"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/grep/grep-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i "s/echo/#echo/" src/egrep.sh
cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
