#!/bin/bash
NAME="groff"
VERS=1.23.0
LINK="https://ftp.gnu.org/gnu/groff/groff-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

export PAGE="letter"
cm
unset PAGE

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
