#!/bin/bash
NAME="groff"
VERS="1.23.0"
LINK="https://ftp.gnu.org/gnu/groff/groff-$VERS.tar.gz"
UPST="https://git.savannah.gnu.org/git/groff.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 FDL | head -n1"
DEPS=""


idir() {

export PAGE="letter"
cm
unset PAGE

}

rdir() {

echo not implemented

}
