#!/bin/bash
NAME="gsettings_desktop_schemas"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://download.gnome.org/sources/gsettings-desktop-schemas/${VERS%.*}/gsettings-desktop-schemas-$VERS.tar.xz"
UPST="https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/tags" # may be problematic
DEPS="glib"


IDIR=$(cat << '~fin.'

sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
mn
glib-compile-schemas /usr/share/glib-2.0/schemas

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/gsettings-desktop-schemas  \
        /usr/share/GConf/gsettings

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
