#!/bin/bash
NAME="gsettings-desktop-schemas"
VERS="47.1"
LINK="https://download.gnome.org/sources/gsettings-desktop-schemas/${VERS%.*}/gsettings-desktop-schemas-$VERS.tar.xz"
UPST="https://repology.org/project/gsettings-desktop-schemas/information"
DEPS="glib"


idir() {

sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
mn
glib-compile-schemas /usr/share/glib-2.0/schemas

}

rdir() {

rm -rvf /usr/include/gsettings-desktop-schemas  \
        /usr/share/GConf/gsettings

    }
