#!/bin/bash
NAME="gtk3"
VERS="3.24.43"
LINK="https://download.gnome.org/sources/gtk+/${VERS%.*}/gtk+-$VERS.tar.xz"
# upstream must be (rarely) manually updated
UPST="https://download.gnome.org/sources/gtk+/3.24/?C=M&O=D"
SELE="#list > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(1) > a:nth-child(1)"
DEPS="at_spi2_core gdk_pixbuf libepoxy pango"


IDIR=$(cat << '~fin.'

mn \
    -D man=false                \
    -D broadway_backend=true    \
    -D gtk_doc=false

gtk-query-immodules-3.0 --update-cache
glib-compile-schemas /usr/share/glib-2.0/schemas

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
