#!/bin/bash
NAME="gtk3"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://download.gnome.org/sources/gtk+/${VERS%.*}/gtk+-$VERS.tar.xz"
DEPS="at-spi2-core gdk-pixbuf libepoxy pango"


IDIR=$(cat << '~fin.'

mn \
    -D man=false                \
    -D broadway_backend=true    \
    -D gtk_doc=false

gtk-query-immodules-3.0 --update-cache
glib-compile-schemas /usr/share/glib-2.0/schemas

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
