#!/bin/bash
NAME="gtk3"
VERS="3.24.43"
LINK="https://download.gnome.org/sources/gtk+/${VERS%.*}/gtk+-$VERS.tar.xz"
# ive yet to find a functional upstream + selector combination because gnome enjoys making my life difficult
DEPS="at-spi2-core gdk-pixbuf libepoxy pango"


idir() {

mn \
    -D man=false                \
    -D broadway_backend=true    \
    -D gtk_doc=false

gtk-query-immodules-3.0 --update-cache
glib-compile-schemas /usr/share/glib-2.0/schemas

}

rdir() {

echo not implemented

}
