#!/bin/bash
NAME="gzip"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/gzip/gzip-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/gzip/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
