#!/bin/bash
NAME="harfbuzz"
VERS=10.0.1
LINK="https://github.com/harfbuzz/harfbuzz/releases/download/$VERS/harfbuzz-$VERS.tar.xz"
DEPS="freetype1"


IDIR=$(cat << '~fin.'

mn   -D graphite2=disabled
32mn -D graphite2=disabled \
     -D glib=disabled      \
     -D cairo=disabled     \
     -D gobject=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
