#!/bin/bash
NAME="harfbuzz"
VERS="10.2.0"
LINK="https://github.com/harfbuzz/harfbuzz/releases/download/$VERS/harfbuzz-$VERS.tar.xz"
UPST="https://github.com/harfbuzz/harfbuzz.git"
DEPS="freetype1"


idir() {

mn   -D graphite2=disabled
32mn -D graphite2=disabled \
     -D glib=disabled      \
     -D cairo=disabled     \
     -D gobject=disabled

 }

 rdir() {

echo not implemented

}
