#!/bin/bash
NAME="help2man"
VERS="1.49.3"
LINK="https://ftp.gnu.org/gnu/help2man/help2man-$VERS.tar.xz"
DEPS="perl gettext"


idir() {

cm  \
  --mandir=/usr/share/man   \
  --infodir=/usr/share/info \
  --libdir=/usr/lib

}

rdir() {

echo "not implemented"

}
