#!/bin/bash
NAME="hwdata"
VERS="0.389"
LINK="https://github.com/vcrhonek/$NAME/archive/v$VERS/$NAME-$VERS.tar.gz"
UPST="https://github.com/vcrhonek/$NAME/tags"
DEPS=""

# cant use cm because no make
idir() {

./configure --prefix=/usr --disable-blacklist
make install

}

rdir() {

rm -rvf /usr/share/hwdata

}
