#!/bin/bash
NAME="iana-etc"
VERS="20241122"
LINK="https://github.com/Mic92/iana-etc/releases/download/$VERS/iana-etc-$VERS.tar.gz"
UPST="https://github.com/Mic92/iana-etc/tags"
DEPS=""


idir() {

cp services protocols /etc

}

rdir() {

rm -vf /etc/{protocols,services}

}
