#!/bin/bash
NAME="iana-etc"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/Mic92/iana-etc/releases/download/$VERS/iana-etc-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cp services protocols /etc

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /etc/{protocols,services}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
