#!/bin/bash
NAME="icu"
VERS=75.1
ver1="${VERS//./-}"
ver2="${VERS//./_}"
LINK="https://github.com/unicode-org/icu/releases/download/release-$ver1/icu4c-$ver2-src.tgz"


IDIR=$(cat << '~fin.'

cd source                                    &&

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
