#!/bin/bash
NAME="icu"
VERS="${NAME}_version"; VERS="${!VERS}"
ver1="${VERS//./-}"
ver2="${VERS//./_}"
LINK="https://github.com/unicode-org/icu/releases/download/release-$ver1/icu4c-$ver2-src.tgz"
UPST="https://github.com/unicode-org/icu/releases/latest"
SELE="h1.d-inline"
DEPS=""


IDIR=$(cat << '~fin.'

cd source &&

./configure --prefix=/usr &&
make &&
make install

make clean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr --libdir=/usr/lib32 --host=i686-pc-linux-gnu &&
make
make DESTDIR=$PWD/DESTDIR install     &&
cp -Rv DESTDIR/usr/lib32/* /usr/lib32 &&
rm -rf DESTDIR                        &&
ldconfig

# TODO: Add error handling or make it build with abstractions

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
