#!/bin/bash
NAME="imagemagick"
VERS="7.1.1.41" # upstream uses x.x.x-x, but using . is easier for me
ver="${VERS%.*}-${VERS##*.}"
LINK="https://github.com/ImageMagick/ImageMagick/archive/refs/tags/$ver.tar.gz"
UPST="https://github.com/ImageMagick/ImageMagick.git"
DEPS="cairo fontconfig freetype2 glib lcms2 libpng libxext librsvg libtiff libwebp libjpeg-turbo pango"


idir() {

cm \
  --sysconfdir=/etc   \
  --enable-shared     \
  --enable-hdri       \
  --with-rsvg         \
  --with-webp         \
  --without-gslib     \
  --without-autotrace \
  --without-dps       \
  --without-fpx       \
  --without-gcc-arch  \
  --without-gvc       \
  --with-perl         \
  --with-modules      

rm -vf /etc/ImageMagick-${VERS%.*.*}/type-{apple,dejavu,windows,ghostscript,urw-base35}.xml

}

rdir() {

echo not implemented

}
