#!/bin/bash
NAME="imlib2"
VERS="1.12.3"
LINK="https://downloads.sourceforge.net/project/enlightenment/imlib2-src/$VERS/imlib2-$VERS.tar.xz"
UPST="https://git.enlightenment.org/old/legacy-imlib2.git" # this upstream looks old but it has the latest version :shrug:
DEPS="giflib librsvg freetype2 libjpeg-turbo libpng libtiff libxext librsvg libwebp"


idir() {

cm

}

rdir() {

rm -vf  /usr/bin/imlib2_*           \
        /usr/lib/libImlib2.*

rm -rvf /usr/{lib,share}/imlib2     \
        /usr/share/doc/imlib2-$VERS

    }
