#!/bin/bash
NAME="imlib2"
VERS="1.12.3"
LINK="https://downloads.sourceforge.net/project/enlightenment/imlib2-src/$VERS/imlib2-$VERS.tar.xz"
UPST="https://sourceforge.net/projects/enlightenment/files/imlib2-src"
SELE="tr.folder:nth-child(1) > th:nth-child(1) > a:nth-child(1) > span:nth-child(2)"
DEPS="giflib librsvg freetype2 libjpeg-turbo libpng libtiff libxext librsvg libwebp"


idir() {

cm

}

rdir() {

rm -vf  /usr/bin/imlib2_*           \
        /usr/lib/libImlib2.*

rm -rvf /usr/{lib,share}/imlib2     \
        /usr/share/doc/imlib2-$VERS

    }


