#!/bin/bash
NAME="intltool"
VERS="0.51.0"
LINK="https://launchpad.net/intltool/trunk/$VERS/+download/intltool-$VERS.tar.gz"
UPST="https://salsa.debian.org/gnome-team/intltool.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS=""


idir() {

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
cm

}

rdir() {

rm -rvf /usr/share/intltool
rm -vf /usr/bin/intltool{,ize,-update,-prepare,-merge,-extract}

}
