#!/bin/bash
NAME="intltool"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://launchpad.net/intltool/trunk/$VERS/+download/intltool-$VERS.tar.gz"
UPST="https://launchpad.net/intltool/trunk"
SELE="#downloads > ul:nth-child(3) > li:nth-child(1) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/intltool
rm -vf /usr/bin/intltool{,ize,-update,-prepare,-merge,-extract}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
