#!/bin/bash
NAME="intltool"
VERS="0.51.0"
LINK="https://launchpad.net/intltool/trunk/$VERS/+download/intltool-$VERS.tar.gz"
UPST="https://launchpad.net/intltool/trunk"
SELE="#downloads > ul:nth-child(3) > li:nth-child(1) > a:nth-child(1)"
DEPS=""


idir() {

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
cm

}

rdir() {

rm -rvf /usr/share/intltool
rm -vf /usr/bin/intltool{,ize,-update,-prepare,-merge,-extract}

}
