#!/bin/bash
NAME="iosevka"
VERS="3.2.1"
UPST="https://github.com/ryanoasis/nerd-fonts/releases/latest"
DOWN="https://github.com/ryanoasis/nerd-fonts/releases/download/v$VERS/Iosevka.tar.xz"


idir() {

mo "$RIDSOURCES"/Iosevka.tar.xz "$RIDSOURCES"/$NAME-$VERS.tar
mkdir -pv /usr/share/fonts/iosevka

tar xvf "$RIDSOURCES"/$NAME-$VERS.tar -C /usr/share/fonts/$NAME

}
