#!/bin/bash
NAME="iosevka"
VERS="3.2.1"
LINK=""
DOWN="https://github.com/ryanoasis/nerd-fonts/releases/download/v$VERS/Iosevka.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

mo "$RIDSOURCES"/Iosevka.tar.xz "$RIDSOURCES"/$NAME-$VERS.tar
mkdir -pv /usr/share/fonts/iosevka

tar xvf "$RIDSOURCES"/$NAME-$VERS.tar -C /usr/share/fonts/$NAME

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/fonts/iosevka

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
