#!/bin/bash
NAME="iproute2"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$VERS.tar.xz"
UPST="https://github.com/iproute2/iproute2/tags"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

make NETNS_RUN_DIR=/run/netns
make SBINDIR=/usr/sbin install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
