#!/bin/bash
NAME="iproute2"
VERS="6.12.0"
LINK="https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$VERS.tar.xz"
UPST="https://github.com/iproute2/iproute2/tags"
DEPS=""


idir() {

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

make NETNS_RUN_DIR=/run/netns
make SBINDIR=/usr/sbin install

}

rdir() {

echo not implemented

}
