#!/bin/bash
NAME="jansson"
VERS="2.14"
LINK="https://github.com/akheron/jansson/releases/download/v$VERS/jansson-$VERS.tar.bz2"
UPST="https://github.com/akheron/jansson.git"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /usr/lib/libjansson.so*

}
