#!/bin/bash
NAME="jinja2"
VERS="3.1.4"
LINK="https://pypi.org/packages/source/J/Jinja2/jinja2-$VERS.tar.gz"
UPST="https://github.com/pallets/jinja/releases/latest"
DEPS=""


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --find-links dist Jinja2

~fin.
)

RDIR=$(cat << '~fin.'

PV=$(gv python)
PV=${PV%.*}

rm -rvf /usr/lib/python$PV/site-packages/Jinja2-$VERS.dist-info

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
