#!/bin/bash
NAME="jinja2"
VERS="${!NAME}_version"
LINK="https://pypi.org/packages/source/J/Jinja2/jinja2-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --find-links dist Jinja2

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/python3.13/site-packages/Jinja2-$VERS.dist-info

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
