#!/bin/bash
NAME="kbd"
VERS="2.6.4"
LINK="https://www.kernel.org/pub/linux/utils/kbd/kbd-$VERS.tar.xz"
DOWN="https://www.linuxfromscratch.org/patches/lfs/development/kbd-$VERS-backspace-1.patch"
UPST="https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git"
DEPS=""


idir() {

patch -Np1 -i "$RIDSOURCES"/kbd-$VERS-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

cm --disable-vlock

}

rdir() {

echo not implemented

}
