#!/bin/bash
NAME="kbd"
VERS="2.6.4"
LINK="https://www.kernel.org/pub/linux/utils/kbd/kbd-$VERS.tar.xz"
DOWN="https://www.linuxfromscratch.org/patches/lfs/development/kbd-$VERS-backspace-1.patch"
UPST="https://repology.org/project/kbd/information"
DEPS=""


IDIR=$(cat << '~fin.'

patch -Np1 -i "$RIDSOURCES"/kbd-$VERS-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

cm --disable-vlock

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
