#!/bin/bash
NAME="kernel"
VERS=6.11.5
# ver="${VERS//\.0/}"
LINK="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

mkdir -pv      /usr/src/linux-$VERS
cd ..
mo kernel-$VERS /usr/src/linux-$VERS

[ -e /usr/src/linux/.config ] &&
cp /usr/src/linux/.config /usr/src/linux-$VERS/.config

rm -rf    /usr/src/linux
ln -sfv   /usr/src/linux-$VERS /usr/src/linux
cd        /usr/src/linux

if [ ! -e .config ]; then
    if [ -e "$RIDHOME/defaults/kernelconfig" ]; then
        cp -vf "$RIDHOME/defaults/kernelconfig" .config
    else
        raw https://raw.githubusercontent.com/Toxikuu/rid/refs/heads/master/defaults/kernelconfig &&
        cp -vf "$RIDSOURCES"/kernelconfig .config
    fi
fi

make olddefconfig
make && make modules_install

cp -vf arch/x86/boot/bzImage /boot/vmlinuz-$VERS-tox
cp -vf /boot/vmlinuz-$VERS-tox /efi/EFI/TOX/tox64.efi
cp -vf System.map /boot/System.map-$VERS
cp -vf .config /boot/config-$VERS

cp -rf Documentation -T /usr/share/doc/linux-$VERS

install -v -m755 -d /etc/modprobe.d

cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
