#!/bin/bash
NAME="kernel"
VERS="6.12.5"
LINK="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$VERS.tar.gz"
DOWN="https://raw.githubusercontent.com/Toxikuu/rid/refs/heads/master/defaults/kernelconfig"
UPST="https://kernel.org/" # i'd use the git repo, but it doesn't tag patches
VCMD="curl -s 'https://kernel.org/' | grep linux- | head -n1 | cut -d'>' -f2 | cut -d'<' -f1"
NEWS='You can edit your kernel config at /usr/src/linux/.config and run `rid -fu kernel` to use the new config. NVIDIA drivers must be rebuilt after the kernel sources are changed. Rid does not provide removal instructions for the kernel.'
DEPS=""


idir() {

[ -e /usr/src/linux/.config ] &&
cp /usr/src/linux/.config $RIDSOURCES/kernelconfig

[ -e /usr/src/linux-$VERS ] ||
{
mkdir -pv      /usr/src/linux-$VERS
cd ..
mo kernel-$VERS /usr/src/linux-$VERS
}

rm -rvf   /usr/src/linux
ln -sfv   linux-$VERS /usr/src/linux
cd        /usr/src/linux

if [ ! -e .config ]; then
    cp -vf "$RIDSOURCES/kernelconfig" .config
fi

make olddefconfig
make && make modules_install

mkdir -pv /efi/EFI/TOX

cp -vf arch/x86/boot/bzImage /boot/vmlinuz-$VERS-tox
cp -vf /boot/vmlinuz-$VERS-tox /efi/EFI/TOX/tox64.efi
cp -vf System.map /boot/System.map-$VERS
cp -vf .config /boot/config-$VERS

cp -rf Documentation -T /usr/share/doc/linux-$VERS

install -v -m755 -d /etc/modprobe.d

cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF

}

rdir() {

echo "Remove the kernel manually (in /usr/src/) or replace this with your own instructions." >&2

}
