#!/bin/bash
NAME="krb5"
VERS="1.21.3"
LINK="https://kerberos.org/dist/krb5/${VERS%.*}/krb5-$VERS.tar.gz"
UPST="https://web.mit.edu/kerberos/"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > ul:nth-child(1) > li:nth-child(3) > ul:nth-child(1) > li:nth-child(1) > a:nth-child(1)"
DEPS=""


idir() {

cd src &&
sed -i -e '/eq 0/{N;s/12 //}' plugins/kdb/db2/libdb2/test/run.test &&

cm  \
    --sysconfdir=/etc        \
    --localstatedir=/var/lib \
    --runstatedir=/run       \
    --with-system-et         \
    --with-system-ss         \
    --with-system-verto=no   \
    --enable-dns-for-realm   \
    --disable-rpath

}

rdir() {

echo not implemented

}


