#!/bin/bash
NAME="krb5"
VERS="1.21.3"
LINK="https://kerberos.org/dist/krb5/${VERS%.*}/krb5-$VERS.tar.gz"
UPST="https://github.com/krb5/krb5.git"
VCMD="git ls-remote --tags 'https://github.com/krb5/krb5.git' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS=""


idir() {

cd src &&
sed -i -e '/eq 0/{N;s/12 //}' plugins/kdb/db2/libdb2/test/run.test &&

cm  \
    --sysconfdir=/etc        \
    --localstatedir=/var/lib \
    --runstatedir=/run       \
    --with-system-et         \
    --with-system-ss         \
    --with-system-verto=no   \
    --enable-dns-for-realm   \
    --disable-rpath

}

rdir() {

echo not implemented

}
