#!/bin/bash
NAME="lcms2"
VERS="2.16"
LINK="https://github.com/mm2/Little-CMS/releases/download/lcms$VERS/lcms2-$VERS.tar.gz"
UPST="https://github.com/mm2/Little-CMS/releases/latest"
SELE="h1.d-inline" # lcms2 is a special case
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /bin/{jpg,link,ps,tif,trans}icc
rm -vf /usr/lib/liblcms2.{la,so*}

}


