#!/bin/bash
NAME="lcms2"
VERS="2.16"
LINK="https://github.com/mm2/Little-CMS/releases/download/lcms$VERS/lcms2-$VERS.tar.gz"
UPST="https://github.com/mm2/Little-CMS.git"
VCMD="git ls-remote --tags 'https://github.com/mm2/Little-CMS.git' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | sed 's/lcms//'" # this is likely to break with new release candidates
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /bin/{jpg,link,ps,tif,trans}icc
rm -vf /usr/lib/liblcms2.{la,so*}

}
