#!/bin/bash
NAME="less"
VERS=668
LINK="https://www.greenwoodsoftware.com/less/less-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/less{,echo,key}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
