#!/bin/bash
NAME="less"
VERS="669"
LINK="https://github.com/gwsw/less/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/gwsw/less/tags"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/less{,echo,key}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
