#!/bin/bash
NAME="less"
VERS="671"
LINK="https://github.com/gwsw/less/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/gwsw/less.git"
DEPS=""


idir() {

make -f Makefile.aut distfiles
autoreconf -fiv
cm --sysconfdir=/etc

}

rdir() {

rm -vf /usr/bin/less{,echo,key}

}
