#!/bin/bash
NAME="lfs-bootscripts"
VERS="20240825"
LINK="https://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-$VERS.tar.xz"
UPST="https://www.linuxfromscratch.org/lfs/downloads/development"
SELE="body > ul:nth-child(2) > li:nth-child(5) > a:nth-child(1)"
DEPS=""


idir() {

make install

}

rdir() {

echo not implemented

}
