#!/bin/bash
NAME="lfs-bootscripts"
VERS="20240825"
LINK="https://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-$VERS.tar.xz"
UPST="https://www.linuxfromscratch.org/~thomas/multilib-m32/chapter09/bootscripts.html"
VCMD="curl -s 'https://www.linuxfromscratch.org/~thomas/multilib-m32/chapter09/bootscripts.html' | grep LFS-Bootscripts- | tail -n1 | cut -d- -f3"
DEPS=""


idir() {

make install

}

rdir() {

echo not implemented

}
