#!/bin/bash
NAME="lfs_bootscripts"
VERS="20240825"
LINK="https://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-$VERS.tar.xz"
UPST="https://www.linuxfromscratch.org/lfs/downloads/development"
SELE="body > ul:nth-child(2) > li:nth-child(5) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

make install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
