#!/bin/bash
NAME="libaom"
VERS="3.11.0"
LINK="https://storage.googleapis.com/aom-releases/libaom-$VERS.tar.gz"
UPST="https://repology.org/project/aom/information"
DEPS="yasm"


idir() {

CN                  \
  -D ENABLE_DOCS=no \
  -D BUILD_SHARED_LIBS=1

rm -vf /usr/lib/libaom.a

}

rdir() {

rm -rvf /usr/include/aom /usr/lib/libaom.so*

}
