#!/bin/bash
NAME="libass"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/libass/libass/releases/download/$VERS/libass-$VERS.tar.xz"
DEPS="freetype2 fribidi nasm fontconfig"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/ass /usr/lib/libass.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
