#!/bin/bash
NAME="libaom"
VERS="3.11.0"
LINK="https://storage.googleapis.com/aom-releases/libaom-$VERS.tar.gz"
UPST="https://aomedia.googlesource.com/aom.git"
VCMD="git ls-remote --tags 'https://aomedia.googlesource.com/aom.git' | sed 's:.*/::' | sort -V | tail -n1"
DEPS="yasm"


idir() {

CN                  \
  -D ENABLE_DOCS=no \
  -D BUILD_SHARED_LIBS=1

rm -vf /usr/lib/libaom.a

}

rdir() {

rm -rvf /usr/include/aom /usr/lib/libaom.so*

}
