#!/bin/bash
NAME="libass"
VERS="0.17.3"
LINK="https://github.com/libass/libass/releases/download/$VERS/libass-$VERS.tar.xz"
UPST="https://github.com/libass/libass/tags"
DEPS="freetype2 fribidi nasm fontconfig"


idir() {

cm

}

rdir() {

rm -rvf /usr/include/ass /usr/lib/libass.so*

}
