#!/bin/bash
NAME="libarchive"
VERS="3.7.7"
LINK="https://github.com/$NAME/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
UPST="https://github.com/$NAME/$NAME/tags"
DEPS=""


idir() {

cm

}

rdir() {

echo not implemented

}
