#!/bin/bash
NAME="libarchive"
VERS=3.7.7
LINK="https://github.com/$NAME/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
DEPS=""


IDIR=$(cat <<EOF

cm

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
