#!/bin/bash
NAME="libclc"
VERS="19.1.3"
LINK="https://github.com/llvm/llvm-project/releases/download/llvmorg-$VERS/libclc-$VERS.src.tar.xz"
UPST="https://github.com/llvm/llvm-project/releases/latest"
SELE="h1.d-inline"
DEPS="llvm spirv-llvm-translator"  # llvm with clang


idir() {

CN

}

rdir() {

rm -rvf /usr/{share,include}/clc

}
