#!/bin/bash
NAME="libconfig"
VERS="1.7.3"
LINK="https://github.com/hyperrealm/libconfig/releases/download/v$VERS/libconfig-$VERS.tar.gz"
UPST="https://github.com/hyperrealm/libconfig.git"
DEPS=""


idir() {

autoreconf -fiv
./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O2,--as-needed\0/g' libtool
make
make install

}

rdir() {

echo not implemented

}
