#!/bin/bash
NAME="libclc"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/llvm/llvm-project/releases/download/llvmorg-$VERS/libclc-$VERS.src.tar.xz"
UPST="https://github.com/llvm/llvm-project/releases/latest"
SELE="h1.d-inline"
DEPS="llvm spirv_llvm_translator"  # llvm with clang


IDIR=$(cat << '~fin.'

CN

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/{share,include}/clc

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
