#!/bin/bash
NAME="libcap"
VERS="2.73"
LINK="https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-$VERS.tar.xz"
UPST="https://git.kernel.org/pub/scm/libs/libcap/libcap.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libcap-20070813 | head -n1 | cut -d- -f2"
DEPS=""


idir() {

sed -i '/install -m.*STA/d' libcap/Makefile

make prefix=/usr lib=lib
make prefix=/usr lib=lib install

make distclean
make CC="gcc -m32 -march=i686"
make CC="gcc -m32 -march=i686" lib=lib32 prefix=$PWD/DESTDIR/usr -C libcap install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
sed -e "s|^libdir=.*|libdir=/usr/lib32|" -i /usr/lib32/pkgconfig/lib{cap,psx}.pc
chmod -v 755 /usr/lib32/libcap.so.$VERS
rm -rf DESTDIR

}

rdir() {

echo not implemented

}
