#!/bin/bash
NAME="libdrm"
VERS="2.4.124"
LINK="https://dri.freedesktop.org/libdrm/libdrm-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/mesa/drm.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libdrm-2_0_0 | head -n1 | cut -d- -f2"
DEPS="libpciaccess"


idir() {

mn   \
    -D udev=true          \
    -D valgrind=disabled  \
    -D cairo-tests=disabled

32mn \
    -D udev=true          \
    -D valgrind=disabled  \
    -D cairo-tests=disabled

}

rdir() {

echo not implemented

}
