#!/bin/bash
NAME="libdrm"
VERS="2.4.123"
LINK="https://dri.freedesktop.org/libdrm/libdrm-$VERS.tar.xz"
UPST="https://dri.freedesktop.org/libdrm/?C=M;O=D"
SELE="body > table > tbody > tr:nth-child(4) > td:nth-child(2) > a"
DEPS="xorg_libraries"


IDIR=$(cat << '~fin.'

mn   \
    -D udev=true          \
    -D valgrind=disabled

32mn \
    -D udev=true          \
    -D valgrind=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
