#!/bin/bash
NAME="libepoxy"
VERS="${NAME}_version"; VERS="${!VERS}"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libepoxy/$ver/libepoxy-$VERS.tar.xz"
DEPS="mesa"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/libepoxy.so*   \
        /usr/include/epoxy

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
