#!/bin/bash
NAME="libevdev"
VERS="1.13.3"
LINK="https://www.freedesktop.org/software/libevdev/libevdev-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/libevdev/libevdev.git"
DEPS=""


idir() {

mn -D documentation=disabled

}

rdir() {

echo not implemented

}
