#!/bin/bash
NAME="libevdev"
VERS="1.13.3"
LINK="https://www.freedesktop.org/software/libevdev/libevdev-$VERS.tar.xz"
UPST="https://www.freedesktop.org/software/libevdev/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


idir() {

mn -D documentation=disabled

}

rdir() {

echo not implemented

}


