#!/bin/bash
NAME="libev"
VERS="4.33"
LINK="http://dist.schmorp.de/$NAME/$NAME-$VERS.tar.gz"
UPST="https://github.com/xorangekiller/libev-git.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n3 | head -n1 | cut -d- -f2 | sed 's/_/./g'" # for some reason, 4.43 exists in the tags, so breakage may ensue
DEPS=""


idir() {

cm
rm -vf /usr/include/event.h

}

rdir() {

rm -vf  /usr/lib/libev.{l,}a \
        /usr/lib/libev.so*

    }
