#!/bin/bash
NAME="libepoxy"
VERS="1.5.10"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libepoxy/$ver/libepoxy-$VERS.tar.xz"
UPST="https://github.com/anholt/libepoxy.git"
DEPS="mesa"


idir() {

mn

}

rdir() {

rm -rvf /usr/lib/libepoxy.so*   \
        /usr/include/epoxy

    }
