#!/bin/bash
NAME="libevdev"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.freedesktop.org/software/libevdev/libevdev-$VERS.tar.xz"
UPST="https://www.freedesktop.org/software/libevdev/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

mn -D documentation=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
