#!/bin/bash
NAME="libffi"
VERS="3.4.6"
LINK="https://github.com/libffi/libffi/releases/download/v$VERS/libffi-$VERS.tar.gz"
UPST="https://github.com/libffi/libffi.git"
DEPS=""


idir() {

cm --with-gcc-arch=native
32cm --with-gcc-arch=i686

}

rdir() {

echo not implemented

}
