#!/bin/bash
NAME="libffi"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/libffi/libffi/releases/download/v$VERS/libffi-$VERS.tar.gz"
UPST="https://github.com/libffi/libffi/tags"
DEPS=""


IDIR=$(cat << '~fin.'

cm --with-gcc-arch=native
32cm --with-gcc-arch=i686

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
