#!/bin/bash
NAME="libfontenc"
VERS="1.1.8"
LINK="https://www.x.org/pub/individual/lib/libfontenc-$VERS.tar.xz"
DEPS="glibc xorgproto util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libfontenc.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
