#!/bin/bash
NAME="libfs"
VERS="1.0.10"
LINK="https://www.x.org/pub/individual/lib/libFS-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libfs.git"
VCMD="git ls-remote --tags 'https://gitlab.freedesktop.org/xorg/lib/libfs.git' | sed 's:.*/::' | sort -V | grep libFS- | tail -n1 | cut -d- -f2"
DEPS="glibc xorgproto xtrans"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libFS.{la,so*}

}
