#!/bin/bash
NAME="libfontenc"
VERS="1.1.8"
LINK="https://www.x.org/pub/individual/lib/libfontenc-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libfontenc.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libfontenc-1_0_2 | head -n1 | cut -d- -f2"
DEPS="glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libfontenc.{la,so*}

}
