#!/bin/bash
NAME="libgpg_error"
VERS="1.50"
LINK="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$VERS.tar.bz2"
UPST="https://repology.org/project/libgpg-error/information"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
