#!/bin/bash
NAME="libglvnd"
VERS="1.7.0"
LINK="https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$VERS/libglvnd-v$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/glvnd/libglvnd/-/tags"
DEPS="xorg_libraries"


IDIR=$(cat << '~fin.'

mn
32mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
