#!/bin/bash
NAME="libgpg-error"
VERS=1.50
LINK="https://www.gnupg.org/ftp/gcrypt/$NAME/$NAME-$VERS.tar.bz2"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
