#!/bin/bash
NAME="libgpg-error"
VERS="1.51"
LINK="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$VERS.tar.gz"
UPST="https://github.com/gpg/libgpg-error.git"
DEPS=""


idir() {

cm

}

rdir() {

echo not implemented

}
