#!/bin/bash
NAME="libinput"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://gitlab.freedesktop.org/libinput/libinput/-/archive/$VERS/libinput-$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/libinput/libinput/-/tags"
DEPS="libevdev mtdev"


IDIR=$(cat << '~fin.'

mn \
    -D debug-gui=false        \
    -D tests=false            \
    -D libwacom=false         \
    -D udev-dir=/usr/lib/udev

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
