#!/bin/bash
NAME="libinput"
VERS="1.26.2"
LINK="https://gitlab.freedesktop.org/libinput/libinput/-/archive/$VERS/libinput-$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/libinput/libinput/-/tags"
DEPS="libevdev mtdev"


idir() {

mn \
    -D debug-gui=false        \
    -D tests=false            \
    -D libwacom=false         \
    -D udev-dir=/usr/lib/udev

}

rdir() {

echo not implemented

}
