#!/bin/bash
NAME="libice"
VERS="1.1.1"
LINK="https://www.x.org/pub/individual/lib/libICE-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libice/-/tags"
DEPS="glibc xorgproto xtrans util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libICE.{la,so*}

}


