#!/bin/bash
NAME="libidn2"
VERS=2.3.7
LINK="https://ftp.gnu.org/gnu/libidn/$NAME-$VERS.tar.gz"
DEPS="libunistring"


IDIR=$(cat <<EOF

cm
32cm

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
