#!/bin/bash
NAME="libidn2"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/libidn/$NAME-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/libidn/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS="libunistring"


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
