#!/bin/bash
NAME="libjpeg-turbo"
VERS="3.0.90" # beta
LINK="https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/$VERS/libjpeg-turbo-$VERS.tar.gz"
UPST="https://github.com/libjpeg-turbo/libjpeg-turbo.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 jpeg-1 | head -n1"
DEPS="cmake yasm"


idir() {

CN \
  -D ENABLE_STATIC=FALSE              \
  -D CMAKE_INSTALL_DEFAULT_LIBDIR=lib

}

rdir() {

rm -vf \
    /usr/bin/cjpeg          \
    /usr/bin/djpeg          \
    /usr/bin/jpegtran       \
    /usr/bin/rdjpgcom       \
    /usr/bin/tjbench        \
    /usr/bin/wrjpgcom       \
    /usr/lib/libjpeg.so*    \
    /usr/lib/libturbojpeg.so*

rm -rvf /usr/share/doc/libjpeg-turbo-$VERS

}
