#!/bin/bash
NAME="libogg"
VERS="1.3.5"
LINK="https://downloads.xiph.org/releases/ogg/libogg-$VERS.tar.xz"
UPST="https://github.com/xiph/ogg.git"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash/
32cm

}

rdir() {

echo not implemented

}
