#!/bin/bash
NAME="libogg"
VERS=1.3.5
LINK="https://downloads.xiph.org/releases/ogg/libogg-$VERS.tar.xz"
DEPS=""


IDIR=$(cat <<EOF

cm --docdir=/tmp/rid/trash/
32cm

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
