#!/bin/bash
NAME="libopusenc"
VERS="0.2.1"
LINK="https://github.com/xiph/libopusenc/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/xiph/libopusenc.git"
DEPS=""


idir() {

./autogen.sh
cm

sed -i "s/unknown/$VERS/" /usr/lib/pkgconfig/libopusenc.pc

}

rdir() {

echo "not implemented"

}
