#!/bin/bash
NAME="libogg"
VERS="${!NAME}_version"
LINK="https://downloads.xiph.org/releases/ogg/libogg-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash/
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
