#!/bin/bash
NAME="libpipeline"
VERS="1.5.8"
LINK="https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$VERS.tar.gz"
UPST="https://gitlab.com/libpipeline/libpipeline.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 2.4.2 | head -n1"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /usr/lib/libpipeline.so*

}
