#!/bin/bash
NAME="libpng"
VERS="1.6.44"
LINK="https://github.com/pnggroup/libpng/archive/refs/tags/v$VERS.tar.gz"
DOWN="https://downloads.sourceforge.net/project/libpng-apng/libpng16/$VERS/libpng-$VERS-apng.patch.gz"
UPST="https://github.com/pnggroup/libpng/tags"
DEPS=""


idir() {

gzip -cd "$RIDSOURCES"/libpng-$VERS-apng.patch.gz | patch -p1

cm
32cm

}

rdir() {

rm -rvf /usr/bin/libpng{,16}-config \
  /usr/bin/{pngfix,png-fix-itxt}    \
  /usr/include/libpng16             \
  /usr/lib/libpng{,16}.*

}


