#!/bin/bash
NAME="libplacebo"
VERS="7.349.0"
LINK="https://github.com/haasn/libplacebo/archive/v$VERS/libplacebo-$VERS.tar.gz"
UPST="https://github.com/haasn/libplacebo.git"
DEPS="ffmpeg glad"


idir() {

sed -e "20s/$/,/"                                         \
    -e "21i cxx.find_library('glslang', required: false)" \
    -i src/glsl/meson.build

mn \
    -D tests=false  \
    -D demos=false

}

rdir() {

rm -rvf /usr/include/libplacebo \
        /usr/lib/libplacebo.so*

    }
