#!/bin/bash
NAME="libpng"
VERS=1.6.44
LINK="https://github.com/pnggroup/libpng/archive/refs/tags/v$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

raw https://downloads.sourceforge.net/project/libpng-apng/libpng16/$VERS/libpng-$VERS-apng.patch.gz
gzip -cd /etc/rid/sources/libpng-$VERS-apng.patch.gz | patch -p1

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/bin/libpng{,16}-config \
  /usr/bin/{pngfix,png-fix-itxt}    \
  /usr/include/libpng16             \
  /usr/lib/libpng{,16}.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
