#!/bin/bash
NAME="libpsl"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/rockdaboot/$NAME/releases/download/$VERS/$NAME-$VERS.tar.gz"
DEPS="libidn2 libunistring"


IDIR=$(cat << '~fin.'

mn
32mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
