#!/bin/bash
NAME="libpng"
VERS="1.6.44"
LINK="https://github.com/pnggroup/libpng/archive/refs/tags/v$VERS.tar.gz"
DOWN="https://sourceforge.net/projects/libpng-apng/files/latest/download" # apng patch
UPST="https://github.com/pnggroup/libpng.git"
VCMD="git ls-remote --tags 'https://github.com/pnggroup/libpng.git' | sed 's:.*/::' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1" # not using betas bc of the patch
DEPS=""


idir() {

gzip -cd "$RIDSOURCES"/libpng-$VERS-apng.patch.gz | patch -p1

cm
32cm

}

rdir() {

rm -rvf /usr/bin/libpng{,16}-config \
  /usr/bin/{pngfix,png-fix-itxt}    \
  /usr/include/libpng16             \
  /usr/lib/libpng{,16}.*

}
