#!/bin/bash
NAME="libpciaccess"
VERS="0.18.1"
LINK="https://www.x.org/pub/individual/lib/libpciaccess-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libpciaccess/-/tags"
DEPS=""


idir() {

mn
32mn

}

rdir() {

rm -vf /usr/lib{,32}/libpciaccess.so*

}
