#!/bin/bash
NAME="libpsl"
VERS=0.21.5
LINK="https://github.com/rockdaboot/$NAME/releases/download/$VERS/$NAME-$VERS.tar.gz"
DEPS="libidn2 libunistring"


IDIR=$(cat <<EOF

mn
32mn

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
