#!/bin/bash
NAME="libpsl"
VERS="0.21.5"
LINK="https://github.com/rockdaboot/$NAME/releases/download/$VERS/$NAME-$VERS.tar.gz"
UPST="https://github.com/rockdaboot/$NAME.git"
DEPS="libidn2 libunistring"


idir() {

mn
32mn

}

rdir() {

echo not implemented

}
