#!/bin/bash
NAME="libpipeline"
VERS="1.5.8"
LINK="https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libpipeline.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
