#!/bin/bash
NAME="libsndfile"
VERS="${!NAME}_version"
LINK="https://github.com/$NAME/$NAME/releases/download/$VERS/$NAME-$VERS.tar.xz"
DEPS="flac opus libvorbis alsa-lib"


IDIR=$(cat << '~fin.'

cm   --disable-mpeg --docdir=/tmp/rid/trash 
32cm --disable-mpeg

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
