#!/bin/bash
NAME="libsm"
VERS="1.2.4"
LINK="https://www.x.org/pub/individual/lib/libSM-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libsm/-/tags"
DEPS="libice util-linux xorgproto glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libSM.{la,so*}

}


