#!/bin/bash
NAME="libsndfile"
VERS=1.2.2
LINK="https://github.com/$NAME/$NAME/releases/download/$VERS/$NAME-$VERS.tar.xz"
DEPS="flac opus libvorbis alsa-lib"


IDIR=$(cat <<EOF

cm   --disable-mpeg --docdir=/tmp/rid/trash 
32cm --disable-mpeg

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
