#!/bin/bash
NAME="libsm"
VERS="1.2.5"
LINK="https://www.x.org/pub/individual/lib/libSM-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libsm.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libSM-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libice util-linux xorgproto glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libSM.{la,so*}

}
