#!/bin/bash
NAME="libtasn1"
VERS="4.19.0"
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/$NAME/?C=M;O=D"
DEPS=""


idir() {

cm
32cm

}

rdir() {

echo not implemented

}
