#!/bin/bash
NAME="libtiff"
VERS="4.7.0"
LINK="https://gitlab.com/libtiff/libtiff/-/archive/v$VERS/libtiff-v$VERS.tar.bz2"
UPST="https://gitlab.com/libtiff/libtiff.git"
DEPS="cmake libjpeg-turbo libwebp"


idir() {

CN

}

rdir() {

rm -vf bin/{fax2ps,fax2tiff,pal2rgb,ppm2tiff,raw2tiff,tiff2bw,tiff2pdf,tiff2ps,tiff2rgba,tiffcmp,tiffcp,tiffcrop,tiffdither,tiffdump,tiffgt,tiffinfo,tiffmedian,tiffset,tiffsplit}
rm -vf /usr/lib/libtiff{,xx}.so*

rm -rvf /usr/lib/cmake/tiff

}
