#!/bin/bash
NAME="libtasn1"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/$NAME/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
