#!/bin/bash
NAME="libtasn1"
VERS=4.19.0
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<EOF

cm
32cm

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
