#!/bin/bash
NAME="libtiff"
VERS="4.7.0"
LINK="https://download.osgeo.org/libtiff/tiff-$VERS.tar.xz"
UPST="https://download.osgeo.org/libtiff/?C=M&O=D"
SELE="#list > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(1) > a:nth-child(1)"
DEPS="cmake libjpeg-turbo libwebp"


idir() {

CN

}

rdir() {

rm -vf bin/{fax2ps,fax2tiff,pal2rgb,ppm2tiff,raw2tiff,tiff2bw,tiff2pdf,tiff2ps,tiff2rgba,tiffcmp,tiffcp,tiffcrop,tiffdither,tiffdump,tiffgt,tiffinfo,tiffmedian,tiffset,tiffsplit}
rm -vf /usr/lib/libtiff{,xx}.so*

rm -rvf /usr/lib/cmake/tiff

}


