#!/bin/bash
NAME="libunwind"
VERS=1.6.2
LINK="https://download.savannah.nongnu.org/releases/libunwind/libunwind-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << 'EOF'

./configure --prefix=/usr --disable-static &&
make
make DESTDIR= install

make clean && rm -f Makefile
CC="gcc -m32" CXX="g++ -m32"                     \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig             \
CFLAGS+=" -Wno-error=incompatible-pointer-types" \
./configure --prefix=/usr                        \
            --libdir=/usr/lib32                  \
            --host=i686-pc-linux-gnu             \
            --disable-static &&

make
make DESTDIR=/tmp/rid/dest install
cp -vr /tmp/rid/dest/usr/lib32/* /usr/lib32
cp -v /tmp/rid/dest/usr/include/libunwind-x86.h /usr/include
rm -rf /tmp/rid/dest/*
ldconfig
unset DESTDIR

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
