#!/bin/bash
NAME="libuv"
VERS="${!NAME}_version"
LINK="https://dist.libuv.org/dist/v$VERS/libuv-v$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

sh autogen.sh                              &&
./configure --prefix=/usr --disable-static &&
make
make install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
