#!/bin/bash
NAME="libuv"
VERS="1.49.2"
LINK="https://dist.libuv.org/dist/v$VERS/libuv-v$VERS.tar.gz"
UPST="https://github.com/libuv/libuv/releases/latest"
DEPS=""


idir() {

sh autogen.sh                              &&
./configure --prefix=/usr --disable-static &&
make
make install

}

rdir() {

echo not implemented

}


