#!/bin/bash
NAME="libunistring"
VERS="1.3"
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/$NAME/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


idir() {

cm --docdir=/tmp/rid/trash
32cm

}

rdir() {

echo not implemented

}
