#!/bin/bash
NAME="libunwind"
VERS=1.8.1
LINK="https://github.com/libunwind/libunwind/releases/download/v$VERS/libunwind-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

CC="gcc -m32" CXX="g++ -m32"                     \
PKG_Cb32/pkgconfig             \
CFLAGS+=" -Wno-error=incompatible-pointer-types" \
./configure --prefix=/usr                        \
            --libdir=/usr/lib32                  \
            --host=i686-pc-linux-gnu             \
            --disable-static &&

make
make DESTDIR=/tmp/rid/dest install
cp -vr /tmp/rid/dest/usr/lib32/* /usr/lib32
cp -v /tmp/rid/dest/usr/include/libunwind-x86.h /usr/include
rm -rf /tmp/rid/dest/*
ldconfig
unset DESTDIR

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/lib/libunwind.* \
        /usr/lib/libunwind-*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
