#!/bin/bash
NAME="libunistring"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
