#!/bin/bash
NAME="libunwind"
VERS="1.8.1"
LINK="https://github.com/libunwind/libunwind/releases/download/v$VERS/libunwind-$VERS.tar.gz"
UPST="https://github.com/libunwind/libunwind/tags"
DEPS=""


idir() {

RIDBUILD=false
cm
unset RIDBUILD

make clean
CC="gcc -m32" CXX="g++ -m32"                     \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig             \
CFLAGS+=" -Wno-error=incompatible-pointer-types" \
./configure --prefix=/usr                        \
            --libdir=/usr/lib32                  \
            --host=i686-pc-linux-gnu             \
            --disable-static &&

make

make DESTDIR=$PWD/DESTDIR install
cp -vr DESTDIR/usr/lib32/* /usr/lib32
cp -v DESTDIR/usr/include/libunwind-x86.h /usr/include
rm -rf DESTDIR
ldconfig

}

rdir() {

rm -vf  /usr/lib/libunwind.* \
        /usr/lib/libunwind-*

    }
