#!/bin/bash
NAME="libvorbis"
VERS="1.3.7"
LINK="https://downloads.xiph.org/releases/vorbis/libvorbis-$VERS.tar.xz"
UPST="https://github.com/xiph/vorbis/tags"
DEPS="libogg"


idir() {

cm
32cm

}

rdir() {

echo not implemented

}
