#!/bin/bash
NAME="libvdpau_va_gl"
VERS="0.4.2"
LINK="https://github.com/i-rinat/libvdpau-va-gl/archive/v$VERS/libvdpau-va-gl-$VERS.tar.gz"
UPST="https://github.com/i-rinat/libvdpau-va-gl/tags"
DEPS="cmake libvdpau libva"


IDIR=$(cat << '~fin.'

CN

mkdir build && cd build
CC="gcc -m32" CXX="g++ -m32"                 \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig         \
cmake -D CMAKE_BUILD_TYPE=Release            \
      -D CMAKE_INSTALL_PREFIX=/usr           \
      .. &&

make
make DESTDIR=$PWD/DESTDIR install
# cant abstract because 32-bit instructions install to lib lol
cp -vr DESTDIR/usr/lib/* /usr/lib32
rm -rf DESTDIR
ldconfig

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/vdpau/libvdpau_va_gl.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
