#!/bin/bash
NAME="libvorbis"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://downloads.xiph.org/releases/vorbis/libvorbis-$VERS.tar.xz"
DEPS="libogg"


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
