#!/bin/bash
NAME="libva"
VERS="2.22.0"
LINK="https://github.com/intel/libva/archive/$VERS/libva-$VERS.tar.gz"
UPST="https://github.com/intel/libva/tags"
DEPS="libdrm"


idir() {

mn
32mn

}

rdir() {

rm -rvf /usr/lib/libva-drm.so*      \
       /usr/lib/libva-glx.so*       \
       /usr/lib/libva.so*           \
       /usr/lib/libva-wayland.so*   \
       /usr/lib/libva-x11.so*       \
       /usr/include/va

   }


