#!/bin/bash
NAME="libvdpau"
VERS="${!NAME}_version"
LINK="https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/$VERS/libvdpau-$VERS.tar.bz2"
DEPS="xorg-libraries"


IDIR=$(cat << '~fin.'

mn   -D documentation=false
32mn -D documentation=false

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/{lib,include}/vdpau
rm -vf /usr/lib{,32}/libvdpau.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
