#!/bin/bash
NAME="libva"
VERS=2.22.0
LINK="https://github.com/intel/libva/archive/$VERS/libva-$VERS.tar.gz"
DEPS="libdrm"


IDIR=$(cat << '~fin.'

mn
32mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/libva-drm.so*      \
       /usr/lib/libva-glx.so*       \
       /usr/lib/libva.so*           \
       /usr/lib/libva-wayland.so*   \
       /usr/lib/libva-x11.so*       \
       /usr/include/va

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
