#!/bin/bash
NAME="libvorbis"
VERS="1.3.7"
LINK="https://downloads.xiph.org/releases/vorbis/libvorbis-$VERS.tar.xz"
UPST="https://github.com/xiph/vorbis/tags"
DEPS="libogg"


IDIR=$(cat << '~fin.'

cm
32cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
