#!/bin/bash
NAME="libvdpau"
VERS="1.5"
LINK="https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/$VERS/libvdpau-$VERS.tar.bz2"
UPST="https://gitlab.freedesktop.org/vdpau/libvdpau.git"
DEPS="glibc libx11 libxext xorgproto"


idir() {

mn   -D documentation=false
32mn -D documentation=false

}

rdir() {

rm -rvf /usr/{lib,include}/vdpau
rm -vf /usr/lib{,32}/libvdpau.so*

}
