#!/bin/bash
NAME="libx11"
VERS="1.8.10"
LINK="https://www.x.org/pub/individual/lib/libX11-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libx11/-/tags"
DEPS="libxcb glibc xorgproto util-macros xtrans"


idir() {

cm $XORG_CONFIG --disable-xf86bigfont
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libX11.{la,so*}

}
