#!/bin/bash
NAME="libxfixes"
VERS="6.0.1"
LINK="https://www.x.org/pub/individual/lib/libXfixes-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxfixes/-/tags"
DEPS="libx11 xorgproto glibc util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXfixes.{la,so*}

}


