#!/bin/bash
NAME="libxau"
VERS="1.0.11"
LINK="https://www.x.org/pub/individual/lib/libXau-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxau/-/tags"
DEPS="xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG

}

rdir() {

rm -vf /usr/lib{,32}/libXau.*

}


