#!/bin/bash
NAME="libxslt"
VERS="${!NAME}_version"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libxslt/$ver/libxslt-$VERS.tar.xz"
DEPS="libxml2 docbook-xml docbook-xsl-nons"


IDIR=$(cat << '~fin.'

cm --docdir=/tmp/rid/trash

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/xslt-config \
       /usr/bin/xsltproc    \
       /usr/lib/libexslt.*  \
       /usr/lib/libxslt.*

rm -rvf /usr/include/libexslt    \
        /usr/include/libxslt     \
        /usr/lib/cmake/libxslt   \
        /usr/lib/libxslt-plugins

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
