#!/bin/bash
NAME="libxcrypt"
VERS="4.4.36"
LINK="https://github.com/besser82/libxcrypt/releases/download/v$VERS/libxcrypt-$VERS.tar.xz"
UPST="https://github.com/besser82/libxcrypt/releases/latest"
DEPS=""


IDIR=$(cat << '~fin.'

cm      --enable-hashes=strong,glibc    \
        --enable-obsolete-api=no        \
        --disable-failure-tokens

CC="gcc -m32" \
./configure --prefix=/usr                \
            --host=i686-pc-linux-gnu     \
            --libdir=/usr/lib32          \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=glibc  \
            --disable-static             \
            --disable-failure-tokens

make
cp -av .libs/libcrypt.so* /usr/lib32/ &&
make install-pkgconfigDATA &&
ln -svf libxcrypt.pc /usr/lib32/pkgconfig/libcrypt.pc

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
