#!/bin/bash
NAME="libxkbfile"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/lib/libxkbfile-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxkbfile/-/tags"
DEPS="libx11 xorgproto glibc util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
