#!/bin/bash
NAME="libxxf86vm"
VERS="1.1.5"
LINK="https://www.x.org/pub/individual/lib/libXxf86vm-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxxf86vm.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXxf86vm-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libxext libx11 glibc xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXxf86vm.{la,so*}

}
