#!/bin/bash
NAME="libxft"
VERS="2.3.8"
LINK="https://www.x.org/pub/individual/lib/libXft-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxft/-/tags"
DEPS="fontconfig libxrender libx11 freetype2 glibc xorgproto"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXft.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
