#!/bin/bash
NAME="libxcomposite"
VERS="0.4.6"
LINK="https://www.x.org/pub/individual/lib/libXcomposite-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcomposite/-/tags"
DEPS="libxfixes xorgproto libx11 glibc util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXcomposite.{la,so*}

}
