#!/bin/bash
NAME="libxfont2"
VERS="2.0.7"
LINK="https://www.x.org/pub/individual/lib/libXfont2-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxfont/-/tags"
DEPS="freetype2 libfontenc xorgproto glibc xtrans util-macros"


idir() {

cm   $XORG_CONFIG    --disable-open-zfile
32cm $XORG_CONFIG_32 --disable-open-zfile

}

rdir() {

rm -vf /usr/lib{,32}/libXfont2.{la,so*}

}
