#!/bin/bash
NAME="libxinerama"
VERS="1.1.5"
LINK="https://www.x.org/pub/individual/lib/libXinerama-$VERS.tar.xz"
DEPS="libxext libx11 glibc xorgproto util_macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXinerama.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
