#!/bin/bash
NAME="libxres"
VERS="1.2.2"
LINK="https://www.x.org/pub/individual/lib/libXres-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxres.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXres-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libxext libx11 glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXRes.{la,so*}

}
