#!/bin/bash
NAME="libxcvt"
VERS="0.1.2"
LINK="https://www.x.org/pub/individual/lib/libxcvt-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcvt.git"
DEPS=""


idir() {

mn
32mn

}

rdir() {

rm -rvf                         \
    /usr/bin/cvt                \
    /usr/lib{,32}/libxcvt.so*   \
    /usr/include/libxcvt

}
