#!/bin/bash
NAME="libxss"
VERS="1.2.4"
LINK="https://www.x.org/pub/individual/lib/libXScrnSaver-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXScrnSaver-1_1_0 | head -n1 | cut -d- -f2"
DEPS="libxext libx11 glibc xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXss.{la,so*}

}
