#!/bin/bash
NAME="libxdamage"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXdamage-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxdamage.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXdamage-1_0_3 | head -n1 | cut -d- -f2"
DEPS="libxfixes xorgproto libx11 glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXdamage.{la,so*}

}
