#!/bin/bash
NAME="libx11"
VERS="1.8.11"
LINK="https://www.x.org/pub/individual/lib/libX11-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libx11.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libX11-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libxcb glibc xorgproto util-macros xtrans"


idir() {

cm $XORG_CONFIG --disable-xf86bigfont
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libX11.{la,so*}

}
