#!/bin/bash
NAME="libxxf86dga"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXxf86dga-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxxf86dga/-/tags"
DEPS="xorgproto libxext libx11 util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXxf86dga.{la,so*}

}


