#!/bin/bash
NAME="libxdamage"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXdamage-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxdamage/-/tags"
DEPS="libxfixes xorgproto libx11 glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXdamage.{la,so*}

}


