#!/bin/bash
NAME="libxt"
VERS="1.3.1"
LINK="https://www.x.org/pub/individual/lib/libXt-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxt/-/tags"
DEPS="libsm libx11 libice glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG 
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXt.{la,so*}

}


