#!/bin/bash
NAME="libxext"
VERS="1.3.6"
LINK="https://www.x.org/pub/individual/lib/libXext-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxext/-/tags"
DEPS="libx11 glibc xorgproto util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXext.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
