#!/bin/bash
NAME="libxkbcommon"
VERS="1.7.0"
LINK="https://xkbcommon.org/download/$NAME-$VERS.tar.xz"
UPST="https://github.com/xkbcommon/libxkbcommon/releases/latest"
DEPS="xkeyboard-config libxcb wayland wayland-protocols"


idir() {

mn   -D enable-docs=false
32mn -D enable-docs=false

}

rdir() {

rm -rvf \
    /usr/bin/xkbcli               \
    /usr/lib{,32}/libxkbcommon*   \
    /usr/lib{,32}/libxkbregistry* \
    /usr/include/xkbcommon        \
    /usr/libexec/xkbcommon

}
