#!/bin/bash
NAME="libxvmc"
VERS="1.0.14"
LINK="https://www.x.org/pub/individual/lib/libXvMC-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxvmc.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXvMC-1_0_2 | head -n1 | cut -d- -f2"
DEPS="libxext libxv libx11 xorgproto glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXvMN{,W}.{la,so*}

}
