#!/bin/bash
NAME="libxdmcp"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/lib/libXdmcp-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxdmcp/-/tags"
DEPS="xorgproto"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG --docdir=/tmp/rid/trash
32cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib{,32}/libXdmcp.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
