#!/bin/bash
NAME="libxdamage"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXdamage-$VERS.tar.xz"
DEPS="libxfixes xorgproto libx11 glibc"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXdamage.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
