#!/bin/bash
NAME="libxss"
VERS="1.2.4"
LINK="https://www.x.org/pub/individual/lib/libXScrnSaver-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver/-/tags"
DEPS="libxext libx11 glibc xorgproto"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXss.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
