#!/bin/bash
NAME="libxxf86dga"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXxf86dga-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxxf86dga/-/tags"
DEPS="xorgproto libxext libx11 util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXxf86dga.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
