#!/bin/bash
NAME="libxext"
VERS="1.3.6"
LINK="https://www.x.org/pub/individual/lib/libXext-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxext.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libXext-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libx11 glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXext.{la,so*}

}
