#!/bin/bash
NAME="libxml2"
VERS="2.13.5"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libxml2/$ver/libxml2-$VERS.tar.xz"
UPST="https://github.com/GNOME/libxml2.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS="icu"


idir() {

cm --sysconfdir=/etc       \
   --with-history          \
   --with-icu              \
   PYTHON=/usr/bin/python3 \
   --docdir=/tmp/rid/trash/ &&

rm -vf /usr/lib/libxml2.la &&
sed '/libs=/s/xml2.*/xml2"/' -i /usr/bin/xml2-config

32cm --sysconfdir=/etc       \
     --with-history          \
     --with-icu              \
     --without-python        \

rm -vf /usr/lib32/libxml2.la

}

rdir() {

echo not implemented

}
