#!/bin/bash
NAME="libxv"
VERS="1.0.12"
LINK="https://www.x.org/pub/individual/lib/libXv-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxv/-/tags"
DEPS="libxext libx11 glibc xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXv.{la,so*}

}


