#!/bin/bash
NAME="libxcvt"
VERS="0.1.2"
LINK="https://www.x.org/pub/individual/lib/libxcvt-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcvt/-/tags"
DEPS=""


IDIR=$(cat << '~fin.'

mn
32mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf                         \
    /usr/bin/cvt                \
    /usr/lib{,32}/libxcvt.so*   \
    /usr/include/libxcvt

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
