#!/bin/bash
NAME="libxrandr"
VERS="1.5.4"
LINK="https://www.x.org/pub/individual/lib/libXrandr-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxrandr/-/tags"
DEPS="libxext libxrender libx11 glibc util-macros xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXrandr.{la,so*}

}
