#!/bin/bash
NAME="libxau"
VERS="1.0.11"
LINK="https://www.x.org/pub/individual/lib/libXau-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxau.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 libXau-1_0_1 | head -n1 | cut -d- -f2"
DEPS="xorgproto"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG

}

rdir() {

rm -vf /usr/lib{,32}/libXau.*

}
