#!/bin/bash
NAME="libxinerama"
VERS="1.1.5"
LINK="https://www.x.org/pub/individual/lib/libXinerama-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxinerama/-/tags"
DEPS="libxext libx11 glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXinerama.{la,so*}

}
