#!/bin/bash
NAME="libxpresent"
VERS="1.0.1"
LINK="https://www.x.org/pub/individual/lib/libXpresent-$VERS.tar.xz"
DEPS="libxfixes libxrandr libxext libx11 glibc xorgproto util_macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXpresent.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
