#!/bin/bash
NAME="libxrandr"
VERS="1.5.4"
LINK="https://www.x.org/pub/individual/lib/libXrandr-$VERS.tar.xz"
DEPS="libxext libxrender libx11 glibc util_macros xorgproto"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXrandr.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
