#!/bin/bash
NAME="libxaw"
VERS="3.5.17"
LINK="https://www.x.org/pub/individual/lib/libXpm-$VERS.tar.xz"
DEPS="libxmu libxpm libx11 libxt libxext xorgproto glibc util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXaw{,6,7}.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
