#!/bin/bash
NAME="libxslt"
VERS="1.1.42"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libxslt/$ver/libxslt-$VERS.tar.xz"
UPST="https://gitlab.gnome.org/GNOME/libxslt/-/tags"
DEPS="libxml2 docbook-xml docbook-xsl-nons"


idir() {

cm --docdir=/tmp/rid/trash

}

rdir() {

rm -vf /usr/bin/xslt-config \
       /usr/bin/xsltproc    \
       /usr/lib/libexslt.*  \
       /usr/lib/libxslt.*

rm -rvf /usr/include/libexslt    \
        /usr/include/libxslt     \
        /usr/lib/cmake/libxslt   \
        /usr/lib/libxslt-plugins

    }


