#!/bin/bash
NAME="libxcursor"
VERS="1.2.3"
LINK="https://www.x.org/pub/individual/lib/libXcursor-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcursor/-/tags"
DEPS="libxfixes libxrender libx11 glibc xorgproto util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXcursor.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
