#!/bin/bash
NAME="libxpm"
VERS="3.5.17"
LINK="https://www.x.org/pub/individual/lib/libXpm-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxpm/-/tags"
DEPS="libxt libxext libx11 glibc util-macros"


idir() {

cm   $XORG_CONFIG    --disable-open-zfile
32cm $XORG_CONFIG_32 --disable-open-zfile

}

rdir() {

rm -vf /usr/lib{,32}/libXpm.{la,so*}

}


