#!/bin/bash
NAME="libxkbfile"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/lib/libxkbfile-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxkbfile.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libxkbfile-1_0_2 | head -n1 | cut -d- -f2"
DEPS="libx11 xorgproto glibc util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

echo not implemented

}
