#!/bin/bash
NAME="libxpresent"
VERS="1.0.1"
LINK="https://www.x.org/pub/individual/lib/libXpresent-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxpresent.git"
DEPS="libxfixes libxrandr libxext libx11 glibc xorgproto util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXpresent.{la,so*}

}
