#!/bin/bash
NAME="libxml2"
VERS="2.13.4"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libxml2/$ver/libxml2-$VERS.tar.xz"
UPST="https://gitlab.gnome.org/GNOME/libxml2/-/tags"
DEPS="icu"


IDIR=$(cat <<'~fin.'

cm --sysconfdir=/etc       \
   --with-history          \
   --with-icu              \
   PYTHON=/usr/bin/python3 \
   --docdir=/tmp/rid/trash/ &&

rm -vf /usr/lib/libxml2.la &&
sed '/libs=/s/xml2.*/xml2"/' -i /usr/bin/xml2-config

32cm --sysconfdir=/etc       \
     --with-history          \
     --with-icu              \
     --without-python        \

rm -vf /usr/lib32/libxml2.la

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
