#!/bin/bash
NAME="libxml2"
VERS=2.13.4
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/libxml2/$ver/libxml2-$VERS.tar.xz"
DEPS="icu"


IDIR=$(cat <<'~fin.'

echo $DESTDIR
echo $MAKEFLAGS
echo $NAME-$VERS
sleep 10

./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --disable-static        \
            --with-history          \
            --with-icu              \
            PYTHON=/usr/bin/python3 \
            --docdir=/usr/share/doc/libxml2-2.13.4 &&
make
make install
rm -vf /usr/lib/libxml2.la &&
sed '/libs=/s/xml2.*/xml2"/' -i /usr/bin/xml2-config

make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --sysconfdir=/etc        \
            --disable-static         \
            --with-history           \
            --with-icu               \
            --without-python &&
make
make DESTDIR=$DESTDIR install &&
rm -vf DESTDIR/usr/lib32/libxml2.la   &&
cp -Rv DESTDIR/usr/lib32/* /usr/lib32 &&
rm -rf DESTDIR                        &&
ldconfig

~fin.
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
