#!/bin/bash
NAME="libxcb"
VERS=1.17.0
LINK="https://xorg.freedesktop.org/archive/individual/lib/libxcb-$VERS.tar.xz"
DEPS="libxau xcb-proto libxdmcp"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG --without-doxygen --docdir=/tmp/rid/trash
32cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

pushd /usr/lib
rm -vf \
  libxcb.so* libxcb-composite.so* libxcb-damage.so* libxcb-dbe.so* libxcb-dpms.so* libxcb-dri2.so* libxcb-dri3.so* libxcb-glx.so* libxcb-present.so* libxcb-randr.so* libxcb-record.so* libxcb-render.so* libxcb-res.so* libxcb-screensaver.so* libxcb-shape.so* libxcb-shm.so* libxcb-sync.so* libxcb-xf86dri.so* libxcb-xfixes.so* libxcb-xinerama.so* libxcb-xinput.so* libxcb-xkb.so* libxcb-xtest.so* libxcb-xvmc.so* and libxcb-xv.so*
popd
pushd /usr/lib32
rm -vf \
  libxcb.so* libxcb-composite.so* libxcb-damage.so* libxcb-dbe.so* libxcb-dpms.so* libxcb-dri2.so* libxcb-dri3.so* libxcb-glx.so* libxcb-present.so* libxcb-randr.so* libxcb-record.so* libxcb-render.so* libxcb-res.so* libxcb-screensaver.so* libxcb-shape.so* libxcb-shm.so* libxcb-sync.so* libxcb-xf86dri.so* libxcb-xfixes.so* libxcb-xinerama.so* libxcb-xinput.so* libxcb-xkb.so* libxcb-xtest.so* libxcb-xvmc.so* and libxcb-xv.so*
popd

rm -rvf /usr/include/xcb/


~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
