#!/bin/bash
NAME="libxmu"
VERS="1.2.1"
LINK="https://www.x.org/pub/individual/lib/libXmu-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxmu.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXmu-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libxext libxt libx11 xorgproto glibc util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXmu{,u}.{la,so*}

}
