#!/bin/bash
NAME="libxvmc"
VERS="1.0.14"
LINK="https://www.x.org/pub/individual/lib/libXvMC-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxvmc/-/tags"
DEPS="libxext libxv libx11 xorgproto glibc"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libXvMN{,W}.{la,so*}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
