#!/bin/bash
NAME="libxxf86dga"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/lib/libXxf86dga-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxxf86dga.git"
VCMD="git ls-remote --tags 'https://gitlab.freedesktop.org/xorg/lib/libxxf86dga.git' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 libXxf86dga-1_0_1 | head -n1 | cut -d- -f2"
DEPS="xorgproto libxext libx11 util-macros"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libXxf86dga.{la,so*}

}
