#!/bin/bash
NAME="libxshmfence"
VERS="1.3.2"
LINK="https://www.x.org/pub/individual/lib/libxshmfence-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxshmfence/-/tags"
DEPS="util-macros xorgproto glibc"


idir() {

cm $XORG_CONFIG
32cm $XORG_CONFIG_32

}

rdir() {

rm -vf /usr/lib{,32}/libxshmfence.{la,so*}

}
