#!/bin/bash
NAME="libyaml"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/yaml/libyaml/releases/download/$VERS/yaml-$VERS.tar.gz"
UPST="https://github.com/yaml/libyaml/tags"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libyaml.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
