#!/bin/bash
NAME="luajit"
VERS="20240917"
LINK="https://anduin.linuxfromscratch.org/BLFS/luajit/luajit-$VERS.tar.xz"
UPST="https://www.linuxfromscratch.org/blfs/view/svn/general/luajit"
SELE=".ulink"
DEPS=""


idir() {

make PREFIX=/usr
make PREFIX=/usr install

rm -vf /usr/lib/libluajit-5.1.a

}

rdir() {

rm -vf  /usr/bin/luajit{,-2.1.ROLLING}  \
        /usr/lib/libluajit-5.1.so*

rm -rvf /usr/include/luajit-2.1 \
        /usr/share/luajit-2.1

    }
