#!/bin/bash
NAME="luarocks"
VERS="3.11.1"
LINK="https://luarocks.org/releases/luarocks-$VERS.tar.gz"
UPST="https://luarocks.github.io/luarocks/releases"
SELE=".main_column > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > a:nth-child(1)"
DEPS=""


idir() {

# luarocks's configure treats unknown flags as errors
./configure --prefix=/usr
make
make install

}

rdir() {

echo not implemented

}
