#!/bin/bash
NAME="luarocks"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://luarocks.org/releases/luarocks-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

# luarocks's configure treats unknown flags as errors
./configure --prefix=/usr
make
make install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
