#!/bin/bash
NAME="luit"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://invisible-mirror.net/archives/luit/luit-$VERS.tgz"
UPST="https://invisible-mirror.net/archives/luit/current/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS="xorg_applications"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/luit

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
