#!/bin/bash
NAME="lynx"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://invisible-mirror.net/archives/lynx/tarballs/lynx$VERS.tar.bz2"
DEPS=""


IDIR=$(cat << '~fin.'

./configure --prefix=/usr           \
            --sysconfdir=/etc/lynx  \
            --with-zlib             \
            --with-bzlib            \
            --with-ssl              \
            --with-screen=ncursesw  \
            --enable-locale-charset \
            --datadir=/usr/share/doc/lynx-$VERS &&
make
make install-full
chgrp -v -R root /usr/share/doc/lynx-$VERS/lynx_doc

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/lynx
rm -rvf /etc/lynx \
  /usr/share/doc/lynx-$VERS

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
