#!/bin/bash
NAME="lynx"
VERS="2.9.2"
LINK="https://invisible-mirror.net/archives/lynx/tarballs/lynx$VERS.tar.bz2"
UPST="https://invisible-mirror.net/archives/lynx/tarballs/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


idir() {

./configure --prefix=/usr           \
            --sysconfdir=/etc/lynx  \
            --with-zlib             \
            --with-bzlib            \
            --with-ssl              \
            --with-screen=ncursesw  \
            --enable-locale-charset \
            --datadir=/usr/share/doc/lynx-$VERS &&
make
make install-full
chgrp -v -R root /usr/share/doc/lynx-$VERS/lynx_doc

}

rdir() {

rm -vf /usr/bin/lynx
rm -rvf /etc/lynx \
  /usr/share/doc/lynx-$VERS

}
