#!/bin/bash
NAME="lynx"
VERS="2.9.2"
LINK="https://invisible-mirror.net/archives/lynx/tarballs/lynx$VERS.tar.bz2"
UPST="https://lynx.invisible-island.net/lynx.html"
VCMD="curl -s '$UPST' | grep 'stable release is' | cut -d' ' -f9 | cut -d';' -f1"
DEPS=""


idir() {

./configure --prefix=/usr           \
            --sysconfdir=/etc/lynx  \
            --with-zlib             \
            --with-bzlib            \
            --with-ssl              \
            --with-screen=ncursesw  \
            --enable-locale-charset \
            --datadir=/usr/share/doc/lynx-$VERS &&
make
make install-full
chgrp -v -R root /usr/share/doc/lynx-$VERS/lynx_doc

}

rdir() {

rm -vf /usr/bin/lynx
rm -rvf /etc/lynx \
  /usr/share/doc/lynx-$VERS

}
