#!/bin/bash
NAME="lz4"
VERS="1.10.0"
LINK="https://github.com/lz4/lz4/releases/download/v$VERS/lz4-$VERS.tar.gz"
UPST="https://github.com/lz4/lz4.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1"
DEPS=""


idir() {

make BUILD_STATIC=no PREFIX=/usr
make BUILD_STATIC=no PREFIX=/usr install

make clean

CC="gcc -m32" make BUILD_STATIC=no
make BUILD_STATIC=no PREFIX=/usr LIBDIR=/usr/lib32 DESTDIR=$RIDDEST install &&
cp -a $RIDDEST/usr/lib32/* /usr/lib32/

}

rdir() {

rm -vf \
    /usr/bin/lz4{,c,cat}    \
    /usr/bin/unlz4          \
    /usr/lib{,32}/liblz4.so*

}
