#!/bin/bash
NAME="lzip"
VERS="1.24.1"
LINK="http://download.savannah.gnu.org/releases/lzip/lzip-$VERS.tar.gz"
UPST="http://download.savannah.gnu.org/releases/lzip/?C=M&O=D"
SELE="tr.o:nth-child(15) > td:nth-child(1) > a:nth-child(1)"
DEPS=""


idir() {

cm

}

rdir() {

echo "not implemented"

}
