#!/bin/bash
NAME="lzip"
VERS="1.24.1"
LINK="http://download.savannah.gnu.org/releases/lzip/lzip-$VERS.tar.gz"
UPST="http://download.savannah.gnu.org/releases/lzip/?C=M&O=D"
VCMD="curl -s '$UPST' | grep lzip- | head -n1 | cut -d- -f2 | cut -d. -f1-3"
DEPS=""


idir() {

cm

}

rdir() {

echo "not implemented"

}
