#!/bin/bash
NAME="make-ca"
VERS=1.14
LINK="https://github.com/lfs-book/$NAME/archive/v$VERS/$NAME-$VERS.tar.gz"
DEPS="p11-kit libtasn1 nss"


IDIR=$(cat <<~fin.

cat >> make-ca << "EOF"
ln -svf /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
EOF

make install &&
install -vdm755 /etc/ssl/local

/usr/sbin/make-ca -g

~fin.
)

RDIR=$(cat <<EOF

rm -rvf /usr/bin/make-ca            \
        /etc/ssl/{certs,local}      \
        /etc/pki/{nssdb,anchors,tls/{certs,java}}

EOF
)

UDIR=$(cat <<EOF
EOF
)
