#!/bin/bash
NAME="man-pages"
VERS="6.9.1"
LINK="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$VERS.tar.xz"
UPST="https://repology.org/project/manpages/information"
DEPS=""


idir() {

rm -v man3/crypt*
make prefix=/usr install

}

rdir() {

echo not implemented

}


