#!/bin/bash
NAME="man-pages"
VERS="${!NAME}_version"
LINK="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

rm -v man3/crypt*
make prefix=/usr install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
