#!/bin/bash
NAME="man_db"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK=""
DEPS=""


IDIR=$(cat << '~fin.'

cm  --docdir=/tmp/rid/trash         \
    --sysconfdir=/etc               \
    --disable-setuid                \
    --enable-cache-owner=bin        \
    --with-browser=/usr/bin/lynx    \
    --with-vgrind=/usr/bin/vgrind   \
    --with-grap=/usr/bin/grap       \
    --with-systemdtmpfilesdir=      \
    --with-systemdsystemunitdir=

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
