#!/bin/bash
NAME="man_pages"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$VERS.tar.xz"
UPST="https://repology.org/project/manpages/information"
DEPS=""


IDIR=$(cat << '~fin.'

rm -v man3/crypt*
make prefix=/usr install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
