#!/bin/bash
NAME="markupsafe"
VERS="3.0.2"
LINK="https://pypi.org/packages/source/M/MarkupSafe/markupsafe-$VERS.tar.gz"
UPST="https://github.com/pallets/markupsafe.git"
DEPS=""


idir() {

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --find-links dist Markupsafe

}

rdir() {

PV=$(gv python)
PV=${PV%.*}

rm -rvf /usr/lib/python$PV/site-packages/MarkupSafe-$VERS.dist-info

}
