#!/bin/bash
NAME="mesa"
VERS="24.3.0-rc2"
LINK="https://mesa.freedesktop.org/archive/mesa-$VERS.tar.xz"
UPST="https://archive.mesa3d.org/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > a:nth-child(1)"
DEPS="libdrm libelf libx11 libxcb libxext libxfixes libxrandr libxshmfence libxxf86vm xcb-util-keysyms xorgproto mako pyyaml libglvnd libva libvdpau libvdpau-va-gl"
# the deps need more testing

IDIR=$(cat << '~fin.'

mn \
    -D platforms=x11            \
    -D vulkan-drivers=""        \
    -D valgrind=disabled        \
    -D libunwind=disabled       \
    -D glvnd=enabled            \
    -D llvm=disabled            \
    -D gallium-drivers=nouveau  \
    -D video-codecs=all         

# # I don't need 32-bit mesa because I use nvidia, so I've commented the below out.
# rm -rvf  ridbuild
# mkdir -v ridbuild
# cd       ridbuild
#
# CC="gcc -m32" CXX="g++ -m32"                 \
# PKG_CONFIG_PATH=/usr/lib32/pkgconfig         \
# meson setup                                  \
#     --prefix=/usr                            \
#     --libdir=/usr/lib32                      \
#     --buildtype=release                      \
#     --strip                                  \
#     -D platforms=x11                         \
#     -D gallium-drivers=nouveau               \
#     -D vulkan-drivers=""                     \
#     -D valgrind=disabled                     \
#     -D libunwind=disabled                    \
#     -D glvnd=enabled                         \
#     -D video-codecs=all                      \
#     -D llvm=disabled                         \
#     .. &&
#     sed -i 's/\/usr\/lib\//\/usr\/lib32\//g' ./build.ninja &&
#
# ninja
#
# DESTDIR=$PWD/DESTDIR ninja install
# cp -vr DESTDIR/usr/lib32/* /usr/lib32
# if [ -d DESTDIR/usr/share/vulkan ]; then
#      cp -vr DESTDIR/usr/share/vulkan /usr/share
# fi
# rm -rf DESTDIR
# ldconfig

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
