#!/bin/bash
NAME="meson"
VERS="1.6.0"
LINK="https://github.com/mesonbuild/meson/releases/download/$VERS/meson-$VERS.tar.gz"
UPST="https://github.com/mesonbuild/meson.git"
DEPS="python"


idir() {

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links dist meson
install -vDm644 data/shell-completions/bash/meson /usr/share/bash-completion/completions/meson

}

rdir() {

PV=$(gv python)
PV=${PV%.*}

rm -vf  /usr/bin/meson  \
    /usr/share/bash-completion/completions/meson

rm -rvf /usr/lib/python$PV/site-packages/mesonbuild    \
        /usr/lib/python$PV/site-packages/meson-$VERS.dist-info

    }
