#!/bin/bash
NAME="mkfontscale"
VERS="1.2.3"
LINK="https://www.x.org/pub/individual/app/mkfontscale-$VERS.tar.xz"
DEPS="freetype2 util-macros xorgproto"
UPST="https://gitlab.freedesktop.org/xorg/app/mkfontscale/-/tags"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
