#!/bin/bash
NAME="mkfontscale"
VERS="1.2.3"
LINK="https://www.x.org/pub/individual/app/mkfontscale-$VERS.tar.xz"
DEPS="freetype2 util-macros xorgproto"
UPST="https://gitlab.freedesktop.org/xorg/app/mkfontscale/-/tags"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


