#!/bin/bash
NAME="mpc"
VERS=1.3.1
LINK="https://ftp.gnu.org/gnu/mpc/mpc-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/tmp/rid/trash

make
make install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libmpc.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
