#!/bin/bash
NAME="mpc"
VERS="1.3.1"
LINK="https://ftp.gnu.org/gnu/mpc/mpc-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/mpc/?C=M;O=D"
DEPS=""


idir() {

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/tmp/rid/trash

make
make install

}

rdir() {

rm -vf /usr/lib/libmpc.so*

}
