#!/bin/bash
NAME="mpfr"
VERS="4.2.1"
LINK="https://ftp.gnu.org/gnu/mpfr/mpfr-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/mpfr/?C=M;O=D"
DEPS=""


idir() {

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/tmp/rid/trash

make
make install

}

rdir() {

rm -vf /usr/lib/libmpfr.so*

}
