#!/bin/bash
NAME="mpfr"
VERS="4.2.1"
LINK="https://ftp.gnu.org/gnu/mpfr/mpfr-$VERS.tar.xz"
UPST="https://gitlab.inria.fr/mpfr/mpfr.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 bug_compound-root | head -n1"
DEPS=""


idir() {

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/tmp/rid/trash

make
make install

}

rdir() {

rm -vf /usr/lib/libmpfr.so*

}
