#!/bin/bash
NAME="mpv"
DESC="A wonderful media player"
VERS="0.39.0"
LINK="https://github.com/mpv-player/mpv/archive/v$VERS/mpv-$VERS.tar.gz"
UPST="https://github.com/mpv-player/mpv.git"
DEPS="alsa-lib ffmpeg libass libplacebo mesa pulseaudio libjpeg-turbo libva libvdpau luajit uchardet vulkan-loader"


idir() {

sed -i 's/AV_OPT_TYPE_CHANNEL_LAYOUT/AV_OPT_TYPE_CHLAYOUT/' filters/f_lavfi.c

mn -D x11=enabled                     \
   -D wayland=disabled                \
   -D egl-wayland=disabled            \
   -D libmpv=true                     \
   -D tests=false                     \
   -D cplugins=enabled                \
   -D lua=enabled                     \
   -D build-date=false                \
   -D fuzzers=false                   \
   -D ta-leak-report=false            \
   -D cplayer=true                    \
   -D javascript=disabled             \
   -D dvbin=disabled                  \
   -D libarchive=disabled             \
   -D libbluray=disabled              \
   -D cdda=disabled                   \
   -D dvdnav=disabled                 \
   -D win32-threads=disabled          \
   -D win32-smtc=disabled             \
   -D macos-10-15-4-features=disabled \
   -D macos-11-features=disabled      \
   -D macos-11-3-features=disabled    \
   -D macos-12-features=disabled      \
   -D macos-cocoa-cb=disabled         \
   -D macos-media-player=disabled     \
   -D macos-touchbar=disabled         \
   -D swift-build=disabled

gtk-update-icon-cache -qtf /usr/share/icons/hicolor || echo "skipping gtk-update-icon-cache"
update-desktop-database -q

}

rdir() {

echo not implemented

}
