#!/bin/bash
NAME="mpv-mpris"
VERS="1.1"
LINK="https://github.com/hoyon/mpv-mpris/archive/refs/tags/$VERS.tar.gz"
UPST="https://github.com/hoyon/mpv-mpris.git"
DEPS="mpv"


idir() {

make
make PREFIX=/usr install

echo "/etc/mpv/scripts/mpris.so has been installed"
echo "this may cause issues"

}

rdir() {

rm -rvf /usr/lib/mpv-mpris \
        /etc/mpv/scripts/mpris.so

}
