#!/bin/bash
NAME="mpv-mpris"
VERS=1.1
LINK="https://github.com/hoyon/$NAME/archive/refs/tags/$VERS.tar.gz"
DEPS="mpv"


IDIR=$(cat <<EOF

make
make PREFIX=/usr install

echo "/etc/mpv/scripts/mpris.so has been installed"
echo "this may cause issues"

EOF
)

RDIR=$(cat <<EOF

rm -rvf /usr/lib/mpv-mpris \
        /etc/mpv/scripts/mpris.so

EOF
)

UDIR=$(cat <<EOF
EOF
)
