#!/bin/bash
NAME="mtdev"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://bitmath.org/code/mtdev/mtdev-$VERS.tar.bz2"
UPST="https://bitmath.se/org/code/mtdev"
SELE="body > table:nth-child(2) > tbody > tr:nth-child(3) > td:nth-child(2) > h4:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/mtdev-test \
        /usr/lib/libmtdev.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
