#!/bin/bash
NAME="mtdev"
VERS="${!NAME}_version"
LINK="https://bitmath.org/code/mtdev/mtdev-$VERS.tar.bz2"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/mtdev-test \
        /usr/lib/libmtdev.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
