#!/bin/bash
NAME="mtdev"
VERS="1.1.7"
LINK="https://bitmath.org/code/mtdev/mtdev-$VERS.tar.bz2"
UPST="http://bitmath.org/git/mtdev.git "
DEPS=""


idir() {

cm

}

rdir() {

rm -vf  /usr/bin/mtdev-test \
        /usr/lib/libmtdev.*

    }
