#!/bin/bash
NAME="nettle"
VERS="3.10"
LINK="https://ftp.gnu.org/gnu/nettle/nettle-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/nettle/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm
chmod -v 755 /usr/lib/lib{hogweed,nettle}.so

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf \
    /usr/bin/nettle-hash        \
    /usr/bin/nettle-lfib-stream \
    /usr/bin/nettle-pbkdf2      \
    /usr/bin/pkcs1-conv         \
    /usr/bin/sexp-conv          \
    /usr/lib/libhogweed.so*     \
    /usr/lib/libnettle.so*

rm -rvf /usr/include/nettle

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
