#!/bin/bash
NAME="nettle"
VERS="3.10"
LINK="https://ftp.gnu.org/gnu/nettle/nettle-$VERS.tar.gz"
UPST="https://git.lysator.liu.se/nettle/nettle.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d_ -f2"
DEPS=""


idir() {

cm
chmod -v 755 /usr/lib/lib{hogweed,nettle}.so

}

rdir() {

rm -vf \
    /usr/bin/nettle-hash        \
    /usr/bin/nettle-lfib-stream \
    /usr/bin/nettle-pbkdf2      \
    /usr/bin/pkcs1-conv         \
    /usr/bin/sexp-conv          \
    /usr/lib/libhogweed.so*     \
    /usr/lib/libnettle.so*

rm -rvf /usr/include/nettle

}
