#!/bin/bash
NAME="nghttp2"
VERS="1.64.0"
LINK="https://github.com/$NAME/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
UPST="https://github.com/$NAME/$NAME.git"
DEPS="libxml2"


idir() {

cm --enable-lib-only \
   --docdir=/tmp/rid/trash/

}

rdir() {

echo not implemented

}
