#!/bin/bash
NAME="nghttp2"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/$NAME/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
DEPS="libxml2"


IDIR=$(cat << '~fin.'

cm --enable-lib-only \
   --docdir=/tmp/rid/trash/

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
