#!/bin/bash
NAME="nightdrive"
VERS="9999"
DEPS="git wget mpv xwinwrap"


idir() {

mkdir -pv /dots && cd /dots

rm -rvf $H/.config
rm -rvf nightdrive

git clone https://github.com/toxikuu/nightdrive
chown -Rv $TU:$TU nightdrive 

[ -e $H/wallpapers/nightdrive.mp4 ] ||
{
    wget https://files.catbox.moe/ia3b5p.mp4 &&
    mv -vf ia3b5p.mp4 $H/wallpapers/nightdrive.mp4
}

ln -sfv config $H/.config
echo "You should now set up extra files manually. (/dots/nightdrive/extra)"

}

rdir() {

rm -rvf $H/.config  \
        /dots/nightdrive
echo "If you set up any files in /dots/nightdrive/extra, you're responsible for handling the removal of those."

}
