#!/bin/bash
NAME="nightdrive"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK=""
DEPS="git wget mpv xwinwrap"


IDIR=$(cat << '~fin.'

mkdir -pv /dots && cd /dots

rm -rvf $H/.config
rm -rvf nightdrive

git clone https://github.com/toxikuu/nightdrive
chown -Rv $TARGET_USER:$TARGET_USER nightdrive 

[ -e $H/wallpapers/nightdrive.mp4 ] ||
{
    wget https://files.catbox.moe/ia3b5p.mp4 &&
    mv -vf ia3b5p.mp4 $H/wallpapers/nightdrive.mp4
}

ln -sfv config $H/.config
echo "You should now set up extra files manually. (/dots/nightdrive/extra)"

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf $H/.config  \
        /dots/nightdrive
echo "If you set up any files in /dots/nightdrive/extra, you're responsible for handling the removal of those."

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
