#!/bin/bash
NAME="nihil"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK=""
DEPS="git iosevka obsidian vesktop xdotool i3 alacritty"


IDIR=$(cat << '~fin.'

cd /dots
git clone https://github.com/toxikuu/nihil.git && cd nihil
chown -vR $TARGET_USER:$TARGET_USER /dots/nihil

rm -rvf $H/.config
ln -svf /dots/nihil/config $H/.config

{ [ -e $H/Vault/.obsidian/themes ] && cp -rvf extra/Obsidian/Nihil $H/Vault/.obsidian/themes/ } || true

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf \
    $H/.config          \
    $H/.xinitrc         \
    $H/.bashrc          \
    $H/Wallpapers       \
    $H/.bash_profile

# i need to add some commands to move .bak back

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
