#!/bin/bash
NAME="nihil"
VERS="9999"
DEPS="git iosevka obsidian vesktop xdotool i3 alacritty"


idir() {

cd /dots
git clone https://github.com/toxikuu/nihil.git && cd nihil
chown -vR $TU:$TU /dots/nihil

rm -rvf $H/.config
ln -svf /dots/nihil/config $H/.config

{ [ -e $H/Vault/.obsidian/themes ] && cp -rvf extra/Obsidian/Nihil $H/Vault/.obsidian/themes/ ; } || :

}

rdir() {

rm -rvf \
$H/.config          \
$H/.xinitrc         \
$H/.bashrc          \
$H/Wallpapers       \
$H/.bash_profile

# i need to add some commands to move .bak back
}
