#!/bin/bash
NAME="ninja"
VERS="1.12.1"
LINK="https://github.com/ninja-build/ninja/archive/v$VERS/ninja-$VERS.tar.gz"
UPST="https://github.com/ninja-build/ninja.git"
VCMD="git ls-remote --tags 'https://github.com/ninja-build/ninja.git' | sed 's:.*/::' | sort -V | tail -n1"
DEPS="python"


idir() {

python3 configure.py --bootstrap
install -vm755 ninja /usr/bin/
install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja

}

rdir() {

rm -vf  ninja   \
        /usr/share/bash-completion/completions/ninja

    }
