#!/bin/bash
NAME="ninja"
VERS="${!NAME}_version"
LINK="https://github.com/ninja-build/ninja/archive/v$VERS/ninja-$VERS.tar.gz"
DEPS="python"


IDIR=$(cat << '~fin.'

python3 configure.py --bootstrap
install -vm755 ninja /usr/bin/
install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  ninja   \
        /usr/share/bash-completion/completions/ninja

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
