#!/bin/bash
NAME="nodejs"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK=""
DEPS="pnpm"


IDIR=$(cat << '~fin.'

pnpm env use -g latest

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
