#!/bin/bash
NAME="nodejs"
VERS="${!NAME}_version"
LINK=""
DEPS="pnpm"


IDIR=$(cat << '~fin.'

pnpm env use -g latest

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
