#!/bin/bash
NAME="nspr"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://archive.mozilla.org/pub/nspr/releases/v$VERS/src/nspr-$VERS.tar.gz"
UPST="https://repology.org/project/nspr/information"
DEPS=""


IDIR=$(cat << '~fin.'

cd nspr &&

sed -i '/^RELEASE/s|^|#|' pr/src/misc/Makefile.in &&
sed -i 's|$(LIBRARY) ||'  config/rules.mk         &&

cm --with-mozilla    \
   --with-pthreads   \
   $([ $(uname -m) = x86_64 ] && echo --enable-64bit)

32cm --with-mozilla  \
     --with-pthreads \
     --disable-64bit

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
