#!/bin/bash
NAME="nspr"
VERS=4.35
LINK="https://archive.mozilla.org/pub/nspr/releases/v$VERS/src/nspr-$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<'EOF'

cd nspr &&

sed -i '/^RELEASE/s|^|#|' pr/src/misc/Makefile.in &&
sed -i 's|$(LIBRARY) ||'  config/rules.mk         &&

cm --with-mozilla    \
   --with-pthreads   \
   $([ $(uname -m) = x86_64 ] && echo --enable-64bit)

pwd
make distclean

32cm --with-mozilla  \
     --with-pthreads \
     --disable-64bit

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
