#!/bin/bash
NAME="nspr"
VERS="4.36"
LINK="https://archive.mozilla.org/pub/nspr/releases/v$VERS/src/nspr-$VERS.tar.gz"
UPST="https://gitlab.archlinux.org/archlinux/packaging/packages/nspr.git" # probably unreliable
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | cut -d- -f1 | sort -V | tail -n1"
DEPS=""


idir() {

cd nspr &&

sed -i '/^RELEASE/s|^|#|' pr/src/misc/Makefile.in &&
sed -i 's|$(LIBRARY) ||'  config/rules.mk         &&

cm --with-mozilla    \
   --with-pthreads   \
   $([ $(uname -m) = x86_64 ] && echo --enable-64bit)

32cm --with-mozilla  \
     --with-pthreads \
     --disable-64bit

 }

 rdir() {

echo not implemented

}
