#!/bin/bash
NAME="nvchad"
VERS="9999"
LINK=""
DEPS="nvim git"


idir() {

git clone https://github.com/NvChad/starter /root/.config/nvim
rm -rvf $H/.config/nvim && cp -rvf /root/.config/nvim $H/.config/nvim
chown -vR $TARGET_USER:$TARGET_USER $H/.config/nvim

}

rdir() {

rm -rvf {/root,$H}/.config/nvim \
        {/root,$H}/.local/{state,share}/nvim

        }


