#!/bin/bash
NAME="nvidia"
VERS="560.35.03"
LINK=""
DOWN="https://us.download.nvidia.com/XFree86/Linux-x86_64/$VERS/NVIDIA-Linux-x86_64-$VERS.run"
UPST="https://github.com/NVIDIA/nvidia-installer/tags"
DEPS=""


IDIR=$(cat << '~fin.'

chmod +x "$RIDSOURCES"/NVIDIA-Linux-x86_64-$VERS.run
kver=$(realpath /usr/src/linux | cut -d- -f2-)
echo "Detected kernel version '$kver'"

"$RIDSOURCES"/NVIDIA-Linux-x86_64-$VERS.run --extract-only || die "Failed to extract NVIDIA's .run"
cd NVIDIA-Linux-x86_64-$VERS

./nvidia-installer                              \
    --silent                                    \
    --ui=none                                   \
    --no-rpms                                   \
    --no-x-check                                \
    --no-peermem                                \
    --no-systemd                                \
    --no-abi-note                               \
    --no-questions                              \
    --x-prefix=/usr                             \
    --disable-nouveau                           \
    --skip-module-load                          \
    --no-nouveau-check                          \
    --no-ncurses-color                          \
    --force-selinux=no                          \
    --kernel-name=$kver                         \
    --run-nvidia-xconfig                        \
    --no-install-libglvnd                       \
    --no-rebuild-initramfs                      \
    --install-compat32-libs                     \
    --kernel-module-type=open                   \
    --no-check-for-alternate-installs           \
    --kernel-source-path=/usr/src/linux         \
    --documentation-prefix=/tmp/rid/trash       \
    --allow-installation-with-running-driver    \
    --kernel-install-path=/lib/modules/$kver/kernel/drivers/video ||
die "NVIDIA's .run failed"

echo "You should reboot for the nvidia drivers to take effect" >&2

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
