#!/bin/bash
NAME="nvidia"
VERS=565.57.01
LINK=""
DEPS=""


IDIR=$(cat << '~fin.'

[ -f "$RIDSOURCES"/NVIDIA-Linux-x86_64-$VERS.run ] ||
raw https://us.download.nvidia.com/XFree86/Linux-x86_64/$VERS/NVIDIA-Linux-x86_64-$VERS.run

chmod +x "$RIDSOURCES"/NVIDIA-Linux-x86_64-$VERS.run
kver=$(realpath /usr/src/linux | cut -d- -f2-)
echo "Detected kernel version '$kver'"

"$RIDSOURCES"/NVIDIA-Linux-x86_64-$VERS.run --extract-only || die "Failed to extract NVIDIA's .run"
cd NVIDIA-Linux-x86_64-$VERS

# fix currently necessary for 6.11 kernels
sed -i 's/drm_fbdev_generic_setup/drm_fbdev_ttm_setup/g' kernel{,-open}/conftest.sh kernel/nvidia-drm/nvidia-drm-{drv.c,sources.mk} || die "Sed failed"

./nvidia-installer                              \
    --silent                                    \
    --ui=none                                   \
    --no-rpms                                   \
    --no-x-check                                \
    --no-peermem                                \
    --no-systemd                                \
    --no-questions                              \
    --x-prefix=/usr                             \
    --no-nouveau-check                          \
    --no-ncurses-color                          \
    --disable-nouveau                           \
    --force-selinux=no                          \
    --kernel-name=$kver                         \
    --run-nvidia-xconfig                        \
    --no-install-libglvnd                       \
    --no-rebuild-initramfs                      \
    --kernel-module-type=proprietary            \
    --no-check-for-alternate-installs           \
    --kernel-source-path=/usr/src/linux         \
    --documentation-prefix=/tmp/rid/trash       \
    --allow-installation-with-running-driver    \
    --kernel-install-path=/lib/modules/$kver/kernel/drivers/video ||
die "NVIDIA's .run failed"

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
