#!/bin/bash
NAME="nvim"
VERS="9999"
LINK="https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz"
DEPS=""

# this is a binary install because im lazy and dont want to resolve nvim dependencies
idir() {

mo bin/nvim   /usr/bin/nvim
mo lib/nvim   /usr/lib/nvim
mo share/nvim /usr/share/nvim

}

rdir() {

rm -vf /usr/bin/nvim
rm -rvf /usr/{lib,share}/nvim

}


