#!/bin/bash
NAME="obsidian"
VERS="1.7.7"
LINK="https://github.com/obsidianmd/obsidian-releases/releases/download/v$VERS/obsidian-$VERS.tar.gz"
UPST="https://github.com/obsidianmd/obsidian-releases.git"
DEPS=""


idir() {

mkdir -pv      /usr/lib/obsidian
cd     ..
mo $NAME-$VERS /usr/lib/obsidian

cat << EOF > /usr/share/applications/obsidian.desktop
[Desktop Entry]
Name=Obsidian
Exec=/usr/lib/obsidian/obsidian
Terminal=false
Type=Application
Icon=obsidian
StartupWMClass=obsidian
X-AppImage-Version=1.6.7
Comment=Markdown Note Application
MimeType=x-scheme-handler/obsidian;
Categories=Office;
Keywords=markdown;md;notes;
EOF

}

rdir() {

echo not implemented

}
