#!/bin/bash
NAME="olympus"
VERS="${!NAME}_version"
LINK=""
DEPS="unzip xdg-utils desktop-file-utils"


IDIR=$(cat << '~fin.'

raw 'https://dev.azure.com/EverestAPI/Olympus/_apis/build/builds/4338/artifacts?artifactName=linux.main&api-version=5.0&%24format=zip'

mo '"$RIDSOURCES"/artifacts?artifactName=linux.main&api-version=5.0&%24format=zip' "$RIDSOURCES"/olympus.zip

cp -vf "$RIDSOURCES"/olympus.zip .

unzip olympus.zip && cd   linux.main
unzip    dist.zip && rm -vf dist.zip

yes "y" | ./install.sh

mo /usr/share/applications/{O,o}lympus.desktop

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
