#!/bin/bash
NAME="olympus"
VERS="9999"
LINK=""
DOWN='https://dev.azure.com/EverestAPI/Olympus/_apis/build/builds/4338/artifacts?artifactName=linux.main&api-version=5.0&%24format=zip'
DEPS="unzip xdg-utils desktop-file-utils"


IDIR=$(cat << '~fin.'

ln -sfv "$RIDSOURCES"/'artifacts?artifactName=linux.main&api-version=5.0&%24format=zip' "$RIDSOURCES"/olympus.zip
cp -vf "$RIDSOURCES"/olympus.zip .

unzip olympus.zip && cd   linux.main    &&
unzip    dist.zip && rm -vf dist.zip    &&
cd .. && mo linux.main /usr/lib/olympus

cd /usr/lib/olympus
yes "y" | ./install.sh

mo /usr/share/applications/{O,o}lympus.desktop

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/olympus
rm -vf /usr/bin/olympus

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
