#!/bin/bash
NAME="opus"
VERS="1.5.2"
LINK="https://github.com/xiph/opus/releases/download/v$VERS/opus-$VERS.tar.gz"
UPST="https://github.com/xiph/opus.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | tail -n1"
DEPS=""


idir() {

mn -D docdir=/tmp/rid/trash
32mn

}

rdir() {

echo not implemented

}
