#!/bin/bash
NAME="opus-tools"
VERS="0.2"
LINK="https://ftp.osuosl.org/pub/xiph/releases/opus/opus-tools-$VERS.tar.gz"
UPST="https://github.com/xiph/opus-tools.git"
DEPS="flac libogg opus libopusenc"


idir() {

cm

}

rdir() {

echo "not implemented"

}
