#!/bin/bash
NAME="opusfile"
VERS="0.12"
LINK="https://ftp.osuosl.org/pub/xiph/releases/opus/opusfile-$VERS.tar.gz"
UPST="https://github.com/xiph/opusfile.git"
DEPS="openssl opus"


idir() {

cm

}

rdir() {

echo "not implemented"

}
