#!/bin/bash
NAME="opus"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/xiph/opus/releases/download/v$VERS/opus-$VERS.tar.gz"
UPST="https://github.com/xiph/opus/releases/latest"
DEPS=""


IDIR=$(cat << '~fin.'

mn -D docdir=/tmp/rid/trash
32mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
