#!/bin/bash
NAME="p11-kit"
VERS="0.25.5"
LINK="https://github.com/p11-glue/p11-kit/releases/download/$VERS/p11-kit-$VERS.tar.xz"
UPST="https://github.com/p11-glue/p11-kit/tags"
DEPS="libtasn1 nss"


idir() {

sed '20,$ d' -i trust/trust-extract-compat &&

cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

mn   -D trust_paths=/etc/pki/anchors

ln -sfv /usr/libexec/p11-kit/trust-extract-compat \
        /usr/bin/update-ca-certificates

32mn -D trust_paths=/etc/pki/anchors

ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so
ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib32/libnssckbi.so

}

rdir() {

echo not implemented

}


