#!/bin/bash
NAME="pango"
VERS="1.55.0"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/pango/$ver/pango-$VERS.tar.xz"
UPST="https://github.com/GNOME/pango.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 1.90 | head -n1"
DEPS="fontconfig freetype2 fribidi glib cairo libx11 libxrender libxft"


idir() {

mn --wrap-mode=nofallback

}

rdir() {

echo not implemented

}
