#!/bin/bash
NAME="pango"
VERS="${NAME}_version"; VERS="${!VERS}"
ver="${VERS%.*}"
LINK="https://download.gnome.org/sources/pango/$ver/pango-$VERS.tar.xz"
DEPS="fontconfig freetype2 fribidi glib cairo xorg-libraries"  # cairo built after harfbuzz


IDIR=$(cat << '~fin.'

mn --wrap-mode=nofallback

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
