#!/bin/bash
NAME="pango"
VERS="1.55.4"
ver="${VERS%.*}"
LINK="https://github.com/GNOME/pango/archive/refs/tags/$VERS.tar.gz"
UPST="https://github.com/GNOME/pango.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 1.90 | head -n1"
DEPS="fontconfig freetype2 fribidi glib cairo libx11 libxrender libxft"


idir() {

mn --wrap-mode=nofallback

}

rdir() {

echo not implemented

}
