#!/bin/bash
NAME="patch"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/patch/patch-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/patch

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
