#!/bin/bash
NAME="patch"
VERS="2.7.6"
LINK="https://ftp.gnu.org/gnu/patch/patch-$VERS.tar.xz"
UPST="https://git.savannah.gnu.org/git/patch.git"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /usr/bin/patch

}
