#!/bin/bash
NAME="pciutils"
VERS="3.13.0"
LINK="https://mj.ucw.cz/download/linux/pci/pciutils-$VERS.tar.gz"
UPST="https://github.com/pciutils/pciutils.git"
DEPS=""


idir() {

sed -r '/INSTALL.*(PCI_IDS|update-pciids)/d' \
    -i Makefile

make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes

make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes                 \
     install install-lib        &&

chmod -v 755 /usr/lib/libpci.so

}

rdir() {

rm -rvf /usr/bin/lspci   \
        /usr/bin/pcilmr  \
        /usr/bin/setpci  \
        /usr/include/pci \
        /usr/lib/libpci.so*

    }
