#!/bin/bash
NAME="pciutils"
VERS="3.13.0"
LINK="https://mj.ucw.cz/download/linux/pci/pciutils-$VERS.tar.gz"
UPST="https://mj.ucw.cz/download/linux/pci/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(7) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

sed -r '/INSTALL.*(PCI_IDS|update-pciids)/d' \
    -i Makefile

make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes

make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes                 \
     install install-lib        &&

chmod -v 755 /usr/lib/libpci.so

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/bin/lspci   \
        /usr/bin/pcilmr  \
        /usr/bin/setpci  \
        /usr/include/pci \
        /usr/lib/libpci.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
