#!/bin/bash
NAME="pcre2"
VERS="10.44"
LINK="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-$VERS/pcre2-$VERS.tar.bz2"
UPST="https://github.com/PCRE2Project/pcre2.git"
DEPS=""


idir() {

cm \
    --docdir=/tmp/rid/trash         \
    --enable-unicode                \
    --enable-jit                    \
    --enable-pcre2-16               \
    --enable-pcre2-32               \
    --enable-pcre2grep-libz         \
    --enable-pcre2grep-libbz2       \
    --enable-pcre2test-libreadline

32cm \
    --enable-unicode                \
    --enable-jit                    \
    --enable-pcre2-16               \
    --enable-pcre2-32               \
    --enable-pcre2grep-libz         \
    --enable-pcre2grep-libbz2       \
    --enable-pcre2test-libreadline

}

rdir() {

echo not implemented

}
