#!/bin/bash
NAME="picom"
VERS="12.4"
LINK="https://github.com/yshui/picom/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/yshui/picom/tags"
DEPS="dbus2 libepoxy xcb-util-image xcb-util-renderutil pixman libconfig pcre2 libev uthash"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
