#!/bin/bash
NAME="picom"
VERS=12.1
LINK="https://github.com/yshui/picom/archive/refs/tags/v$VERS.tar.gz"
DEPS="xorg-libraries pixman libconfig pcre2 libev uthash"  # INCOMPLETE


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
