#!/bin/bash
NAME="pixman"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/releases/individual/lib/pixman-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/pixman/pixman/-/tags"
DEPS=""


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/pixman-1
rm -vf /usr/lib/libpixman-1.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
