#!/bin/bash
NAME="pixman"
VERS="0.44.0"
LINK="https://www.x.org/releases/individual/lib/pixman-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/pixman/pixman.git"
DEPS=""


idir() {

mn

}

rdir() {

rm -rvf /usr/include/pixman-1
rm -vf /usr/lib/libpixman-1.*

}
