#!/bin/bash
NAME="playerctl"
VERS=2.4.1
LINK="https://github.com/altdesktop/$NAME/archive/refs/tags/v$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<EOF

mn -D zsh-completions=false \
   -D bash-completions=true \
   -D introspection=true    \
   -D gtk-doc=false

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
