#!/bin/bash
NAME="playerctl"
VERS="2.4.1"
LINK="https://github.com/altdesktop/$NAME/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/altdesktop/$NAME/tags"
DEPS=""


IDIR=$(cat << '~fin.'

mn -D zsh-completions=false \
   -D bash-completions=true \
   -D introspection=true    \
   -D gtk-doc=false

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
