#!/bin/bash
NAME="ply"
VERS="3.11"
LINK="https://files.pythonhosted.org/packages/source/p/ply/ply-$VERS.tar.gz"
UPST="https://pypi.org/project/ply"
DEPS=""


idir() {

pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
pip3 install --no-index --find-links=dist --no-cache-dir --no-user ply

}

rdir() {

echo not implemented

}
