#!/bin/bash
NAME="pnpm"
VERS=9999
LINK=""
DEPS="curl"


IDIR=$(cat << '~fin.'

curl -fsSL https://get.pnpm.io/install.sh | env PNPM_HOME=/opt/pnpm sh -
sed -i '/# pnpm/,/# pnpm end/d' $HOME/.bashrc

if ! grep -q "# pnpm end" /etc/toxenv ; then
    cat << 'EOF' >> /etc/toxenv

    # pnpm
    export PNPM_HOME="/opt/pnpm"
    pathappend "/opt/pnpm"
    # pnpm end

EOF
fi

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /opt/pnpm

sed -i '/# pnpm/,/# pnpm end/d' /etc/toxenv

~fin.
)

UDIR=$(cat << '~fin.'
pnpm self-update

if ! grep -q "# pnpm end" /etc/toxenv ; then
    cat << 'EOF' >> /etc/toxenv

    # pnpm
    export PNPM_HOME="/opt/pnpm"
    pathappend "/opt/pnpm"
    # pnpm end

EOF
fi
~fin.
)
