#!/bin/bash
NAME="pnpm"
VERS="9.13.2" # this may not be used, but it is helpful for knowing when to self-update pnpm
UPST="https://github.com/pnpm/pnpm/releases/latest"
DEPS="curl"


idir() {

PNPM_HOME="/opt/pnpm"

curl -fsSL https://get.pnpm.io/install.sh | env PNPM_HOME="$PNPM_HOME" sh -
echo "Disregard the output of pnpm's install.sh as rid overrides it" >&2
sed -i '/# pnpm/,/# pnpm end/d' $HOME/.bashrc

if ! grep -q "# pnpm end" /etc/env ; then
    cat << EOF >> /etc/env

    # pnpm
    export PNPM_HOME="$PNPM_HOME"
    pathappend "\$PNPM_HOME"
    # pnpm end
EOF
fi

}

rdir() {

rm -rvf /opt/pnpm
sed -i '/    # pnpm/,/    # pnpm end/d' /etc/env

}

udir() {
pnpm self-update

if ! grep -q "# pnpm end" /etc/env ; then
    cat << 'EOF' >> /etc/env

    # pnpm
    export PNPM_HOME="/opt/pnpm"
    pathappend "$PNPM_HOME"
    # pnpm end
EOF
fi

}
