#!/bin/bash
NAME="polkit"
VERS=125
LINK="https://github.com/polkit-org/polkit/archive/$VERS/polkit-$VERS.tar.gz"
DEPS="duktape glib-no-gobject linux-pam elogind"


IDIR=$(cat << '~fin.'

groupadd -fg 27 polkitd &&
useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
        -g polkitd -s /bin/false polkitd

sed -i '/systemd_sysusers_dir/s/^/#/' meson.build

mn \
    -D man=false                \
    -D man=false                \
    -D session_tracking=elogind \
    -D introspection=false      \
    -D tests=false

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
