#!/bin/bash
NAME="polkit"
VERS="125"
LINK="https://github.com/polkit-org/polkit/archive/$VERS/polkit-$VERS.tar.gz"
UPST="https://github.com/polkit-org/polkit/tags"
DEPS="duktape glib linux_pam elogind"


IDIR=$(cat << '~fin.'

groupadd -fg 27 polkitd &&
useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
        -g polkitd -s /bin/false polkitd

sed -i '/systemd_sysusers_dir/s/^/#/' meson.build

mn \
    -D man=false                \
    -D tests=false              \
    -D session_tracking=elogind \
    -D introspection=false      \
    -D os_type=lfs

rm -vf /tmp/*.service
rm -rf /usr/lib/{sysusers,tmpfiles}.d

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /bin/pk{action,check,exec,ttyagent} \
        /bin/polkitd                        \
        /lib/polkit-1                       \
        /etc/polkit-1                       \
        /usr/include/polkit-1               \
        /usr/share/polkit-1

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
