#!/bin/bash
NAME="popt"
VERS="${NAME}_version"; VERS="${!VERS}"
ver="${VERS%.*}"
LINK="http://ftp.rpm.org/popt/releases/popt-$ver.x/popt-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libpopt.la \
       /usr/lib/libpopt.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
