#!/bin/bash
NAME="prism"
VERS="9.1"
DOWN="https://github.com/PrismLauncher/PrismLauncher/releases/download/$VERS/PrismLauncher-Linux-Qt6-Portable-$VERS.tar.gz"
UPST="https://github.com/PrismLauncher/PrismLauncher.git"
DEPS="krb5"


idir() {

tar xvf "$RIDSOURCES"/PrismLauncher-Linux-Qt6-Portable-$VERS.tar.gz
cd ..
mo $NAME-$VERS  /usr/src/prism
chmod 777       /usr/src/prism

cat << "EOF" > /usr/share/applications/prism.desktop
[Desktop Entry]
Type=Application
Version=$VERS
Name=PrismLauncher
Comment=Minecraft Client
Exec=/usr/src/prism/PrismLauncher
Icon=/usr/src/prism/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg
Terminal=false
Categories=Game;Application;
Keywords=minecraft;client;launcher;prism;
StartupNotify=false
EOF

}

rdir() {

rm -vf  /usr/share/applications/prism.desktop
rm -rvf /usr/src/prism

}
