#!/bin/bash
NAME="procps_ng"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-$VERS.tar.xz"
UPST="https://gitlab.com/procps-ng/procps/-/tags"
DEPS=""


IDIR=$(cat << '~fin.'

cm  --docdir=/tmp/rid/trash \
    --disable-kill

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
