#!/bin/bash
NAME="procps-ng"
VERS="4.0.4"
LINK="https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-$VERS.tar.xz"
UPST="https://gitlab.com/procps-ng/procps.git"
DEPS=""


idir() {

cm  --docdir=/tmp/rid/trash \
    --disable-kill

}

rdir() {

echo not implemented

}
