#!/bin/bash
NAME="psmisc"
VERS="23.7"
LINK="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$VERS.tar.xz"
UPST="https://gitlab.com/psmisc/psmisc/-/tags"
DEPS=""


idir() {

./configure --prefix=/usr

make
make install

}

rdir() {

pushd /usr/bin

rm -vf \
    fuser   \
    killall \
    peekfd  \
    prtstat \
    pslog   \
    pstree  \
    pstree.x11

popd

}


