#!/bin/bash
NAME="psmisc"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$VERS.tar.xz"
UPST="https://gitlab.com/psmisc/psmisc/-/tags"
DEPS=""


IDIR=$(cat << '~fin.'

./configure --prefix=/usr

make
make install

~fin.
)

RDIR=$(cat << '~fin.'

pushd /usr/bin

rm -vf \
    fuser   \
    killall \
    peekfd  \
    prtstat \
    pslog   \
    pstree  \
    pstree.x11

popd

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
