#!/bin/bash
NAME="psmisc"
VERS="${!NAME}_version"
LINK="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

./configure --prefix=/usr

make
make install

~fin.
)

RDIR=$(cat << '~fin.'

pushd /usr/bin

rm -vf \
    fuser   \
    killall \
    peekfd  \
    prtstat \
    pslog   \
    pstree  \
    pstree.x11

popd

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
