#!/bin/bash
NAME="pulseaudio"
VERS=17.0
LINK="https://www.freedesktop.org/software/$NAME/releases/$NAME-$VERS.tar.xz"
DEPS="libsndfile alsa-lib check"

# i havent been able to get 32 bit pulse to build. ill mess around with it later but for now note that this package will fail
IDIR=$(cat << '~fin.'

mn   -D database=gdbm \
     -D doxygen=false \
     -D bluez5=disabled

rm /usr/share/dbus-1/system.d/pulseaudio-system.conf

32mn -D database=gdbm \
     -D doxygen=false \
     -D bluez5=disabled

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
