#!/bin/bash
NAME="pv"
VERS="1.9.15"
LINK="http://www.ivarch.com/programs/sources/pv-$VERS.tar.gz"
UPST="https://codeberg.org/a-j-wood/pv.git"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /usr/bin/pv

}
