#!/bin/bash
NAME="python"
VERS="3.13.1"
LINK="https://www.python.org/ftp/python/$VERS/Python-$VERS.tar.xz"
UPST="https://github.com/python/cpython.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -Ev 'a|b|rc' | tail -n1" # ignores alphas, betas, and release candidates
DEPS=""


idir() {

cm \
    --enable-shared         \
    --with-system-expat     \
    --enable-optimizations  \
    --disable-option-checking

cat > /etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

}

rdir() {

rm -rvf /usr/lib/python[0-9]*   \
        /usr/bin/python         \
        /usr/bin/python[0-9]*

}

udir() {

rdir
idir

}
