#!/bin/bash
NAME="python"
VERS="3.13.0"
LINK="https://www.python.org/ftp/python/$VERS/Python-$VERS.tar.xz"
UPST="https://www.python.org/downloads"
SELE="#touchnav-wrapper > header > div > div.header-banner > div > div.download-os-macos > p > a"
DEPS=""


idir() {

cm \
    --enable-shared         \
    --with-system-expat     \
    --enable-optimizations  \
    --disable-option-checking

cat > /etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

}

rdir() {

rm -rvf /usr/lib/python[0-9]*

}

udir() {

rdir
idir

}
