#!/bin/bash
NAME="pyyaml"
VERS="6.0.2"
LINK="https://files.pythonhosted.org/packages/source/P/PyYAML/pyyaml-$VERS.tar.gz"
UPST="https://github.com/yaml/pyyaml.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -v rc | tail -n2 | head -n1"
DEPS="cython libyaml"


idir() {

pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
pip3 install --no-index --find-links=dist --no-cache-dir --no-user PyYAML

}

rdir() {

PV=$(gv python)

rm -rvf /usr/lib/python${PV}/site-packages/pyyaml*

}
