#!/bin/bash
NAME="readline"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/readline/readline-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

./configure --prefix=/usr    \
            --disable-static \
            --with-curses

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" install

make distclean
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static              \
    --with-curses

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/readline           \
        /usr/lib{,32}/libhistory.so*    \
        /usr/lib{,32}/libreadline.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
