#!/bin/bash
NAME="readline"
VERS="8.2.13"
LINK="https://ftp.gnu.org/gnu/readline/readline-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/readline/?C=M;O=D"
VCMD="curl -s '$UPST' | grep readline- | head -n2 | tail -n1 | cut -d- -f2 | cut -d. -f1-3"
DEPS=""


idir() {

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

./configure --prefix=/usr    \
            --disable-static \
            --with-curses

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" install

make distclean
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static              \
    --with-curses

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR

}

rdir() {

rm -rvf /usr/include/readline           \
        /usr/lib{,32}/libhistory.so*    \
        /usr/lib{,32}/libreadline.so*

    }
