#!/bin/bash
NAME="rid"
VERS="0.16.1"
LINK=""
DOWN="https://github.com/Toxikuu/rid/releases/download/v$VERS/rid.tar.xz"
UPST="https://github.com/toxikuu/rid/tags"
DEPS="openssl tar xz bash coreutils glibc gcc"


IDIR=$(cat << '~fin.'

if [ -e $RIDHOME/pkgs.json ]; then
  mv -vf $RIDHOME/pkgs.json /tmp/rid-pkgs.bak
fi

tar xvf "$RIDSOURCES"/rid.tar.xz -C /usr/bin
/usr/bin/rid -b

if [ -e /tmp/rid-pkgs.bak ]; then
  mv -vf /tmp/rid-pkgs.bak $RIDHOME/pkgs.json
  echo "restored pkgs.json"
fi

~fin.
)

RDIR=$(cat << '~fin.'

if [ -e $RIDHOME/pkgs.json ]; then
  mv -vf /tmp/pkgs.json /tmp/rid-pkgs.bak
fi
rm -rvf /{tmp,etc}/rid
rm -vf /bin/rid

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
