#!/bin/bash
NAME="ripgrep"
VERS="14.1.1"
LINK="https://github.com/BurntSushi/ripgrep/archive/refs/tags/$VERS.tar.gz"
UPST="https://github.com/BurntSushi/ripgrep/tags"
DEPS="rust"


idir() {

RUSTFLAGS="-C target-cpu=native" \
cargo build --release

install -v -Dm755 "target/release/rg" "/usr/bin/rg"

}

rdir() {

rm -vf \
    /usr/bin/rg                 \
    /usr/share/man/man1/rg.1    \
    /usr/share/bash-completion/completions/rg

}
