#!/bin/bash
NAME="rofi"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/davatorium/rofi/releases/download/$VERS/rofi-$VERS.tar.xz"
DEPS="pango cairo xcb-util xcb-util-wm xcb-util-cursor"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
