#!/bin/bash
NAME="rofi"
VERS="1.7.5"
LINK="https://github.com/davatorium/rofi/releases/download/$VERS/rofi-$VERS.tar.xz"
UPST="https://github.com/davatorium/rofi/tags"
DEPS="pango cairo xcb-util xcb-util-wm xcb-util-cursor"


idir() {

mn

}

rdir() {

echo not implemented

}


