#!/bin/bash
NAME="rust-bindgen"
VERS="0.69.5"
LINK="https://github.com/rust-lang/rust-bindgen/archive/v$VERS.tar.gz"
UPST="https://github.com/rust-lang/rust-bindgen/tags"
DEPS="llvm rust"  # llvm with clang


idir() {

cargo build --release
install -Dm755 target/release/bindgen /usr/bin/

}

rdir() {

rm -vf /usr/bin/bindgen

}
