#!/bin/bash
NAME="rust"  # rustup
VERS=9999
LINK=""
DEPS="curl"


IDIR=$(cat << '~fin.'

if [ "$VERS" = "9999" ]; then
    export VERS="stable"
fi

export CARGO_HOME=/opt/cargo
export RUSTUP_HOME=/opt/rustup

mkdir -pv /opt/cargo /opt/rustup
chown -Rv $USER:$USER /opt/cargo /opt/rustup

if ! command -v rustup &> /dev/null; then
    curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
fi

. /opt/cargo/env

rustup toolchain install $VERS
rustup default $VERS
rustup component add cargo clippy rustfmt

mv -v /etc/bash_completion.d/cargo /usr/share/bash-completion/completions
rm -vf /opt/cargo/env

if ! grep -q "# cargo end" /etc/toxenv ; then
    cat << EOF >> /etc/toxenv

    # cargo
    export CARGO_HOME="/opt/cargo"
    export RUSTUP_HOME="/opt/rustup"
    pathprepend "/opt/cargo/bin"
    # cargo end

EOF
fi

chgrp -R users  /opt/cargo
chmod g+s       /opt/cargo
chmod 775       /opt/cargo

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /opt/{cargo,rustup}

if grep -q "/opt/cargo/bin" /etc/profile; then
    sed -i '/\/opt\/cargo\/bin/d' /etc/profile
fi

if [ -f /usr/share/bash-completion/completions/cargo ]; then
    rm -v /usr/share/bash-completion/completions/cargo
fi

sed -i '/# cargo/,/# cargo end/d' /etc/toxenv

~fin.
)

UDIR=$(cat << '~fin.'

if [ "$VERS" = "9999" ]; then
    export VERS="stable"
fi

export CARGO_HOME=/opt/cargo
export RUSTUP_HOME=/opt/rustup
chown -R $USER:$USER /opt/cargo /opt/rustup

rustup update $VERS
rustup default $VERS
rustup component add cargo clippy rustfmt

if [ -f /etc/bash_completion.d/cargo ]; then
    mv -v /etc/bash_completion.d/cargo /usr/share/bash-completion/completions
fi

if ! grep -q "# cargo end" /etc/toxenv ; then
    cat << EOF >> /etc/toxenv

    # cargo
    export CARGO_HOME="/opt/cargo"
    export RUSTUP_HOME="/opt/rustup"
    pathprepend "/opt/cargo/bin"
    # cargo end

EOF
fi

~fin.
)
