#!/bin/bash
NAME="rust"  # rustup
VERS="1.82.0"
LINK=""
USPT="https://github.com/rust-lang/rust/releases"
DEPS="curl"


idir() {

if [ "$VERS" = "9999" ]; then
    export VERS="nightly"
fi

export CARGO_HOME=/opt/cargo
export RUSTUP_HOME=/opt/rustup

mkdir -pv $CARGO_HOME $RUSTUP_HOME

if ! command -v rustup &> /dev/null; then
    curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
fi

. $CARGO_HOME/env

rustup toolchain install $VERS  &&
rustup default $VERS            &&
rustup component add cargo clippy rustfmt ||
die "Rustup failed"

mv -vf /etc/bash_completion.d/cargo /usr/share/bash-completion/completions
rm -vf $CARGO_HOME/env

if ! grep -q "# rust end" /etc/env ; then
    cat << EOF >> /etc/env

    # rust
    export CARGO_HOME="$CARGO_HOME"
    export RUSTUP_HOME="$RUSTUP_HOME"
    pathprepend "\$CARGO_HOME/bin"
    # rust end
EOF
fi

chmod 777 "$CARGO_HOME"
chmod 755 "$RUSTUP_HOME"

}

rdir() {

rm -rvf /opt/{cargo,rustup}
rm -vf /usr/share/bash-completion/completions/cargo

sed -i '/    # rust/,/    # rust end/d' /etc/env

}
