#!/bin/bash
NAME="rust-bindgen"
VERS=0.70.1
LINK="https://github.com/rust-lang/rust-bindgen/archive/v$VERS.tar.gz"
DEPS="llvm rust"  # llvm with clang


IDIR=$(cat << '~fin.'

cargo build --release
install -Dm755 target/release/bindgen /usr/bin/

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/bindgen

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
