#!/bin/bash
NAME="sdl2"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.libsdl.org/release/SDL2-$VERS.tar.gz"
DEPS="libxkbcommon wayland-protocols xorg-libraries"


IDIR=$(cat << '~fin.'

cm
rm -v /usr/lib/libSDL2*.a
32cm
rm -v /usr/lib32/libSDL2*.a

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libSDL2.{la,so*}   \
    /usr/bin/sdl2-config
rm -rvf /usr/include/SDL2               \
    /usr/lib/cmake/SDL2

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
