#!/bin/bash
NAME="seatd"
VERS="0.9.1"
LINK="https://git.sr.ht/~kennylevinsen/seatd/archive/$VERS.tar.gz"
UPST="https://github.com/kennylevinsen/seatd/tags"
DEPS="elogind"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/seatd{,-launch} \
       /usr/lib/libseat.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
