#!/bin/bash
NAME="seatd"
VERS="0.9.1"
LINK="https://git.sr.ht/~kennylevinsen/seatd/archive/$VERS.tar.gz"
UPST="https://github.com/kennylevinsen/seatd.git"
DEPS="elogind"


idir() {

mn

}

rdir() {

rm -vf /usr/bin/seatd{,-launch} \
       /usr/lib/libseat.so*

   }
