#!/bin/bash
NAME="sessreg"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/app/sessreg-$VERS.tar.xz"
DEPS="util-macros xorgproto"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
