#!/bin/bash
NAME="setuptools"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://pypi.org/packages/source/s/setuptools/setuptools-$VERS.tar.gz"
DEPS="python"


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links dist setuptools

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/python3.13/site-packages/setuptools*       \
        /usr/lib/python3.13/site-packages/_distutils_hack   \
        /usr/lib/python3.13/site-packages/pkg_resources

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
