#!/bin/bash
NAME="setuptools"
VERS="75.5.0"
LINK="https://pypi.org/packages/source/s/setuptools/setuptools-$VERS.tar.gz"
UPST="https://pypi.org/project/setuptools/"
DEPS="python"


idir() {

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links dist setuptools

}

rdir() {

PV=$(gv python)
PV=${PV%.*}

rm -rvf /usr/lib/python$PV/site-packages/setuptools*       \
        /usr/lib/python$PV/site-packages/_distutils_hack   \
        /usr/lib/python$PV/site-packages/pkg_resources

    }


