#!/bin/bash
NAME="setxkbmap"
VERS="1.3.4"
LINK="https://www.x.org/pub/individual/app/setxkbmap-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/setxkbmap.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 setxkbmap-1_0_2 | head -n1 | cut -d- -f2"
DEPS="util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
