#!/bin/bash
NAME="setxkbmap"
VERS="1.3.4"
LINK="https://www.x.org/pub/individual/app/setxkbmap-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/setxkbmap/-/tags"
DEPS="util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


