#!/bin/bash
NAME="shared-mime-info"
VERS="2.4"
LINK="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/$VERS/shared-mime-info-$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/xdg/shared-mime-info.git"
DEPS="glib libxml2"


idir() {

mn -D update-mimedb=true

}

rdir() {

rm -rvf /usr/bin/update-mime-database \
        /usr/share/mime

    }
