#!/bin/bash
NAME="simde"
VERS="0.8.2"
LINK="https://github.com/simd-everywhere/simde/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/simd-everywhere/simde/releases/latest"
DEPS=""


idir() {

mn

}

rdir() {

echo not implemented

}
