#!/bin/bash
NAME="slop"
VERS="7.6"
LINK="https://github.com/naelstrof/slop/archive/refs/tags/v$VERS.tar.gz"
DOWN="https://gitlab.archlinux.org/archlinux/packaging/packages/slop/-/raw/main/bugfix-add-missed-header.patch"
UPST="https://github.com/naelstrof/slop/releases/latest"
DEPS="libxext libx11 mesa glew libxrender cmake glu"


idir() {

patch -Np1 -i "$RIDSOURCES"/bugfix-add-missed-header.patch
sed -e 's|CXX_STANDARD 11|CXX_STANDARD 17|g' -i CMakeLists.txt

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib .
make
make install

}

rdir() {

echo "not implemented"

}
