#!/bin/bash
NAME="spirv-tools"
VERS="1.3.296.0"
LINK="https://github.com/KhronosGroup/SPIRV-Tools/archive/vulkan-sdk-$VERS/SPIRV-Tools-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/SPIRV-Headers/tags"
DEPS="cmake spirv-headers"


IDIR=$(cat << '~fin.'


CN \
  -D SPIRV_WERROR=OFF               \
  -D SPIRV_TOOLS_BUILD_STATIC=OFF   \
  -D SPIRV-Headers_SOURCE_DIR=/usr

32CN \
  -D SPIRV_WERROR=OFF               \
  -D SPIRV_TOOLS_BUILD_STATIC=OFF   \
  -D SPIRV-Headers_SOURCE_DIR=/usr

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
