#!/bin/bash
NAME="spirv_headers"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/KhronosGroup/SPIRV-Headers/archive/vulkan-sdk-$VERS/SPIRV-Headers-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/SPIRV-Headers/tags"
DEPS="cmake"


IDIR=$(cat << '~fin.'

CN

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
