#!/bin/bash
NAME="sqlite"
VERS="3.47.0"
ver="${VERS//./}000"
UPST="https://sqlite.org/"
SELE="body > a:nth-child(9)"
LINK="https://sqlite.org/2024/sqlite-autoconf-3470000.tar.gz"
DEPS=""


idir() {

cm  \
  --enable-fts{4,5} \
  CPPFLAGS="-D SQLITE_ENABLE_COLUMN_METADATA=1 \
            -D SQLITE_ENABLE_UNLOCK_NOTIFY=1   \
            -D SQLITE_ENABLE_DBSTAT_VTAB=1     \
            -D SQLITE_SECURE_DELETE=1"

        }

        rdir() {

rm -vf /usr/lib/libsqlite3.{la,so*} \
  /usr/bin/sqlite3

}
