#!/bin/bash
NAME="startup_notification"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.freedesktop.org/software/startup-notification/releases/startup-notification-$VERS.tar.gz"
DEPS="xorg_libraries xcb_util"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/libstartup-notification-1.*    \
        /usr/include/startup-notification-1.0   \
        /usr/share/doc/startup-notification-$VERS

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
