#!/bin/bash
NAME="startup-notification"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.freedesktop.org/software/$NAME/releases/$NAME-$VERS.tar.gz"
DEPS="xorg-libraries xcb-util"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/libstartup-notification-1.*    \
        /usr/include/startup-notification-1.0   \
        /usr/share/doc/startup-notification-$VERS

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
