#!/bin/bash
NAME="startup_notification"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.freedesktop.org/software/startup-notification/releases/startup-notification-$VERS.tar.gz"
UPST="https://www.freedesktop.org/software/startup-notification/releases/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="xorg_libraries xcb_util"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/libstartup-notification-1.*    \
        /usr/include/startup-notification-1.0   \
        /usr/share/doc/startup-notification-$VERS

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
