#!/bin/bash
NAME="startup-notification"
VERS="0.12"
LINK="https://www.freedesktop.org/software/startup-notification/releases/startup-notification-$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/xdg/startup-notification"
DEPS="libx11 libxcb xcb-util"


idir() {

cm

}

rdir() {

rm -rvf /usr/lib/libstartup-notification-1.*    \
        /usr/include/startup-notification-1.0   \
        /usr/share/doc/startup-notification-$VERS

    }
