#!/bin/bash
NAME="steam"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://repo.steampowered.com/steam/pool/steam/s/steam/steam_$VERS.tar.gz"
UPST="https://repo.steampowered.com/steam/pool/steam/s/steam/?C=M&O=D"
SELE="#list > tbody > tr:nth-child(4) > td.link > a"
DEPS="@lfs alsa_plugins curl dbus_2 xorg_server libglvnd make-ca mesa nvidia vulkan_loader pulseaudio xdg_user_dirs libgpg_error"


# namespaces support in kernel is necessary
IDIR=$(cat << '~fin.'

ln -sf /usr/bin/true steamdeps
make install

echo "Make sure you have namespaces support enabled in your kernel config." >&2

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/steam          \
        /usr/share/doc/steam    \
        /usr/bin/steam          \
        /usr/bin/steamdeps

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
