#!/bin/bash
NAME="strace"
VERS="6.13"
LINK="https://github.com/strace/strace/releases/download/v$VERS/strace-$VERS.tar.xz"
UPST="https://github.com/strace/strace.git"
DEPS="glibc libunwind" # optionally, libunwind


idir() {

cm --with-libunwind

}

rdir() {

echo not implemented

}
