#!/bin/bash
NAME="strace"
VERS="6.12"
LINK="https://github.com/strace/strace/releases/download/v$VERS/strace-$VERS.tar.xz"
UPST="https://github.com/strace/strace.git"
DEPS="glibc" # optionally, libunwind


idir() {

cm --enable-bundled

}

rdir() {

echo not implemented

}
