#!/bin/bash
NAME="sudo"
VERS="1.9.16"
LINK="https://www.sudo.ws/dist/sudo-$VERS.tar.gz"
DEPS="linux-pam"
UPST="https://www.sudo.ws"
SELE=".gdoc-markdown > p:nth-child(6) > a:nth-child(2)"
NEWS="Feel free to edit the sudo and badpass prompts in $RIDMETA/sudo and rebuild. Also, the default instructions disable year 2038 support."


idir() {

NORMAL=$(tput sgr0)
BOLD=$(tput bold)
RED=$(tput setaf 1)
ITALIC=$(tput sitm)
PINK=$(tput setaf 5)
WHITE=$(tput setaf 7)

SUDO_PROMPT=" ${BOLD}[${RED}#${NORMAL}${BOLD}]${NORMAL} "
BADPASS_PROMPT="${BOLD}${ITALIC}${PINK}♡★  ✿ ,.♡${WHITE} ~ try again! ${PINK}՞ ${RED}⸝⸝${PINK}>  ̫ <${RED}⸝⸝${PINK} ՞⸜ ★ ♡⸝ ✿ ${NORMAL}"

# Here's a cute cat I found while looking for sudo prompts:
#  ╱|、
# (˚ˎ。7  
#  |、˜〵          
#  じしˍ,)ノ

    # --with-all-insults         \
    # --with-insults             \

cm  --libexecdir=/usr/lib      \
    --with-secure-path         \
    --with-editor=/bin/nvim    \
    --without-lecture          \
    --docdir=/tmp/rid/trash    \
    --disable-year2038         \
    --with-passwd-tries=9      \
    --with-timeout=30          \
    --with-password-timeout=5  \
    --with-passprompt="${SUDO_PROMPT}"  \
    --with-badpass-message="${BADPASS_PROMPT}"

cat > /etc/sudoers.d/00-sudo << "EOF"
Defaults secure_path="/usr/sbin:/usr/bin"
%wheel ALL=(ALL) ALL
EOF

cat > /etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
chmod 644 /etc/pam.d/sudo

}

rdir() {

echo not implemented

}


