#!/bin/bash
NAME="symbols"
VERS="3.2.1"
DOWN="https://github.com/ryanoasis/nerd-fonts/releases/download/v$VERS/NerdFontsSymbolsOnly.tar.xz"
UPST="https://github.com/ryanoasis/nerd-fonts/releases/latest"
DEPS="tar xz"


idir() {

cp -vf $RIDSOURCES/NerdFontsSymbolsOnly.tar.xz .

mkdir -pv Symbols
tar xvf NerdFontsSymbolsOnly.tar.xz -C Symbols
rm -vf Symbols/{LICENSE,README.md}
mo Symbols /usr/share/fonts/Symbols

}

rdir() {

rm -rvf /usr/share/fonts/Symbols

}
