#!/bin/bash
NAME="sysklogd"
VERS="2.7.0"
LINK="https://github.com/troglobit/sysklogd/releases/download/v$VERS/sysklogd-$VERS.tar.gz"
UPST="https://github.com/troglobit/sysklogd.git"
DEPS=""


idir() {

cm --sysconfdir=/etc --runstatedir=/run --without-logger

cat > /etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# Do not open any internet ports.
secure_mode 2

# End /etc/syslog.conf
EOF

}

rdir() {

rm -vf /usr/bin/sysklogd

}
