#!/bin/bash
NAME="sysklogd"
VERS=2.6.2
LINK="https://github.com/troglobit/sysklogd/releases/download/v$VERS/sysklogd-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc --runstatedir=/run --without-logger

cat > /etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# Do not open any internet ports.
secure_mode 2

# End /etc/syslog.conf
EOF

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/sysklogd

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
