#!/bin/bash
NAME="tar"
VERS="1.35"
LINK="https://ftp.gnu.org/gnu/tar/tar-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/tar/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


idir() {

export FORCE_UNSAFE_CONFIGURE=1
cm

}

rdir() {

rm -vf /usr/bin/tar

}
