#!/bin/bash
NAME="tar"
VERS="1.35"
LINK="https://ftp.gnu.org/gnu/tar/tar-$VERS.tar.xz"
UPST="https://git.savannah.gnu.org/git/tar.git"
DEPS=""


idir() {

export FORCE_UNSAFE_CONFIGURE=1
cm

}

rdir() {

rm -vf /usr/bin/tar

}
