#!/bin/bash
NAME="tar"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/tar/tar-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/tar/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

export FORCE_UNSAFE_CONFIGURE=1
cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/tar

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
