#!/bin/bash
NAME="texinfo"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/texinfo/texinfo-$VERS.tar.xz"
UPST="https://ftp.gnu.org/gnu/texinfo/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm
# make TEXMF=/usr/share/texmf install-tex

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
