#!/bin/bash
NAME="texinfo"
VERS="7.1.1"
LINK="https://ftp.gnu.org/gnu/texinfo/texinfo-$VERS.tar.xz"
UPST="https://git.savannah.gnu.org/git/texinfo.git"
VCMD="git ls-remote --tags 'https://git.savannah.gnu.org/git/texinfo.git' | sed 's:.*/::' | sort -V | tail -n1 | cut -d- -f2"
DEPS=""


idir() {

cm
# make TEXMF=/usr/share/texmf install-tex

}

rdir() {

echo not implemented

}
