#!/bin/bash
NAME="time"
VERS="1.9"
LINK="https://ftp.gnu.org/gnu/time/time-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/time/?C=M;O=D"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /bin/time

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
