#!/bin/bash

NAME="tree"
VERS="${!NAME}_version"
LINK="https://gitlab.com/OldManProgrammer/unix-tree/-/archive/$VERS/unix-tree-$VERS.tar.bz2"


IDIR=$(cat << '~fin.'

make
make PREFIX=/usr install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/tree

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
