#!/bin/bash
NAME="tree"
DESC="Utility for viewing file trees"
VERS="2.2.1"
LINK="https://gitlab.com/OldManProgrammer/unix-tree/-/archive/$VERS/unix-tree-$VERS.tar.bz2"
UPST="https://gitlab.com/OldManProgrammer/unix-tree.git"


idir() {

make
make PREFIX=/usr install

# fixes a make install bug where the mandir is /usr/man :shrug:
mv -vf /usr/man/man1/tree.1 /usr/share/man/man1/tree.1
rm -rvf /usr/man

}

rdir() {

rm -vf /usr/bin/tree
rm -vf /usr/share/man/man1/tree.1

}
