#!/bin/bash
NAME="tzdata"
VERS=2024b
LINK=""
DEPS="glibc"  # provides tzselect zic etc


IDIR=$(cat << '~fin.'

[ -e "$RIDSOURCES"/tzdata$VERS.tar.gz ] ||
raw https://data.iana.org/time-zones/releases/tzdata$VERS.tar.gz

mkdir -pv tzdata-$VERS && cd tzdata-$VERS
cp -vf "$RIDSOURCES"/tzdata$VERS.tar.gz .
tar xvf tzdata$VERS.tar.gz

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward; do
    zic -L /dev/null   -d $ZONEINFO       ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix ${tz}
    zic -L leapseconds -d $ZONEINFO/right ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

ln -sfv /usr/share/zoneinfo/$TZ /etc/localtime
echo "Set timezone to $TZ"

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
