#!/bin/bash
NAME="uchardet"
VERS="0.0.8"
LINK="https://www.freedesktop.org/software/uchardet/releases/uchardet-$VERS.tar.xz"
UPST="https://www.freedesktop.org/software/uchardet/releases/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="cmake"


idir() {

CN -D BUILD_STATIC=OFF

}

rdir() {

rm -rvf /usr/include/uchardet /usr/lib/libuchardet.so*
rm -vf /usr/bin/uchardet

}
