#!/bin/bash
NAME="uchardet"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.freedesktop.org/software/uchardet/releases/uchardet-$VERS.tar.xz"
DEPS="cmake"


IDIR=$(cat << '~fin.'

CN -D BUILD_STATIC=OFF

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/include/uchardet /usr/lib/libuchardet.so*
rm -vf /usr/bin/uchardet

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
