#!/bin/bash
NAME="uchardet"
VERS="0.0.8"
LINK="https://www.freedesktop.org/software/uchardet/releases/uchardet-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/uchardet/uchardet.git"
DEPS="cmake"


idir() {

CN -D BUILD_STATIC=OFF

}

rdir() {

rm -rvf /usr/include/uchardet /usr/lib/libuchardet.so*
rm -vf /usr/bin/uchardet

}
