#!/bin/bash
NAME="uthash"
VERS="2.3.0"
LINK="https://github.com/troydhanson/uthash/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/troydhanson/uthash/tags"
DEPS=""


idir() {

for h in src/*.h; do
    install -v -m644 $h /usr/include/
done

}

rdir() {

echo not implemented

}
