#!/bin/bash
NAME="util-macros"
VERS=1.20.1
LINK="https://www.x.org/pub/individual/util/util-macros-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

./configure $XORG_CONFIG
make install

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf $XORG_PREFIX/share/util-macros

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
