#!/bin/bash
NAME="util-macros"
VERS="1.20.2"
LINK="https://www.x.org/pub/individual/util/util-macros-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/util/macros/-/tags"
DEPS=""


idir() {

./configure $XORG_CONFIG
make install

}

rdir() {

rm -rvf /usr/share/util-macros

}
