#!/bin/bash
NAME="vulkan-headers"
VERS=1.3.299
LINK="https://github.com/KhronosGroup/Vulkan-Headers/archive/v$VERS/Vulkan-Headers-$VERS.tar.gz"
DEPS="cmake"


IDIR=$(cat <<EOF

mkdir build &&
cd    build &&

cmake -D CMAKE_INSTALL_PREFIX=/usr -G Ninja .. &&
ninja

ninja install

EOF
)

RDIR=$(cat <<EOF

rm -rvf \
    /usr/include/vk_video \
    /usr/include/vulkan   \
    /usr/share/vulkan     \
    /usr/share/cmake/VulkanHeaders

EOF
)

UDIR=$(cat <<EOF
EOF
)
