#!/bin/bash
NAME="vulkan-loader"
VERS="1.3.301"
LINK="https://github.com/KhronosGroup/Vulkan-Loader/archive/v$VERS/Vulkan-Loader-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/Vulkan-Loader/tags"
DEPS="cmake vulkan-headers libx11 libxrandr"


IDIR=$(cat << '~fin.'

CN

# specifying C*FLAGS is necessary here
ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 \
32CN

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/cmake/VulkanLoader \
        /usr/lib{,32}/libvulkan.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
