#!/bin/bash
NAME="vulkan-headers"
VERS="1.3.301"
LINK="https://github.com/KhronosGroup/Vulkan-Headers/archive/v$VERS/Vulkan-Headers-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/Vulkan-Headers/tags"
DEPS="cmake"


idir() {

CN

}

rdir() {

rm -rvf \
    /usr/include/vk_video \
    /usr/include/vulkan   \
    /usr/share/vulkan     \
    /usr/share/cmake/VulkanHeaders

}


