#!/bin/bash
NAME="vulkan_loader"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://github.com/KhronosGroup/Vulkan-Loader/archive/v$VERS/Vulkan-Loader-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/Vulkan-Loader/tags"
DEPS="cmake vulkan_headers xorg_libraries"


IDIR=$(cat << '~fin.'

mkdir build &&
cd    build &&

cmake -D CMAKE_INSTALL_PREFIX=/usr     \
      -D CMAKE_BUILD_TYPE=Release      \
      -D CMAKE_SKIP_INSTALL_RPATH=ON   \
      -G Ninja ..

ninja
DESTDIR=/ ninja install

rm -rf *
ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig   \
cmake -D CMAKE_INSTALL_PREFIX=/usr     \
      -D CMAKE_INSTALL_LIBDIR=lib32    \
      -D CMAKE_BUILD_TYPE=Release      \
      -D CMAKE_SKIP_INSTALL_RPATH=ON   \
      -G Ninja ..

ninja
DESTDIR=/tmp/rid/dest ninja install
cp -vr /tmp/rid/dest/usr/lib32/* /usr/lib32
rm -rf /tmp/rid/dest
ldconfig

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/lib/cmake/VulkanLoader \
        /usr/lib{,32}/libvulkan.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
