#!/bin/bash
NAME="vulkan_headers"
VERS="1.3.301"
LINK="https://github.com/KhronosGroup/Vulkan-Headers/archive/v$VERS/Vulkan-Headers-$VERS.tar.gz"
UPST="https://github.com/KhronosGroup/Vulkan-Headers/tags"
DEPS="cmake"


IDIR=$(cat << '~fin.'

CN

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf \
    /usr/include/vk_video \
    /usr/include/vulkan   \
    /usr/share/vulkan     \
    /usr/share/cmake/VulkanHeaders

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
