#!/bin/bash
NAME="wayland"
VERS="1.23.1"
LINK="https://gitlab.freedesktop.org/wayland/wayland/-/releases/$VERS/downloads/wayland-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/wayland/wayland/-/tags"
DEPS="libxml2"


idir() {

mn   -D documentation=false
32mn -D documentation=false

}

rdir() {

rm -vf \
    /usr/bin/wayland-scanner       \
    /usr/lib{,32}/libwayland-client.so* \
    /usr/lib{,32}/libwayland-cursor.so* \
    /usr/lib{,32}/libwayland-server.so* \
    /usr/lib{,32}/libwayland-egl.so*

rm -rvf /usr/share/wayland
    

}


