#!/bin/bash
NAME="wayland-protocols"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://gitlab.freedesktop.org/wayland/$NAME/-/releases/$VERS/downloads/$NAME-$VERS.tar.xz"
DEPS="wayland"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/wayland-protocols

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
