#!/bin/bash
NAME="wayland-protocols"
VERS="1.38"
LINK="https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$VERS/downloads/wayland-protocols-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/wayland/wayland-protocols.git"
DEPS="wayland"


idir() {

mn

}

rdir() {

rm -rvf /usr/share/wayland-protocols

}
