#!/bin/bash
NAME="wget"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://ftp.gnu.org/gnu/wget/wget-$VERS.tar.gz"
DEPS="libpsl make-ca libidn2"


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc \
   --with-ssl=openssl

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/wget \
   /usr/share/man/man1/wget.1

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
