#!/bin/bash
NAME="wget"
VERS="1.24.5"
LINK="https://ftp.gnu.org/gnu/wget/wget-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/wget/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > a:nth-child(1)"
DEPS="libpsl make_ca libidn2"


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc \
   --with-ssl=openssl

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/wget \
   /usr/share/man/man1/wget.1

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
