#!/bin/bash
NAME="wheel"
VERS=0.44.0
LINK="https://pypi.org/packages/source/w/wheel/wheel-$VERS.tar.gz"
DEPS="python"


IDIR=$(cat << '~fin.'

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links=dist wheel

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/wheel
rm -rvf /usr/lib/python3.12/site-packages/wheel*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
