#!/bin/bash
NAME="wheel"
VERS="0.45.0"
LINK="https://pypi.org/packages/source/w/wheel/wheel-$VERS.tar.gz"
UPST="https://pypi.org/project/wheel"
DEPS="python"


idir() {

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links=dist wheel

}

rdir() {

PV=$(gv python)
PV="${PV%.*}"

rm -vf /usr/bin/wheel
rm -rvf /usr/lib/python$PV/site-packages/wheel*

}


