#!/bin/bash
NAME="which"
VERS=2.21
LINK="https://ftp.gnu.org/gnu/which/which-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/which

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
