#!/bin/bash
NAME="which"
VERS="2.21"
LINK="https://ftp.gnu.org/gnu/which/which-$VERS.tar.gz"
UPST="https://ftp.gnu.org/gnu/which/?C=M;O=D"
VCMD="curl -s '$UPST' | grep which- | head -n1 | cut -d- -f2 | cut -d. -f1-2"
DEPS=""


idir() {

cm

}

rdir() {

rm -vf /usr/bin/which

}
