#!/bin/bash
NAME="whitepink"
VERS="0"
LINK=""
DEPS=""


IDIR=$(cat << '~fin.'

mkdir -pv /dots && cd /dots

rm -rvf $H/.config
rm -rvf whitepink

git clone https://github.com/Toxikuu/whitepink
chown -Rv $TARGET_USER:$TARGET_USER whitepink

ln -sfv /dots/whitepink/config $H/.config
echo "You should now set up files in extra manually. (/dots/whitepink/extra)"

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf $H/.config  \
        /dots/whitepink
echo "If you set up any files in /dots/nightdrive/extra, you're responsible for handling the removal of those."

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
