#!/bin/bash
NAME="whitepink"
VERS="9999"
DEPS="git"
NEWS="Some files (in /dots/whitepink/extra) must be set up manually."


idir() {

mkdir -pv /dots && cd /dots

rm -rvf $H/.config
rm -rvf whitepink

git clone https://github.com/Toxikuu/whitepink
chown -Rv $TARGET_USER:$TARGET_USER whitepink

ln -sfv /dots/whitepink/config $H/.config

}

rdir() {

rm -rvf $H/.config  \
        /dots/whitepink

}
