#!/bin/bash
NAME="x264"
VERS="20240812"
LINK="https://anduin.linuxfromscratch.org/BLFS/x264/x264-$VERS.tar.xz"
# there is like no upstream for this package lol
DEPS="nasm"


idir() {

cm --enable-shared --disable-cli

}

rdir() {

rm -vf /usr/lib/libx264.so*

}
