#!/bin/bash
NAME="x265"
VERS="4.1"
LINK="https://bitbucket.org/multicoreware/x265_git/downloads/x265_$VERS.tar.gz"
UPST="https://bitbucket.org/multicoreware/x265_git.git"
DEPS="cmake nasm"


idir() {

mkdir bld &&
cd    bld &&

cmake -D CMAKE_INSTALL_PREFIX=/usr \
      -D GIT_ARCHETYPE=1           \
      -W no-dev ../source          &&
make

make install &&
rm -vf /usr/lib/libx265.a

}

rdir() {

rm -vf /usr/bin/x265 /usr/lib/libx265.so*

}
