#!/bin/bash
NAME="xauth"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/app/xauth-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xauth.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sed 's/\^{}//' | sort -V | grep -B1 xf86-4_3_0_1 | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libxmu libxau libxext libx11 util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
