#!/bin/bash
NAME="xauth"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/app/xauth-1.1.3.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xauth/-/tags"
DEPS="libxmu libxau libxext libx11 util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


