#!/bin/bash
NAME="xbitmaps"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/data/$NAME-$VERS.tar.xz"
UPST="https://archlinux.org/packages/extra/any/xbitmaps/" # the actual upstream is annoying to parse
DEPS="util-macros"


idir() {

./configure $XORG_CONFIG
make install

}

rdir() {

rm -vf /usr/include/X11/bitmaps

}
