#!/bin/bash
NAME="xcb-util-keysyms"
VERS="0.4.1"
LINK="https://xcb.freedesktop.org/dist/xcb-util-keysyms-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-keysyms/-/tags"
DEPS="libxcb"


idir() {

cm

}

rdir() {

rm -vf /usr/lib/libxcb-keysyms.*

}
