#!/bin/bash
NAME="xcb-util-image"
VERS=0.4.1
LINK="https://xcb.freedesktop.org/dist/xcb-util-image-$VERS.tar.xz"
DEPS="xcb-util"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-image.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
