#!/bin/bash
NAME="xcb-util-xrm"
VERS="1.3"
LINK="https://github.com/Airblader/xcb-util-xrm/releases/download/v$VERS/xcb-util-xrm-$VERS.tar.bz2"
UPST="https://github.com/Airblader/xcb-util-xrm.git"
DEPS="xcb-util util-macros"


idir() {

cm

}

rdir() {

echo not implemented

}
