#!/bin/bash
NAME="xcb-util-errors"
VERS=1.0.1
LINK="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
DEPS="xcb-proto"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-errors.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
