#!/bin/bash
NAME="xcb-util-renderutil"
VERS="0.3.10"
LINK="https://xcb.freedesktop.org/dist/xcb-util-renderutil-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-render-util/-/tags"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-render-util.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
