#!/bin/bash
NAME="xcb-util-keysyms"
VERS=0.4.1
LINK="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-keysyms.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
