#!/bin/bash
NAME="xcb-proto"
VERS="${!NAME}_version"
LINK="https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-$VERS.tar.xz"
DEPS=""


IDIR=$(cat << '~fin.'

PYTHON=python3 ./configure $XORG_CONFIG
make install

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/xcb/ \
        /usr/lib/python3.13/site-packages/xcbgen

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
