#!/bin/bash
NAME="xcb-util"
VERS="0.4.1"
LINK="https://xcb.freedesktop.org/dist/xcb-util-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -v gitlab | tail -n1 | cut -d- -f3"
DEPS="libxcb"


idir() {

cm

}

rdir() {

rm -vf /usr/lib/libxcb-util.*

}
