#!/bin/bash
NAME="xcb-proto"
VERS="1.17.0"
LINK="https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-$VERS.tar.xz"
UPST="https://repology.org/project/xcb-proto/information"
DEPS=""


idir() {

PYTHON=python3 ./configure $XORG_CONFIG
make install

}

rdir() {

PV=$(gv python)
PV=${PV%.*}

rm -rvf /usr/share/xcb/ \
        /usr/lib/python$PV/site-packages/xcbgen

    }
