#!/bin/bash
NAME="xcb-util"
VERS="0.4.1"
LINK="https://xcb.freedesktop.org/dist/xcb-util-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-util/-/tags"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-util.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
