#!/bin/bash
NAME="xcb-util-wm"
VERS="0.4.2"
LINK="https://xcb.freedesktop.org/dist/xcb-util-wm-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-wm/-/tags"
DEPS="libxcb"


idir() {

cm

}

rdir() {

rm -vf  /usr/lib/libxcb-ewmh.* \
        /usr/lib/libxcb-icccm.*

    }
