#!/bin/bash
NAME="xcb-util-wm"
VERS=0.4.2
LINK="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/lib/libxcb-ewmh.* \
        /usr/lib/libxcb-icccm.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
