#!/bin/bash
NAME="xcb-util-xrm"
VERS="1.3"
LINK="https://github.com/Airblader/xcb-util-xrm/releases/download/v$VERS/xcb-util-xrm-$VERS.tar.gz"
UPST="https://github.com/Airblader/xcb-util-xrm/tags"
DEPS="xcb-util util-macros"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
