#!/bin/bash
NAME="xcb-util-cursor"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
DEPS="xcb-util-image xcb-util-renderutil"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-cursor.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
