#!/bin/bash
NAME="xcb_util_wm"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://xcb.freedesktop.org/dist/xcb-util-wm-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-wm/-/tags"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/lib/libxcb-ewmh.* \
        /usr/lib/libxcb-icccm.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
