#!/bin/bash
NAME="xcb_util_keysyms"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://xcb.freedesktop.org/dist/xcb-util-keysyms-$VERS.tar.xz"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-keysyms.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
