#!/bin/bash
NAME="xcb_util_image"
VERS="0.4.1"
LINK="https://xcb.freedesktop.org/dist/xcb-util-image-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/tags"
DEPS="xcb_util"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-image.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
