#!/bin/bash
NAME="xcb_util"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://xcb.freedesktop.org/dist/xcb-util-$VERS.tar.xz"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-util.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
