#!/bin/bash
NAME="xcb_util_keysyms"
VERS="0.4.1"
LINK="https://xcb.freedesktop.org/dist/xcb-util-keysyms-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-keysyms/-/tags"
DEPS="libxcb"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib/libxcb-keysyms.*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
