#!/bin/bash
NAME="xcb_proto"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-$VERS.tar.xz"
UPST="https://repology.org/project/xcb-proto/information"
DEPS=""


IDIR=$(cat << '~fin.'

PYTHON=python3 ./configure $XORG_CONFIG
make install

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/xcb/ \
        /usr/lib/python3.13/site-packages/xcbgen

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
