#!/bin/bash
NAME="xclip"
VERS="0.13"
LINK="https://github.com/astrand/xclip/archive/refs/tags/$VERS.tar.gz"
UPST="https://github.com/astrand/xclip/tags"
DEPS=""


idir() {

autoconf -fv
# cm doesn't work because --disable-static throws an error
./configure --prefix=/usr
make
make install

}

rdir() {

rm -vf  /usr/bin/xclip{,-*}  \
        /usr/share/man/man1/xclip{.1,-copyfile.1}

    }


