#!/bin/bash
NAME="xclip"
VERS="${!NAME}_version"
LINK="https://github.com/astrand/xclip/archive/refs/tags/$VERS.tar.gz"
UPST="https://github.com/astrand/xclip/tags"
DEPS=""


IDIR=$(cat << '~fin.'

autoconf -fv
# cm doesn't work because --disable-static throws an error
./configure --prefix=/usr
make
make install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/xclip{,-*}  \
        /usr/share/man/man1/xclip{.1,-copyfile.1}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
