#!/bin/bash
NAME="xcmsdb"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/app/xcmsdb-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xcmsdb/-/tags"
DEPS="libx11 util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
