#!/bin/bash
NAME="xcmsdb"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/app/xcmsdb-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xcmsdb/-/tags"
DEPS="libx11 util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


