#!/bin/bash
NAME="xcmsdb"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/app/xcmsdb-1.0.7.tar.xz"
DEPS="libx11 util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
