#!/bin/bash
NAME="xcursor_themes"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/data/xcursor-themes-$VERS.tar.xz"
DEPS="xorg_applications"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/icons/{redglass,handhelds,whiteglass}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
