#!/bin/bash
NAME="xcursorgen"
VERS="1.0.8"
LINK="https://www.x.org/pub/individual/app/xcursorgen-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xcursorgen/-/tags"
DEPS="libx11 libxcursor libpng util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
