#!/bin/bash
NAME="xcursorgen"
VERS="1.0.8"
LINK="https://www.x.org/pub/individual/app/xcursorgen-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xcursorgen.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 xcursorgen-1_0_1 | head -n1 | cut -d- -f2"
DEPS="libx11 libxcursor libpng util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
