#!/bin/bash
NAME="xcursor-themes"
VERS="${!NAME}_version"
LINK="https://www.x.org/pub/individual/data/$NAME-$VERS.tar.xz"
DEPS="xorg-applications"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/icons/{redglass,handhelds,whiteglass}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
