#!/bin/bash
NAME="xcursor-themes"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/data/xcursor-themes-$VERS.tar.xz"
UPST="https://repology.org/project/xcursor-themes/information"
DEPS="util-macros xcursorgen pkgconf"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/icons/{redglass,handhelds,whiteglass}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
