#!/bin/bash
NAME="xdg-user-dirs"
VERS="${!NAME}_version"
LINK="https://user-dirs.freedesktop.org/releases/$NAME-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc --disable-documentation

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
