#!/bin/bash
NAME="xdg-user-dirs"
VERS="0.18"
LINK="https://user-dirs.freedesktop.org/releases/xdg-user-dirs-$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/xdg/xdg-user-dirs.git"
DEPS=""


idir() {

cm --sysconfdir=/etc --disable-documentation

}

rdir() {

echo not implemented

}
