#!/bin/bash
NAME="xdg-utils"
VERS="1.2.1"
LINK="https://gitlab.freedesktop.org/xdg/xdg-utils/-/archive/v$VERS/xdg-utils-v$VERS.tar.gz"
UPST="https://gitlab.freedesktop.org/xdg/xdg-utils.git"
DEPS="xmlto lynx xset xprop"


idir() {

# cant do cm because --disable-static causes a build failure lol
./configure --prefix=/usr &&
make &&
make install

}

rdir() {

pushd /usr/bin
  rm -vf \
    xdg-desktop-menu  \
    xdg-desktop-icon  \
    xdg-mime          \
    xdg-icon-resource \
    xdg-open          \
    xdg-email         \
    xdg-screensaver   \
    xdg-settings     &&
popd

}
