#!/bin/bash
NAME="xdg_utils"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://gitlab.freedesktop.org/xdg/xdg-utils/-/archive/v$VERS/xdg-utils-v$VERS.tar.gz"
DEPS="xmlto lynx xorg_applications"


IDIR=$(cat << '~fin.'

./configure --prefix=/usr &&
make &&
make install

~fin.
)

RDIR=$(cat << '~fin.'

pushd /usr/bin
  rm -vf \
    xdg-desktop-menu  \
    xdg-desktop-icon  \
    xdg-mime          \
    xdg-icon-resource \
    xdg-open          \
    xdg-email         \
    xdg-screensaver   \
    xdg-settings     &&
popd

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
