#!/bin/bash
NAME="xdg_user_dirs"
VERS="0.18"
LINK="https://user-dirs.freedesktop.org/releases/xdg-user-dirs-$VERS.tar.gz"
UPST="https://user-dirs.freedesktop.org/releases/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc --disable-documentation

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
