#!/bin/bash
NAME="xdg_user_dirs"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://user-dirs.freedesktop.org/releases/xdg-user-dirs-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

cm --sysconfdir=/etc --disable-documentation

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
