#!/bin/bash
NAME="xdotool"
VERS="3.20211022.1"
LINK="https://github.com/jordansissel/xdotool/releases/download/v$VERS/xdotool-$VERS.tar.gz"
UPST="https://github.com/jordansissel/xdotool/tags"
DEPS=""


idir() {

make WITHOUT_RPATH_FIX=1
make PREFIX=/usr INSTALLMAN=/usr/share/man install

}

rdir() {

rm -vf /usr/bin/xdotool /usr/lib/libxdo.so*

}


