#!/bin/bash
NAME="xdpyinfo"
VERS="1.3.4"
LINK="https://www.x.org/pub/individual/app/xdpyinfo-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xdpyinfo.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 xf86-4_3_0_1 | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libx11 libxext libxtst libxxf86vm libxrender libxcomposite libxinerama util-macros xorgproto"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
