#!/bin/bash
NAME="xev"
VERS="1.2.6"
LINK="https://www.x.org/pub/individual/app/xev-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xev.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 xev-1_0_2 | head -n1 | cut -d- -f2"
DEPS="libx11 libxrandr util-macros xorgproto"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
