#!/bin/bash
NAME="xf86-input-libinput"
VERS="${!NAME}_version"
LINK="https://www.x.org/pub/individual/driver/$NAME-$VERS.tar.xz"
DEPS="libinput xorg-server"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
