#!/bin/bash
NAME="xf86-input-libinput"
VERS="1.5.0"
LINK="https://www.x.org/pub/individual/driver/xf86-input-libinput-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f4"
DEPS="libinput xorg-server"


idir() {

cm

}

rdir() {

echo not implemented

}
