#!/bin/bash
NAME="xf86-input-evdev"
VERS=2.10.6
LINK="https://www.x.org/pub/individual/driver/$NAME-$VERS.tar.bz2"
DEPS="libevdev mtdev xorg-server"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
