#!/bin/bash
NAME="xf86_input_evdev"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/driver/xf86-input-evdev-$VERS.tar.xz"
DEPS="libevdev mtdev xorg_server"


IDIR=$(cat << '~fin.'

cm

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
