#!/bin/bash
NAME="xhost"
VERS="1.0.9"
LINK="https://www.x.org/pub/individual/app/xhost-$VERS.tar.xz"
DEPS="libx11 libxmu util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
