#!/bin/bash
NAME="xhost"
VERS="1.0.9"
LINK="https://www.x.org/pub/individual/app/xhost-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xhost.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n3 | head -n1 | cut -d- -f2"
DEPS="libx11 libxmu util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
