#!/bin/bash
NAME="xinit"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/app/xinit-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xinit/-/tags"
DEPS="xorg_libraries"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG --with-xinitdir=/etc/X11/app-defaults
ldconfig

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
