#!/bin/bash
NAME="xinput"
VERS="1.6.4"
LINK="https://www.x.org/pub/individual/app/xinput-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xinput/-/tags"
DEPS="util-macros xorgproto libxfixes libxi libx11 libxinerama"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
