#!/bin/bash
NAME="xkbcomp"
VERS="1.4.7"
LINK="https://www.x.org/pub/individual/app/xkbcomp-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xkbcomp/-/tags"
DEPS="libx11 util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


