#!/bin/bash
NAME="xkbcomp"
VERS="1.4.7"
LINK="https://www.x.org/pub/individual/app/xkbcomp-$VERS.tar.xz"
DEPS="libx11 util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
