#!/bin/bash
NAME="xkbevd"
VERS="1.1.6"
LINK="https://www.x.org/pub/individual/app/xkbevd-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xkbevd.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n3 | head -n1 | cut -d- -f2"
DEPS="util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
