#!/bin/bash
NAME="xkbevd"
VERS="1.1.5"
LINK="https://www.x.org/pub/individual/app/xkbevd-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xkbevd/-/tags"
DEPS="util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
