#!/bin/bash
NAME="xkbutils"
VERS="1.0.6"
LINK="https://www.x.org/pub/individual/app/xkbutils-$VERS.tar.xz"
DEPS="util-macros xorgproto libxt libxaw libx11"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
