#!/bin/bash
NAME="xkeyboard-config"
VERS="2.43"
LINK="https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
DEPS=""


idir() {

mn

}

rdir() {

rm -rvf /usr/share/X11/xkb

}
