#!/bin/bash
NAME="xkeyboard-config"
VERS="${!NAME}_version"
LINK="https://www.x.org/pub/individual/data/xkeyboard-config/$NAME-$VERS.tar.xz"
DEPS="xorg-libraries"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/X11/xkb

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
