#!/bin/bash
NAME="xkeyboard_config"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$VERS.tar.xz"
UPST="https://www.x.org/archive/individual/data/xkeyboard-config/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="xorg_libraries"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/X11/xkb

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
