#!/bin/bash
NAME="xkeyboard_config"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$VERS.tar.xz"
DEPS="xorg_libraries"


IDIR=$(cat << '~fin.'

mn

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/X11/xkb

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
