#!/bin/bash
NAME="xkill"
VERS="1.0.6"
LINK="https://www.x.org/pub/individual/app/xkill-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xkill.git"
VCMD="git ls-remote --tags 'https://gitlab.freedesktop.org/xorg/app/xkill.git' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libx11 libxmu util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
