#!/bin/bash
NAME="xkill"
VERS="1.0.6"
LINK="https://www.x.org/pub/individual/app/xkill-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xkill/-/tags"
DEPS="libx11 libxmu util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


