#!/bin/bash
NAME="xlsatoms"
VERS="1.1.4"
LINK="https://www.x.org/pub/individual/app/xlsatoms-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xlsatoms.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="util-macros xorgproto libxcb"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
