#!/bin/bash
NAME="xlsatoms"
VERS="1.1.4"
LINK="https://www.x.org/pub/individual/app/xlsatoms-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xlsatoms/-/tags"
DEPS="util-macros xorgproto libxcb"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
