#!/bin/bash
NAME="xlsclients"
VERS="1.1.5"
LINK="https://www.x.org/pub/individual/app/xlsclients-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xlsclients/-/tags"
DEPS="util-macros xorgproto libxcb"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
