#!/bin/bash
NAME="xmessage"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/app/xmessage-$VERS.tar.xz"
DEPS="libxaw libx11 libxt util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
