#!/bin/bash
NAME="xml-parser"
VERS=2.47
LINK="https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

perl Makefile.PL

make
make install

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
