#!/bin/bash
NAME="xml-parser"
VERS="2.47"
LINK="https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-$VERS.tar.gz"
UPST="https://github.com/cpan-authors/XML-Parser.git"
DEPS=""


idir() {

perl Makefile.PL

make
make install

}

rdir() {

echo not implemented

}
