#!/bin/bash
NAME="xmlto"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://pagure.io/xmlto/archive/$VERS/xmlto-$VERS.tar.gz"
UPST="https://pagure.io/xmlto/releases"
SELE=".col > div:nth-child(2)"
DEPS="docbook_xml docbook_xsl_nons libxslt"


IDIR=$(cat << '~fin.'

autoreconf -fiv &&
LINKS="/usr/bin/links" cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf /usr/share/xmlto  \
  /usr/bin/xmlif          \
  /usr/bin/xmlto          

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
