#!/bin/bash
NAME="xmlto"
VERS="0.0.29"
LINK="https://pagure.io/xmlto/archive/$VERS/xmlto-$VERS.tar.gz"
UPST="https://pagure.io/xmlto/releases"
SELE=".col > div:nth-child(2)"
DEPS="docbook-xml docbook-xsl-nons libxslt"


idir() {

autoreconf -fiv &&
LINKS="/usr/bin/links" cm

}

rdir() {

rm -rvf /usr/share/xmlto  \
  /usr/bin/xmlif          \
  /usr/bin/xmlto          

}


