#!/bin/bash
NAME="xmodmap"
VERS="1.0.11"
LINK="https://www.x.org/pub/individual/app/xmodmap-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xmodmap.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n3 | head -n1 | cut -d- -f2"
DEPS="util-macros libx11"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
