#!/bin/bash
NAME="xorg-server"
VERS="21.1.15"
LINK="https://www.x.org/archive/individual/xserver/xorg-server-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/xserver.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | grep -B1 xo-6_7_0 | head -n1 | cut -d- -f3"
DEPS="libxcvt pixman xkeyboard-config dbus2 elogind libepoxy libunwind nettle xcb-util-keysyms xcb-util-image xcb-util-renderutil xcb-util-wm font-util"


idir() {

mn \
    --localstatedir=/var    \
    -D glamor=true          \
    -D secure-rpc=false     \
    -D xkb_output_dir=/var/lib/xkb

mkdir -pv /etc/X11/xorg.conf.d &&
install -v -d -m1777 /tmp/.{ICE,X11}-unix &&
cat >> /etc/sysconfig/createfiles << "EOF"
/tmp/.ICE-unix dir 1777 root root
/tmp/.X11-unix dir 1777 root root
EOF

}

rdir() {

echo not implemented

}
