#!/bin/bash
NAME="xorgproto"
VERS=2024.1
LINK="https://xorg.freedesktop.org/archive/individual/proto/xorgproto-$VERS.tar.xz"
DEPS="util-macros"


IDIR=$(cat << '~fin.'

mn
mv -v /usr/share/doc/xorgproto{,-2024.1}

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/share/doc/xorgproto-2024.1/

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
