#!/bin/bash
NAME="xorgproto"
VERS="2024.1"
LINK="https://xorg.freedesktop.org/archive/individual/proto/xorgproto-$VERS.tar.xz"
UPST="https://repology.org/project/xorgproto/information"
DEPS="util-macros"


idir() {

mn
mv -v /usr/share/doc/xorgproto{,-2024.1}

}

rdir() {

rm -vf /usr/share/doc/xorgproto-2024.1/

}
