#!/bin/bash
NAME="xorg_fonts"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK=""
DEPS="xcursor_themes wget"


IDIR=$(cat << '~fin.'

cat > font-7-list << "EOF"
font-util-1.4.1.tar.xz
encodings-1.1.0.tar.xz
font-alias-1.0.5.tar.xz
font-adobe-utopia-type1-1.0.5.tar.xz
font-bh-ttf-1.0.4.tar.xz
font-bh-type1-1.0.4.tar.xz
font-ibm-type1-1.0.4.tar.xz
font-misc-ethiopic-1.0.5.tar.xz
font-xfree86-type1-1.0.5.tar.xz
EOF

mkdir font &&
cd font &&
grep -v '^#' ../font-7-list | wget -i- -c \
    -B https://www.x.org/pub/individual/font/

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root

for package in $(grep -v '^#' ../font-7-list)
do
  packagedir=${package%.tar.?z*}
  tar -xf $package
  pushd $packagedir
    ./configure $XORG_CONFIG
    make
    as_root make install
  popd
  as_root rm -rf $packagedir
done

install -v -d -m755 /usr/share/fonts                               &&
ln -svfn $XORG_PREFIX/share/fonts/X11/OTF /usr/share/fonts/X11-OTF &&
ln -svfn $XORG_PREFIX/share/fonts/X11/TTF /usr/share/fonts/X11-TTF

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/bdftruncate    \
        /usr/bin/ucs2any        \

rm -rvf /usr/share/fonts/X11{,-TTF,-OTF}

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
