#!/bin/bash
NAME="xorg_server"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://www.x.org/pub/individual/xserver/xorg-server-$VERS.tar.xz"
UPST="https://www.x.org/archive/individual/xserver/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="libxcvt pixman xkeyboard_config dbus2 elogind libepoxy libunwind nettle xcb_util_keysyms xcb_util_image xcb_util_renderutil xcb_util_wm"


IDIR=$(cat << '~fin.'

mn \
    --localstatedir=/var    \
    -D glamor=true          \
    -D secure-rpc=false     \
    -D xkb_output_dir=/var/lib/xkb

mkdir -pv /etc/X11/xorg.conf.d &&
install -v -d -m1777 /tmp/.{ICE,X11}-unix &&
cat >> /etc/sysconfig/createfiles << "EOF"
/tmp/.ICE-unix dir 1777 root root
/tmp/.X11-unix dir 1777 root root
EOF

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
