#!/bin/bash
NAME="xpr"
VERS="1.2.0"
LINK="https://www.x.org/pub/individual/app/xpr-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xpr.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1 | cut -d- -f2"
DEPS="libx11 libxmu util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
