#!/bin/bash
NAME="xpr"
VERS="1.2.0"
LINK="https://www.x.org/pub/individual/app/xpr-$VERS.tar.xz"
DEPS="libx11 libxmu util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
