#!/bin/bash
NAME="xprop"
VERS="1.2.7"
LINK="https://www.x.org/pub/individual/app/xprop-$VERS.tar.xz"
DEPS="util-macros libx11"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
