#!/bin/bash
NAME="xprop"
VERS="1.2.8"
LINK="https://www.x.org/pub/individual/app/xprop-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xprop/-/tags"
DEPS="util-macros libx11"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
