#!/bin/bash
NAME="xprop"
VERS="1.2.8"
LINK="https://www.x.org/pub/individual/app/xprop-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xprop/-/tags"
DEPS="util-macros libx11"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
