#!/bin/bash
NAME="xrandr"
VERS="1.5.3"
LINK="https://www.x.org/pub/individual/app/xrandr-$VERS.tar.xz"
DEPS="libx11 libxrandr util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
