#!/bin/bash
NAME="xrandr"
VERS="1.5.3"
LINK="https://www.x.org/pub/individual/app/xrandr-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xrandr.git"
VCMD="git ls-remote --tags 'https://gitlab.freedesktop.org/xorg/app/xrandr.git' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libx11 libxrandr util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
