#!/bin/bash
NAME="xrdb"
VERS="1.2.2"
LINK="https://www.x.org/pub/individual/app/xrdb-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xrdb/-/tags"
DEPS="libx11 libxmu util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
