#!/bin/bash
NAME="xrefresh"
VERS="1.1.0"
LINK="https://www.x.org/pub/individual/app/xrefresh-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xrefresh.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libx11 util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
