#!/bin/bash
NAME="xsetroot"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/app/xsetroot-$VERS.tar.xz"
DEPS="libxmu libx11 libxcursor xbitmaps util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
