#!/bin/bash
NAME="xsetroot"
VERS="1.1.3"
LINK="https://www.x.org/pub/individual/app/xsetroot-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xsetroot.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="libxmu libx11 libxcursor xbitmaps util-macros"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
