#!/bin/bash
NAME="xset"
VERS="1.2.5"
LINK="https://www.x.org/pub/individual/app/xset-$VERS.tar.xz"
DEPS="libxmu util-macros"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
