#!/bin/bash
NAME="xtrans"
VERS="1.5.2"
LINK="https://www.x.org/releases/individual/lib/xtrans-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/tags"
DEPS=""


idir() {

cm $XORG_CONFIG

CC="gcc -m32" CXX="g++ -m32" PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure $XORG_CONFIG_32
make
make DESTDIR=$PWD/DESTDIR install
cp -vr DESTDIR/usr/share/pkgconfig/* /usr/lib32/pkgconfig
rm -rf DESTDIR

}

rdir() {

echo not implemented

}


