#!/bin/bash
NAME="xwayland"
VERS="24.1.4"
LINK="https://www.x.org/pub/individual/xserver/xwayland-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/xserver.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n1 | cut -d- -f2"
DEPS="libxcvt libxfont2 libglvnd libxau wayland libdrm libxshmfence xtrans xorgproto dbus2 pixman wayland-protocols libepoxy mesa"


idir() {

sed -i '/install_man/,$d' meson.build &&

mn \
    -D xkb_output_dir=/var/lib/xkb \
    -D secure-rpc=false

cat >> /etc/sysconfig/createfiles << "EOF"
/tmp/.X11-unix dir 1777 root root
EOF

}

rdir() {

rm -vf /usr/bin/Xwayland

}
