#!/bin/bash
NAME="xwayland"
VERS="24.1.4"
LINK="https://www.x.org/pub/individual/xserver/xwayland-$VERS.tar.xz"
UPST="https://www.x.org/releases/individual/xserver/?C=N;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS="libxcvt pixman wayland_protocols xorg_applications xorg_fonts libepoxy mesa"


IDIR=$(cat << '~fin.'

sed -i '/install_man/,$d' meson.build &&

mn \
    -D xkb_output_dir=/var/lib/xkb \
    -D secure-rpc=false

cat >> /etc/sysconfig/createfiles << "EOF"
/tmp/.X11-unix dir 1777 root root
EOF

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/bin/Xwayland

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
