#!/bin/bash
NAME="xwd"
VERS="1.0.9"
LINK="https://www.x.org/pub/individual/app/xwd-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xwd/-/tags"
DEPS="libx11 util-macros libxt"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}


