#!/bin/bash
NAME="xwd"
VERS="1.0.9"
LINK="https://www.x.org/pub/individual/app/xwd-$VERS.tar.xz"
DEPS="libx11 util-macros libxt"


IDIR=$(cat << '~fin.'

cm $XORG_CONFIG

~fin.
)

RDIR=$(cat << '~fin.'

echo not implemented

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
