#!/bin/bash
NAME="xwinwrap"
VERS="0.9"
LINK="https://github.com/mmhobi7/xwinwrap/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/mmhobi7/xwinwrap.git"
DEPS="libx11 libxext libxrender"


idir() {

sed -i 's/usr\/local/usr/' Makefile || die "sed failed"
make                                || die "make failed"
make install                        || die "make install failed"

}

rdir() {

rm -vf /bin/xwinwrap

}
