#!/bin/bash
NAME="xwud"
VERS="1.0.7"
LINK="https://www.x.org/pub/individual/app/xwud-$VERS.tar.xz"
UPST="https://gitlab.freedesktop.org/xorg/app/xwud.git"
VCMD="git ls-remote --tags '$UPST' | sed 's:.*/::' | sort -V | tail -n2 | head -n1 | cut -d- -f2"
DEPS="util-macros libx11"


idir() {

cm $XORG_CONFIG

}

rdir() {

echo not implemented

}
