#!/bin/bash
NAME="xxhash"
VERS="0.8.2"
LINK="https://github.com/Cyan4973/xxHash/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/Cyan4973/xxHash/releases/latest"
DEPS=""


idir() {

make PREFIX=/usr
make PREFIX=/usr install

}

rdir() {

rm -vf /usr/lib/libxxhash.so*

}
