#!/bin/bash
NAME="yajl"
VERS="${!NAME}_version"
LINK="https://github.com/lloyd/yajl/archive/refs/tags/$VERS.tar.gz"
DEPS="cmake"


IDIR=$(cat << '~fin.'

[ -e "$RIDSOURCES"/yajl-2.1.0-CVE-2017-16516.patch ] ||
raw https://gitlab.archlinux.org/archlinux/packaging/packages/yajl/-/raw/main/yajl-2.1.0-CVE-2017-16516.patch
[ -e "$RIDSOURCES"/yajl-2.1.0-CVE-2022-24795.patch ] ||
raw https://gitlab.archlinux.org/archlinux/packaging/packages/yajl/-/raw/main/yajl-2.1.0-CVE-2022-24795.patch
[ -e "$RIDSOURCES"/yajl-2.1.0-memory_leak.patch ] ||
raw https://gitlab.archlinux.org/archlinux/packaging/packages/yajl/-/raw/main/yajl-2.1.0-memory_leak.patch

patch -Np1 -i "$RIDSOURCES"/yajl-2.1.0-CVE-2017-16516.patch
patch -Np1 -i "$RIDSOURCES"/yajl-2.1.0-CVE-2022-24795.patch
patch -Np1 -i "$RIDSOURCES"/yajl-2.1.0-memory_leak.patch

cmake \
    -B ridbuild                     \
    -D CMAKE_BUILD_TYPE=Release     \
    -D CMAKE_INSTALL_PREFIX=/usr    \
    -W no-dev

make -C ridbuild
make -C ridbuild DESTDIR= install

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/lib/libyajl.so* \
        /usr/lib/libyajl_s.a

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
