#!/bin/bash
NAME="yasm"
VERS=1.3.0
LINK="https://www.tortall.net/projects/yasm/releases/yasm-$VERS.tar.gz"
DEPS=""


IDIR=$(cat << '~fin.'

sed -i 's#) ytasm.*#)#' Makefile.in &&
cm

~fin.
)

RDIR=$(cat << '~fin.'

rm -rvf \
    /usr/include/libyasm                \
    /usr/include/libyasm{,-stdint}.h    \
    /usr/bin/yasm                       \
    /usr/lib/libyasm.a

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
