#!/bin/bash
NAME="yasm"
VERS="1.3.0"
LINK="https://github.com/yasm/yasm/archive/refs/tags/v$VERS.tar.gz"
UPST="https://github.com/yasm/yasm.git"
DEPS=""


idir() {

sed -i 's#) ytasm.*#)#' Makefile.in &&
cm

}

rdir() {

rm -rvf \
    /usr/include/libyasm                \
    /usr/include/libyasm{,-stdint}.h    \
    /usr/bin/yasm                       \
    /usr/lib/libyasm.a

}
