#!/bin/bash
NAME="yasm"
VERS="1.3.0"
LINK="https://www.tortall.net/projects/yasm/releases/yasm-$VERS.tar.gz"
UPST="https://yasm.tortall.net/Download.html"
SELE="#latest-release-130"
DEPS=""


idir() {

sed -i 's#) ytasm.*#)#' Makefile.in &&
cm

}

rdir() {

rm -rvf \
    /usr/include/libyasm                \
    /usr/include/libyasm{,-stdint}.h    \
    /usr/bin/yasm                       \
    /usr/lib/libyasm.a

}
