#!/bin/bash
NAME="zip"
VERS="3.0"
LINK="https://downloads.sourceforge.net/infozip/zip${VERS//./}.tar.gz"
UPST="https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/"
SELE=".current-dir"
DEPS=""


idir() {

make -f unix/Makefile generic CC="gcc -std=gnu89"
make prefix=/usr MANDIR=$RIDTRASH -f unix/Makefile install

}

rdir() {

rm -vf /bin/zip{,cloak,note,split}

}
