#!/bin/bash
NAME="zip"
VERS="3.0"
LINK="https://downloads.sourceforge.net/infozip/zip${VERS//./}.tar.gz"
UPST="https://infozip.sourceforge.net/Zip.html" # 3.0 is from 2008, but I'll include upstream anyway
VCMD="curl -s '$UPST' | grep -oE 'Zip [0-9]+\.[0-9]+' | head -n1 | cut -d' ' -f2"
DEPS=""


idir() {

make -f unix/Makefile generic CC="gcc -std=gnu89"
make prefix=/usr MANDIR=$RIDTRASH -f unix/Makefile install

}

rdir() {

rm -vf /bin/zip{,cloak,note,split}

}
