#!/bin/bash
NAME="zlib"
VERS="1.3.1"
LINK="https://zlib.net/fossils/zlib-$VERS.tar.gz"
UPST="https://github.com/madler/zlib.git"
DEPS=""


idir() {

./configure --prefix=/usr
make && make install
rm -vf /usr/lib/libz.a

make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --libdir=/usr/lib32

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR

rm -vf /usr/lib32/libz.a

}

rdir() {

rm -vf /usr/lib{,32}/libz.so*

}
