#!/bin/bash
NAME="zlib"
VERS="${NAME}_version"; VERS="${!VERS}"
LINK="https://zlib.net/fossils/zlib-$VERS.tar.gz"
UPST="https://zlib.net/fossils/?C=M;O=D"
SELE="body > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(1)"
DEPS=""


IDIR=$(cat << '~fin.'

./configure --prefix=/usr
make && make install
rm -vf /usr/lib/libz.a

make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --libdir=/usr/lib32

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR

rm -vf /usr/lib32/libz.a

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf /usr/lib{,32}/libz.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
