#!/bin/bash
NAME="zstd"
VERS="1.5.6"
LINK="https://github.com/facebook/zstd/releases/download/v$VERS/zstd-$VERS.tar.gz"
UPST="https://github.com/facebook/zstd/tags"
DEPS=""


IDIR=$(cat << '~fin.'

make prefix=/usr
make prefix=/usr install
rm -vf /usr/lib/libzstd.a

make clean
CC="gcc -m32" make prefix=/usr
make prefix=/usr DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib/* /usr/lib32/
sed -e "/^libdir/s/lib$/lib32/" -i /usr/lib32/pkgconfig/libzstd.pc
rm -rf DESTDIR
rm -vf /usr/lib32/libzstd.a

~fin.
)

RDIR=$(cat << '~fin.'

rm -vf  /usr/bin/zstd{,cat,grep,less,mt}    \
        /usr/bin/unzstd                     \
        /usr/lib{,32}/libzstd.so*

~fin.
)

UDIR=$(cat << '~fin.'
~fin.
)
